import enum


class KeymastersKeepGamePlatforms(enum.Enum):
    _32X = "32X"  # Sega 32X
    _3DO = "3D0"  # 3DO Multiplayer
    _3DS = "3DS"  # Nintendo 3DS
    A2 = "A2"  # Apple II
    A26 = "A26"  # Atari 2600
    A2GS = "A2GS"  # Apple IIGS
    A52 = "A52"  # Atari 5200
    A78 = "A78"  # Atari 7800
    A8 = "A8"  # Atari 8-bit: 400, 800, XL, XE
    ADV = "ADV"  # Entex AdventureVision
    AMI = "AMI"  # Commodore Amiga
    AND = "AND"  # Android OS
    ARC = "ARC"  # Arcade
    ARCH = "ARCH"  # Acorn Archimedes
    AST = "AST"  # Atari ST
    BA = "BA"  # Bally Astrocade
    BB = "BB"  # BlackBerry
    BBCM = "BBCM"  # BBC Micro
    BOARD = "BOARD"  # Board Game (Physical)
    BREW = "BREW"  # Qualcomm BREW
    C64 = "C64"  # Commodore 64
    C128 = "C128"  # Commodore 128
    CARD = "CARD"  # Card Game (Physical)
    CD32 = "CD32"  # Amiga CD32
    CDI = "CDI"  # Philips CD-i
    CDTV = "CDTV"  # Commodore CDTV
    CHF = "CHF"  # Fairchild Channel F
    CP4 = "CP4"  # Commodore 116, 16, Plus/4
    CPC = "CPC"  # Amstrad CPC 464, CPC664, CPC6128
    CV = "CV"  # ColecoVision
    DC = "DC"  # Sega Dreamcast
    DOS = "DOS"  # MS-DOS
    ELEC = "ELEC"  # Acorn Electron
    EXEN = "EXEN"  # In-Fusion ExEn
    FAL = "FAL"  # Atari Falcon030
    FC = "FC"  # Nintendo Famicom
    FDS = "FDS"  # Nintendo Famicom Disk System
    FIRE = "FIRE"  # Amazon Fire OS
    FM7 = "FM7"  # Fujitsu FM-7
    FMT = "FMT"  # Fujitsu FM Towns
    GB = "GB"  # Nintendo Game Boy
    GBA = "GBA"  # Nintendo Game Boy Advance
    GBC = "GBC"  # Nintendo Game Boy Color
    GC = "GC"  # Nintendo GameCube
    GCOM = "GCOM"  # Tiger Game.com
    GEN = "GEN"  # Sega Genesis
    GG = "GG"  # Sega Game Gear
    GIZ = "GIZ"  # Tiger Gizmondo
    GW = "GW"  # Nintendo Game & Watch
    GX4 = "GX4"  # Amstrad GX4000
    IMOD = "IMOD"  # NTT DoCoMo i-mode
    INTV = "INTV"  # Intellivision, Intellivision II
    IOS = "IOS"  # Apple iOS: iPad, iPod, iPhone
    J2ME = "J2ME"  # Sun Java 2 Micro Edition
    JAG = "JAG"  # Atari Jaguar
    JCD = "JCD"  # Atari Jaguar CD
    LASR = "LASR"  # Pioneer LaserActive
    LYNX = "LYNX"  # Atari Lynx
    MART = "MART"  # Fujitsu FM Towns Marty
    MCD = "MCD"  # Sega Mega CD
    META = "META"  # Metagame
    MOD = "MOD"  # Modded Game
    MSX = "MSX"  # MSX
    MSX2 = "MSX2"  # MSX2, MSX2+, MSX TurboR
    N64 = "N64"  # Nintendo 64
    NDS = "NDS"  # Nintendo DS
    NES = "NES"  # Nintendo Entertainment System
    NG = "NG"  # SNK Neo Geo
    NGAGE = "NGAGE"  # Nokia N-GAGE
    NGCD = "NGCD"  # SNK Neo Geo CD
    NGP = "NGP"  # SNK Neo Geo Pocket
    NGPC = "NGPC"  # SNK Neo Geo Pocket Color
    ODY2 = "ODY2"  # Magnavox Odyssey 2
    OUYA = "OUYA"  # Ouya
    PALM = "PALM"  # Palm OS
    PBL = "PBL"  # Pinball
    PC = "PC"  # PC
    PC10 = "PC10"  # Nintendo PlayChoice-10
    PC88 = "PC88"  # NEC PC-8801
    PC98 = "PC98"  # NEC PC-9801
    PCB = "PCB"  # PC Boot Loader
    PCCD = "PCCD"  # NEC PC Engine CD-ROM
    PCE = "PCE"  # NEC PC Engine
    PCED = "PCED"  # NEC PC Engine Duo
    PICO = "PICO"  # Sega Pico / Kids Computer Pico
    PICO8 = "PICO8"  # PICO-8 Fantasy Console
    PPC = "PPC"  # Microsoft Pocket PC
    PS1 = "PS1"  # Sony PlayStation 1
    PS2 = "PS2"  # Sony PlayStation 2
    PS3 = "PS3"  # Sony PlayStation 3
    PS4 = "PS4"  # Sony PlayStation 4
    PS5 = "PS5"  # Sony PlayStation 5
    PSP = "PSP"  # Sony PlayStation Portable
    QL = "QL"  # Sinclair Quantum Leap
    SAM = "SAM"  # Sam Coupe
    SAT = "SAT"  # Sega Saturn
    SCD = "SCD"  # Sega CD
    SFC = "SFC"  # Nintendo Super Famicom
    SLOT = "SLOT"  # Slot Machine
    SM3 = "SM3"  # Sega Mark III
    SMD = "SMD"  # Sega Mega Drive
    SMS = "SMS"  # Sega Master System
    SNES = "SNES"  # Super Nintendo Entertainment System
    SW = "SW"  # Nintendo Switch
    SYM = "SYM"  # Symbian
    TD = "TD"  # NEC TurboDuo
    TG16 = "TG16"  # NEC TurboGrafx-16
    TGCD = "TGCD"  # NEC TurboGrafx CD-ROM
    TMO = "TMO"  # Thomson MO
    TRS = "TRS"  # Radio Shack TRS-80
    TRSC = "TRSC"  # Radio Shack TRS-80 Color Computer
    TTO = "TTO"  # Thomson TO
    VB = "VB"  # Nintendo Virtual Boy
    VECT = "VECT"  # General Consumer Electric Vectrex
    VIC = "VIC"  # Commodore VIC 20
    VITA = "VITA"  # Sony PlayStation Vita
    VR = "VR"  # Virtual Reality
    VS = "VS"  # Nintendo VS. System
    VVS = "VVS"  # V-Tech V-Smile
    VSP = "VSP"  # V-Tech V-Smile Pocket
    W16 = "W16"  # 16-bit Microsoft Windows: 1, 2, 3, 3.1, 3.11
    WCE = "WCE"  # Microsoft Windows CE
    WEB = "WEB"  # Web Browser
    WII = "WII"  # Nintendo Wii
    WIIU = "WIIU"  # Nintendo Wii U
    WMOB = "WMOB"  # Windows Mobile: 2003, 2003 SE, 5, 6, 6.1, 6.5
    WPH = "WPH"  # Windows Phone
    WS = "WS"  # Bandai WonderSwan
    WSC = "WSC"  # Bandai WonderSwan Color
    X1 = "X1"  # Sharp X1
    X360 = "X360"  # Microsoft Xbox 360
    X68 = "X68"  # Sharp X68000
    XBOX = "XBOX"  # Microsoft Xbox
    XEGS = "XEGS"  # Atari XEGS
    XONE = "XONE"  # Microsoft Xbox One
    XSX = "XSX"  # Microsoft Xbox Series X
    ZEBO = "ZEBO"  # Zeebo Zeebo
    ZOD = "ZOD"  # Tapwave Zodiac
    ZXS = "ZXS"  # Sinclair ZX Spectrum


class KeymastersKeepGoals(enum.Enum):
    KEYMASTERS_CHALLENGE = 0
    MAGIC_KEY_HEIST = 1


class KeymastersKeepItems(enum.Enum):
    ARTIFACT_OF_RESOLVE = "Artifact of Resolve"
    FILLER_KEY_BROKEN = "Broken Key"
    FILLER_KEY_CRACKED = "Cracked Key"
    FILLER_KEY_DULL = "Dull Key"
    FILLER_KEY_USELESS = "Useless Key"
    FILLER_KEY_WORN = "Worn Key"
    KEY_AMBER_INFERNO = "Amber Inferno Key"
    KEY_AMBER_STONE = "Amber Stone Key"
    KEY_ASHEN_SPARK = "Ashen Spark Key"
    KEY_AURIC_FLASH = "Auric Flash Key"
    KEY_AURORA_BEAM = "Aurora Beam Key"
    KEY_AZURE_TIDE = "Azure Tide Key"
    KEY_BRONZE_ROOT = "Bronze Root Key"
    KEY_CELESTIAL_STAR = "Celestial Star Key"
    KEY_CERULEAN_RIPPLE = "Cerulean Ripple Key"
    KEY_COBALT_SKY = "Cobalt Sky Key"
    KEY_COPPER_BLOOM = "Copper Bloom Key"
    KEY_CRIMSON_BLAZE = "Crimson Blaze Key"
    KEY_CRYSTAL_GLACIER = "Crystal Glacier Key"
    KEY_DUSKLIGHT_VEIL = "Dusklight Veil Key"
    KEY_EBONY_OAK = "Ebony Oak Key"
    KEY_ELECTRIC_STORM = "Electric Storm Key"
    KEY_EMERALD_GROVE = "Emerald Grove Key"
    KEY_FROSTBITE = "Frostbite Key"
    KEY_FROZEN_TWILIGHT = "Frozen Twilight Key"
    KEY_GLACIAL_SHARD = "Glacial Shard Key"
    KEY_GOLDEN_BIRCH = "Golden Birch Key"
    KEY_GOLDEN_FLAME = "Golden Flame Key"
    KEY_GOLDEN_ZEPHYR = "Golden Zephyr Key"
    KEY_HALO_FLAME = "Halo Flame Key"
    KEY_ICY_CASCADE = "Icy Cascade Key"
    KEY_IRONCLAD = "Ironclad Key"
    KEY_IVORY_DRIFT = "Ivory Drift Key"
    KEY_IVORY_SPROUT = "Ivory Sprout Key"
    KEY_MAHOGANY_BARK = "Mahogany Bark Key"
    KEY_MIDNIGHT_ABYSS = "Midnight Abyss Key"
    KEY_MIDNIGHT_SHADE = "Midnight Shade Key"
    KEY_OBSIDIAN_CORE = "Obsidian Core Key"
    KEY_OBSIDIAN_WRAITH = "Obsidian Wraith Key"
    KEY_ONYX_ECLIPSE = "Onyx Eclipse Key"
    KEY_PALE_GALE = "Pale Gale Key"
    KEY_PEARLESCENT_GLOW = "Pearlescent Glow Key"
    KEY_PLASMA_SURGE = "Plasma Surge Key"
    KEY_PLATINUM_FORGE = "Platinum Forge Key"
    KEY_RADIANT_DAWN = "Radiant Dawn Key"
    KEY_RUSTSTONE = "Ruststone Key"
    KEY_SAPPHIRE_SURGE = "Sapphire Surge Key"
    KEY_SCARLET_EMBER = "Scarlet Ember Key"
    KEY_SILVER_BREEZE = "Silver Breeze Key"
    KEY_SILVER_SHIELD = "Silver Shield Key"
    KEY_SNOWDRIFT = "Snowdrift Key"
    KEY_STORMCALL = "Stormcall Key"
    KEY_STORMCLOUD = "Stormcloud Key"
    KEY_VERDANT_MOSS = "Verdant Moss Key"
    KEY_VERDANT_TIMBER = "Verdant Timber Key"
    KEY_VOID_EMBER = "Void Ember Key"
    KEYMASTERS_KEEP_CHALLENGE_COMPLETE = "Completed: Keymaster's Keep Challenge"
    UNLOCK_THE_ARCANE_DOOR = "Unlock: The Arcane Door"
    UNLOCK_THE_ARCANE_PASSAGE = "Unlock: The Arcane Passage"
    UNLOCK_THE_ARCANE_THRESHOLD = "Unlock: The Arcane Threshold"
    UNLOCK_THE_CLANDESTINE_PASSAGE = "Unlock: The Clandestine Passage"
    UNLOCK_THE_CLOAKED_ENTRANCE = "Unlock: The Cloaked Entrance"
    UNLOCK_THE_CLOAKED_THRESHOLD = "Unlock: The Cloaked Threshold"
    UNLOCK_THE_CLOAKED_VAULT = "Unlock: The Cloaked Vault"
    UNLOCK_THE_CONCEALED_THRESHOLD = "Unlock: The Concealed Threshold"
    UNLOCK_THE_CONCEALED_VAULT = "Unlock: The Concealed Vault"
    UNLOCK_THE_CRYPTIC_CHAMBER = "Unlock: The Cryptic Chamber"
    UNLOCK_THE_CRYPTIC_GATEWAY = "Unlock: The Cryptic Gateway"
    UNLOCK_THE_CRYPTIC_VAULT = "Unlock: The Cryptic Vault"
    UNLOCK_THE_DISGUISED_GATEWAY = "Unlock: The Disguised Gateway"
    UNLOCK_THE_ECHOING_PASSAGE = "Unlock: The Echoing Passage"
    UNLOCK_THE_ELUSIVE_DOOR = "Unlock: The Elusive Door"
    UNLOCK_THE_ENCHANTED_GATEWAY = "Unlock: The Enchanted Gateway"
    UNLOCK_THE_ENCHANTED_PASSAGE = "Unlock: The Enchanted Passage"
    UNLOCK_THE_ENIGMATIC_PORTAL = "Unlock: The Enigmatic Portal"
    UNLOCK_THE_ENIGMATIC_THRESHOLD = "Unlock: The Enigmatic Threshold"
    UNLOCK_THE_FADED_GATEWAY = "Unlock: The Faded Gateway"
    UNLOCK_THE_FAINT_DOORWAY = "Unlock: The Faint Doorway"
    UNLOCK_THE_FAINT_PATH = "Unlock: The Faint Path"
    UNLOCK_THE_FAINT_THRESHOLD = "Unlock: The Faint Threshold"
    UNLOCK_THE_FORBIDDEN_ENTRANCE = "Unlock: The Forbidden Entrance"
    UNLOCK_THE_FORGOTTEN_DOOR = "Unlock: The Forgotten Door"
    UNLOCK_THE_FORGOTTEN_GATEWAY = "Unlock: The Forgotten Gateway"
    UNLOCK_THE_FORGOTTEN_PORTAL = "Unlock: The Forgotten Portal"
    UNLOCK_THE_FORGOTTEN_THRESHOLD = "Unlock: The Forgotten Threshold"
    UNLOCK_THE_GHOSTED_PASSAGEWAY = "Unlock: The Ghosted Passageway"
    UNLOCK_THE_GHOSTLY_PASSAGE = "Unlock: The Ghostly Passage"
    UNLOCK_THE_HIDDEN_ARCHWAY = "Unlock: The Hidden Archway"
    UNLOCK_THE_HIDDEN_CHAMBER = "Unlock: The Hidden Chamber"
    UNLOCK_THE_HIDDEN_DOORWAY = "Unlock: The Hidden Doorway"
    UNLOCK_THE_HIDDEN_ENTRANCE = "Unlock: The Hidden Entrance"
    UNLOCK_THE_HIDDEN_KEYHOLE = "Unlock: The Hidden Keyhole"
    UNLOCK_THE_HIDDEN_PASSAGEWAY = "Unlock: The Hidden Passageway"
    UNLOCK_THE_HIDDEN_PATH = "Unlock: The Hidden Path"
    UNLOCK_THE_HIDDEN_REACH = "Unlock: The Hidden Reach"
    UNLOCK_THE_HIDDEN_VAULT = "Unlock: The Hidden Vault"
    UNLOCK_THE_INCONSPICUOUS_DOOR = "Unlock: The Inconspicuous Door"
    UNLOCK_THE_INVISIBLE_DOORWAY = "Unlock: The Invisible Doorway"
    UNLOCK_THE_KEYMASTERS_CHALLENGE_CHAMBER = "Unlock: The Keymaster's Challenge Chamber"
    UNLOCK_THE_LOCKED_DOORWAY = "Unlock: The Locked Doorway"
    UNLOCK_THE_LOCKED_GATEWAY = "Unlock: The Locked Gateway"
    UNLOCK_THE_LOST_ARCHWAY = "Unlock: The Lost Archway"
    UNLOCK_THE_LOST_PORTAL = "Unlock: The Lost Portal"
    UNLOCK_THE_LOST_THRESHOLD = "Unlock: The Lost Threshold"
    UNLOCK_THE_MYSTERIOUS_ARCH = "Unlock: The Mysterious Arch"
    UNLOCK_THE_MYSTERIOUS_DOORWAY = "Unlock: The Mysterious Doorway"
    UNLOCK_THE_MYSTERIOUS_PASSAGE = "Unlock: The Mysterious Passage"
    UNLOCK_THE_MYSTERIOUS_VAULT = "Unlock: The Mysterious Vault"
    UNLOCK_THE_MYSTICAL_PASSAGE = "Unlock: The Mystical Passage"
    UNLOCK_THE_OBSCURED_ARCH = "Unlock: The Obscured Arch"
    UNLOCK_THE_OBSCURED_DOORWAY = "Unlock: The Obscured Doorway"
    UNLOCK_THE_OBSCURED_PORTAL = "Unlock: The Obscured Portal"
    UNLOCK_THE_OBSCURED_VAULT = "Unlock: The Obscured Vault"
    UNLOCK_THE_OBSCURE_PASSAGE = "Unlock: The Obscure Passage"
    UNLOCK_THE_PHANTOM_PASSAGE = "Unlock: The Phantom Passage"
    UNLOCK_THE_PHANTOM_VAULT = "Unlock: The Phantom Vault"
    UNLOCK_THE_QUIET_ARCHWAY = "Unlock: The Quiet Archway"
    UNLOCK_THE_QUIET_THRESHOLD = "Unlock: The Quiet Threshold"
    UNLOCK_THE_SEALED_CHAMBER = "Unlock: The Sealed Chamber"
    UNLOCK_THE_SEALED_GATEWAY = "Unlock: The Sealed Gateway"
    UNLOCK_THE_SEALED_THRESHOLD = "Unlock: The Sealed Threshold"
    UNLOCK_THE_SECRETED_DOOR = "Unlock: The Secreted Door"
    UNLOCK_THE_SECRETIVE_DOOR = "Unlock: The Secretive Door"
    UNLOCK_THE_SECRET_ARCHWAY = "Unlock: The Secret Archway"
    UNLOCK_THE_SECRET_PASSAGEWAY = "Unlock: The Secret Passageway"
    UNLOCK_THE_SECRET_THRESHOLD = "Unlock: The Secret Threshold"
    UNLOCK_THE_SECRET_VAULT = "Unlock: The Secret Vault"
    UNLOCK_THE_SHADOWED_PORTAL = "Unlock: The Shadowed Portal"
    UNLOCK_THE_SHADOWED_THRESHOLD = "Unlock: The Shadowed Threshold"
    UNLOCK_THE_SHADOWY_PASSAGE = "Unlock: The Shadowy Passage"
    UNLOCK_THE_SHIMMERING_PASSAGE = "Unlock: The Shimmering Passage"
    UNLOCK_THE_SHROUDED_GATEWAY = "Unlock: The Shrouded Gateway"
    UNLOCK_THE_SHROUDED_PORTAL = "Unlock: The Shrouded Portal"
    UNLOCK_THE_SILENT_ARCHWAY = "Unlock: The Silent Archway"
    UNLOCK_THE_SILENT_PASSAGE = "Unlock: The Silent Passage"
    UNLOCK_THE_SILENT_THRESHOLD = "Unlock: The Silent Threshold"
    UNLOCK_THE_SILENT_VAULT = "Unlock: The Silent Vault"
    UNLOCK_THE_UNFATHOMABLE_DOOR = "Unlock: The Unfathomable Door"
    UNLOCK_THE_UNKNOWN_ARCH = "Unlock: The Unknown Arch"
    UNLOCK_THE_UNKNOWN_GATEWAY = "Unlock: The Unknown Gateway"
    UNLOCK_THE_UNMARKED_PASSAGE = "Unlock: The Unmarked Passage"
    UNLOCK_THE_UNMARKED_VAULT = "Unlock: The Unmarked Vault"
    UNLOCK_THE_UNRAVELED_DOOR = "Unlock: The Unraveled Door"
    UNLOCK_THE_UNSEEN_ARCHWAY = "Unlock: The Unseen Archway"
    UNLOCK_THE_UNSEEN_DOOR = "Unlock: The Unseen Door"
    UNLOCK_THE_UNSEEN_PASSAGE = "Unlock: The Unseen Passage"
    UNLOCK_THE_UNSEEN_PORTAL = "Unlock: The Unseen Portal"
    UNLOCK_THE_UNSPOKEN_GATE = "Unlock: The Unspoken Gate"
    UNLOCK_THE_UNTOLD_GATEWAY = "Unlock: The Untold Gateway"
    UNLOCK_THE_UNTRACEABLE_PATH = "Unlock: The Untraceable Path"
    UNLOCK_THE_VANISHING_ARCHWAY = "Unlock: The Vanishing Archway"
    UNLOCK_THE_VANISHING_DOOR = "Unlock: The Vanishing Door"
    UNLOCK_THE_VAULT_OF_WHISPERS = "Unlock: The Vault of Whispers"
    UNLOCK_THE_VEILED_PASSAGE = "Unlock: The Veiled Passage"
    UNLOCK_THE_VEILED_PATH = "Unlock: The Veiled Path"
    UNLOCK_THE_WHISPERED_PORTAL = "Unlock: The Whispered Portal"
    UNLOCK_THE_WHISPERED_THRESHOLD = "Unlock: The Whispered Threshold"
    UNLOCK_THE_WHISPERING_DOOR = "Unlock: The Whispering Door"


class KeymastersKeepLocations(enum.Enum):
    THE_ARCANE_DOOR_TRIAL = "Beyond the Arcane Door: TRIAL_NAME"
    THE_ARCANE_DOOR_UNLOCK = "Unlock: The Arcane Door"
    THE_ARCANE_PASSAGE_TRIAL = "Along the Arcane Passage: TRIAL_NAME"
    THE_ARCANE_PASSAGE_UNLOCK = "Unlock: The Arcane Passage"
    THE_ARCANE_THRESHOLD_TRIAL = "Beyond the Arcane Threshold: TRIAL_NAME"
    THE_ARCANE_THRESHOLD_UNLOCK = "Unlock: The Arcane Threshold"
    THE_CLANDESTINE_PASSAGE_TRIAL = "Into the Clandestine Passage: TRIAL_NAME"
    THE_CLANDESTINE_PASSAGE_UNLOCK = "Unlock: The Clandestine Passage"
    THE_CLOAKED_ENTRANCE_TRIAL = "Beyond the Cloaked Entrance: TRIAL_NAME"
    THE_CLOAKED_ENTRANCE_UNLOCK = "Unlock: The Cloaked Entrance"
    THE_CLOAKED_THRESHOLD_TRIAL = "Beyond the Cloaked Threshold: TRIAL_NAME"
    THE_CLOAKED_THRESHOLD_UNLOCK = "Unlock: The Cloaked Threshold"
    THE_CLOAKED_VAULT_TRIAL = "Inside the Cloaked Vault: TRIAL_NAME"
    THE_CLOAKED_VAULT_UNLOCK = "Unlock: The Cloaked Vault"
    THE_CONCEALED_THRESHOLD_TRIAL = "Beyond the Concealed Threshold: TRIAL_NAME"
    THE_CONCEALED_THRESHOLD_UNLOCK = "Unlock: The Concealed Threshold"
    THE_CONCEALED_VAULT_TRIAL = "Inside the Concealed Vault: TRIAL_NAME"
    THE_CONCEALED_VAULT_UNLOCK = "Unlock: The Concealed Vault"
    THE_CRYPTIC_CHAMBER_TRIAL = "Inside the Cryptic Chamber: TRIAL_NAME"
    THE_CRYPTIC_CHAMBER_UNLOCK = "Unlock: The Cryptic Chamber"
    THE_CRYPTIC_GATEWAY_TRIAL = "Beyond the Cryptic Gateway: TRIAL_NAME"
    THE_CRYPTIC_GATEWAY_UNLOCK = "Unlock: The Cryptic Gateway"
    THE_CRYPTIC_VAULT_TRIAL = "Inside the Cryptic Vault: TRIAL_NAME"
    THE_CRYPTIC_VAULT_UNLOCK = "Unlock: The Cryptic Vault"
    THE_DISGUISED_GATEWAY_TRIAL = "Beyond the Disguised Gateway: TRIAL_NAME"
    THE_DISGUISED_GATEWAY_UNLOCK = "Unlock: The Disguised Gateway"
    THE_ECHOING_PASSAGE_TRIAL = "Along the Echoing Passage: TRIAL_NAME"
    THE_ECHOING_PASSAGE_UNLOCK = "Unlock: The Echoing Passage"
    THE_ELUSIVE_DOOR_TRIAL = "Beyond the Elusive Door: TRIAL_NAME"
    THE_ELUSIVE_DOOR_UNLOCK = "Unlock: The Elusive Door"
    THE_ENCHANTED_GATEWAY_TRIAL = "Beyond the Enchanted Gateway: TRIAL_NAME"
    THE_ENCHANTED_GATEWAY_UNLOCK = "Unlock: The Enchanted Gateway"
    THE_ENCHANTED_PASSAGE_TRIAL = "Along the Enchanted Passage: TRIAL_NAME"
    THE_ENCHANTED_PASSAGE_UNLOCK = "Unlock: The Enchanted Passage"
    THE_ENIGMATIC_PORTAL_TRIAL = "Beyond the Enigmatic Portal: TRIAL_NAME"
    THE_ENIGMATIC_PORTAL_UNLOCK = "Unlock: The Enigmatic Portal"
    THE_ENIGMATIC_THRESHOLD_TRIAL = "Beyond the Enigmatic Threshold: TRIAL_NAME"
    THE_ENIGMATIC_THRESHOLD_UNLOCK = "Unlock: The Enigmatic Threshold"
    THE_FADED_GATEWAY_TRIAL = "Beyond the Faded Gateway: TRIAL_NAME"
    THE_FADED_GATEWAY_UNLOCK = "Unlock: The Faded Gateway"
    THE_FAINT_DOORWAY_TRIAL = "Beyond the Faint Doorway: TRIAL_NAME"
    THE_FAINT_DOORWAY_UNLOCK = "Unlock: The Faint Doorway"
    THE_FAINT_PATH_TRIAL = "Along the Faint Path: TRIAL_NAME"
    THE_FAINT_PATH_UNLOCK = "Unlock: The Faint Path"
    THE_FAINT_THRESHOLD_TRIAL = "Beyond the Faint Threshold: TRIAL_NAME"
    THE_FAINT_THRESHOLD_UNLOCK = "Unlock: The Faint Threshold"
    THE_FORBIDDEN_ENTRANCE_TRIAL = "Beyond the Forbidden Entrance: TRIAL_NAME"
    THE_FORBIDDEN_ENTRANCE_UNLOCK = "Unlock: The Forbidden Entrance"
    THE_FORGOTTEN_DOOR_TRIAL = "Beyond the Forgotten Door: TRIAL_NAME"
    THE_FORGOTTEN_DOOR_UNLOCK = "Unlock: The Forgotten Door"
    THE_FORGOTTEN_GATEWAY_TRIAL = "Beyond the Forgotten Gateway: TRIAL_NAME"
    THE_FORGOTTEN_GATEWAY_UNLOCK = "Unlock: The Forgotten Gateway"
    THE_FORGOTTEN_PORTAL_TRIAL = "Beyond the Forgotten Portal: TRIAL_NAME"
    THE_FORGOTTEN_PORTAL_UNLOCK = "Unlock: The Forgotten Portal"
    THE_FORGOTTEN_THRESHOLD_TRIAL = "Beyond the Forgotten Threshold: TRIAL_NAME"
    THE_FORGOTTEN_THRESHOLD_UNLOCK = "Unlock: The Forgotten Threshold"
    THE_GHOSTED_PASSAGEWAY_TRIAL = "Along the Ghosted Passageway: TRIAL_NAME"
    THE_GHOSTED_PASSAGEWAY_UNLOCK = "Unlock: The Ghosted Passageway"
    THE_GHOSTLY_PASSAGE_TRIAL = "Along the Ghostly Passage: TRIAL_NAME"
    THE_GHOSTLY_PASSAGE_UNLOCK = "Unlock: The Ghostly Passage"
    THE_HIDDEN_ARCHWAY_TRIAL = "Beyond the Hidden Archway: TRIAL_NAME"
    THE_HIDDEN_ARCHWAY_UNLOCK = "Unlock: The Hidden Archway"
    THE_HIDDEN_CHAMBER_TRIAL = "Inside the Hidden Chamber: TRIAL_NAME"
    THE_HIDDEN_CHAMBER_UNLOCK = "Unlock: The Hidden Chamber"
    THE_HIDDEN_DOORWAY_TRIAL = "Beyond the Hidden Doorway: TRIAL_NAME"
    THE_HIDDEN_DOORWAY_UNLOCK = "Unlock: The Hidden Doorway"
    THE_HIDDEN_ENTRANCE_TRIAL = "Beyond the Hidden Entrance: TRIAL_NAME"
    THE_HIDDEN_ENTRANCE_UNLOCK = "Unlock: The Hidden Entrance"
    THE_HIDDEN_KEYHOLE_TRIAL = "Beyond the Hidden Keyhole: TRIAL_NAME"
    THE_HIDDEN_KEYHOLE_UNLOCK = "Unlock: The Hidden Keyhole"
    THE_HIDDEN_PASSAGEWAY_TRIAL = "Along the Hidden Passageway: TRIAL_NAME"
    THE_HIDDEN_PASSAGEWAY_UNLOCK = "Unlock: The Hidden Passageway"
    THE_HIDDEN_PATH_TRIAL = "Along the Hidden Path: TRIAL_NAME"
    THE_HIDDEN_PATH_UNLOCK = "Unlock: The Hidden Path"
    THE_HIDDEN_REACH_TRIAL = "Inside the Hidden Reach: TRIAL_NAME"
    THE_HIDDEN_REACH_UNLOCK = "Unlock: The Hidden Reach"
    THE_HIDDEN_VAULT_TRIAL = "Inside the Hidden Vault: TRIAL_NAME"
    THE_HIDDEN_VAULT_UNLOCK = "Unlock: The Hidden Vault"
    THE_INCONSPICUOUS_DOOR_TRIAL = "Beyond the Inconspicuous Door: TRIAL_NAME"
    THE_INCONSPICUOUS_DOOR_UNLOCK = "Unlock: The Inconspicuous Door"
    THE_INVISIBLE_DOORWAY_TRIAL = "Beyond the Invisible Doorway: TRIAL_NAME"
    THE_INVISIBLE_DOORWAY_UNLOCK = "Unlock: The Invisible Doorway"
    THE_KEYMASTERS_CHALLENGE_CHAMBER_UNLOCK = "Unlock: The Keymaster's Challenge Chamber"
    THE_KEYMASTERS_CHALLENGE_CHAMBER_VICTORY = "Inside the Keymaster's Challenge Chamber: Ultimate Challenge"
    THE_LOCKED_DOORWAY_TRIAL = "Beyond the Locked Doorway: TRIAL_NAME"
    THE_LOCKED_DOORWAY_UNLOCK = "Unlock: The Locked Doorway"
    THE_LOCKED_GATEWAY_TRIAL = "Beyond the Locked Gateway: TRIAL_NAME"
    THE_LOCKED_GATEWAY_UNLOCK = "Unlock: The Locked Gateway"
    THE_LOST_ARCHWAY_TRIAL = "Beyond the Lost Archway: TRIAL_NAME"
    THE_LOST_ARCHWAY_UNLOCK = "Unlock: The Lost Archway"
    THE_LOST_PORTAL_TRIAL = "Beyond the Lost Portal: TRIAL_NAME"
    THE_LOST_PORTAL_UNLOCK = "Unlock: The Lost Portal"
    THE_LOST_THRESHOLD_TRIAL = "Beyond the Lost Threshold: TRIAL_NAME"
    THE_LOST_THRESHOLD_UNLOCK = "Unlock: The Lost Threshold"
    THE_MYSTERIOUS_ARCH_TRIAL = "Beyond the Mysterious Arch: TRIAL_NAME"
    THE_MYSTERIOUS_ARCH_UNLOCK = "Unlock: The Mysterious Arch"
    THE_MYSTERIOUS_DOORWAY_TRIAL = "Beyond the Mysterious Doorway: TRIAL_NAME"
    THE_MYSTERIOUS_DOORWAY_UNLOCK = "Unlock: The Mysterious Doorway"
    THE_MYSTERIOUS_PASSAGE_TRIAL = "Along the Mysterious Passage: TRIAL_NAME"
    THE_MYSTERIOUS_PASSAGE_UNLOCK = "Unlock: The Mysterious Passage"
    THE_MYSTERIOUS_VAULT_TRIAL = "Inside the Mysterious Vault: TRIAL_NAME"
    THE_MYSTERIOUS_VAULT_UNLOCK = "Unlock: The Mysterious Vault"
    THE_MYSTICAL_PASSAGE_TRIAL = "Along the Mystical Passage: TRIAL_NAME"
    THE_MYSTICAL_PASSAGE_UNLOCK = "Unlock: The Mystical Passage"
    THE_OBSCURED_ARCH_TRIAL = "Beyond the Obscured Arch: TRIAL_NAME"
    THE_OBSCURED_ARCH_UNLOCK = "Unlock: The Obscured Arch"
    THE_OBSCURED_DOORWAY_TRIAL = "Beyond the Obscured Doorway: TRIAL_NAME"
    THE_OBSCURED_DOORWAY_UNLOCK = "Unlock: The Obscured Doorway"
    THE_OBSCURED_PORTAL_TRIAL = "Beyond the Obscured Portal: TRIAL_NAME"
    THE_OBSCURED_PORTAL_UNLOCK = "Unlock: The Obscured Portal"
    THE_OBSCURED_VAULT_TRIAL = "Inside the Obscured Vault: TRIAL_NAME"
    THE_OBSCURED_VAULT_UNLOCK = "Unlock: The Obscured Vault"
    THE_OBSCURE_PASSAGE_TRIAL = "Along the Obscure Passage: TRIAL_NAME"
    THE_OBSCURE_PASSAGE_UNLOCK = "Unlock: The Obscure Passage"
    THE_PHANTOM_PASSAGE_TRIAL = "Along the Phantom Passage: TRIAL_NAME"
    THE_PHANTOM_PASSAGE_UNLOCK = "Unlock: The Phantom Passage"
    THE_PHANTOM_VAULT_TRIAL = "Inside the Phantom Vault: TRIAL_NAME"
    THE_PHANTOM_VAULT_UNLOCK = "Unlock: The Phantom Vault"
    THE_QUIET_ARCHWAY_TRIAL = "Beyond the Quiet Archway: TRIAL_NAME"
    THE_QUIET_ARCHWAY_UNLOCK = "Unlock: The Quiet Archway"
    THE_QUIET_THRESHOLD_TRIAL = "Beyond the Quiet Threshold: TRIAL_NAME"
    THE_QUIET_THRESHOLD_UNLOCK = "Unlock: The Quiet Threshold"
    THE_SEALED_CHAMBER_TRIAL = "Inside the Sealed Chamber: TRIAL_NAME"
    THE_SEALED_CHAMBER_UNLOCK = "Unlock: The Sealed Chamber"
    THE_SEALED_GATEWAY_TRIAL = "Beyond the Sealed Gateway: TRIAL_NAME"
    THE_SEALED_GATEWAY_UNLOCK = "Unlock: The Sealed Gateway"
    THE_SEALED_THRESHOLD_TRIAL = "Beyond the Sealed Threshold: TRIAL_NAME"
    THE_SEALED_THRESHOLD_UNLOCK = "Unlock: The Sealed Threshold"
    THE_SECRETED_DOOR_TRIAL = "Beyond the Secreted Door: TRIAL_NAME"
    THE_SECRETED_DOOR_UNLOCK = "Unlock: The Secreted Door"
    THE_SECRETIVE_DOOR_TRIAL = "Beyond the Secretive Door: TRIAL_NAME"
    THE_SECRETIVE_DOOR_UNLOCK = "Unlock: The Secretive Door"
    THE_SECRET_ARCHWAY_TRIAL = "Beyond the Secret Archway: TRIAL_NAME"
    THE_SECRET_ARCHWAY_UNLOCK = "Unlock: The Secret Archway"
    THE_SECRET_PASSAGEWAY_TRIAL = "Along the Secret Passageway: TRIAL_NAME"
    THE_SECRET_PASSAGEWAY_UNLOCK = "Unlock: The Secret Passageway"
    THE_SECRET_THRESHOLD_TRIAL = "Beyond the Secret Threshold: TRIAL_NAME"
    THE_SECRET_THRESHOLD_UNLOCK = "Unlock: The Secret Threshold"
    THE_SECRET_VAULT_TRIAL = "Inside the Secret Vault: TRIAL_NAME"
    THE_SECRET_VAULT_UNLOCK = "Unlock: The Secret Vault"
    THE_SHADOWED_PORTAL_TRIAL = "Beyond the Shadowed Portal: TRIAL_NAME"
    THE_SHADOWED_PORTAL_UNLOCK = "Unlock: The Shadowed Portal"
    THE_SHADOWED_THRESHOLD_TRIAL = "Beyond the Shadowed Threshold: TRIAL_NAME"
    THE_SHADOWED_THRESHOLD_UNLOCK = "Unlock: The Shadowed Threshold"
    THE_SHADOWY_PASSAGE_TRIAL = "Along the Shadowy Passage: TRIAL_NAME"
    THE_SHADOWY_PASSAGE_UNLOCK = "Unlock: The Shadowy Passage"
    THE_SHIMMERING_PASSAGE_TRIAL = "Along the Shimmering Passage: TRIAL_NAME"
    THE_SHIMMERING_PASSAGE_UNLOCK = "Unlock: The Shimmering Passage"
    THE_SHROUDED_GATEWAY_TRIAL = "Beyond the Shrouded Gateway: TRIAL_NAME"
    THE_SHROUDED_GATEWAY_UNLOCK = "Unlock: The Shrouded Gateway"
    THE_SHROUDED_PORTAL_TRIAL = "Beyond the Shrouded Portal: TRIAL_NAME"
    THE_SHROUDED_PORTAL_UNLOCK = "Unlock: The Shrouded Portal"
    THE_SILENT_ARCHWAY_TRIAL = "Beyond the Silent Archway: TRIAL_NAME"
    THE_SILENT_ARCHWAY_UNLOCK = "Unlock: The Silent Archway"
    THE_SILENT_PASSAGE_TRIAL = "Along the Silent Passage: TRIAL_NAME"
    THE_SILENT_PASSAGE_UNLOCK = "Unlock: The Silent Passage"
    THE_SILENT_THRESHOLD_TRIAL = "Beyond the Silent Threshold: TRIAL_NAME"
    THE_SILENT_THRESHOLD_UNLOCK = "Unlock: The Silent Threshold"
    THE_SILENT_VAULT_TRIAL = "Inside the Silent Vault: TRIAL_NAME"
    THE_SILENT_VAULT_UNLOCK = "Unlock: The Silent Vault"
    THE_UNFATHOMABLE_DOOR_TRIAL = "Beyond the Unfathomable Door: TRIAL_NAME"
    THE_UNFATHOMABLE_DOOR_UNLOCK = "Unlock: The Unfathomable Door"
    THE_UNKNOWN_ARCH_TRIAL = "Beyond the Unknown Arch: TRIAL_NAME"
    THE_UNKNOWN_ARCH_UNLOCK = "Unlock: The Unknown Arch"
    THE_UNKNOWN_GATEWAY_TRIAL = "Beyond the Unknown Gateway: TRIAL_NAME"
    THE_UNKNOWN_GATEWAY_UNLOCK = "Unlock: The Unknown Gateway"
    THE_UNMARKED_PASSAGE_TRIAL = "Along the Unmarked Passage: TRIAL_NAME"
    THE_UNMARKED_PASSAGE_UNLOCK = "Unlock: The Unmarked Passage"
    THE_UNMARKED_VAULT_TRIAL = "Inside the Unmarked Vault: TRIAL_NAME"
    THE_UNMARKED_VAULT_UNLOCK = "Unlock: The Unmarked Vault"
    THE_UNRAVELED_DOOR_TRIAL = "Beyond the Unraveled Door: TRIAL_NAME"
    THE_UNRAVELED_DOOR_UNLOCK = "Unlock: The Unraveled Door"
    THE_UNSEEN_ARCHWAY_TRIAL = "Beyond the Unseen Archway: TRIAL_NAME"
    THE_UNSEEN_ARCHWAY_UNLOCK = "Unlock: The Unseen Archway"
    THE_UNSEEN_DOOR_TRIAL = "Beyond the Unseen Door: TRIAL_NAME"
    THE_UNSEEN_DOOR_UNLOCK = "Unlock: The Unseen Door"
    THE_UNSEEN_PASSAGE_TRIAL = "Along the Unseen Passage: TRIAL_NAME"
    THE_UNSEEN_PASSAGE_UNLOCK = "Unlock: The Unseen Passage"
    THE_UNSEEN_PORTAL_TRIAL = "Beyond the Unseen Portal: TRIAL_NAME"
    THE_UNSEEN_PORTAL_UNLOCK = "Unlock: The Unseen Portal"
    THE_UNSPOKEN_GATE_TRIAL = "Beyond the Unspoken Gate: TRIAL_NAME"
    THE_UNSPOKEN_GATE_UNLOCK = "Unlock: The Unspoken Gate"
    THE_UNTOLD_GATEWAY_TRIAL = "Beyond the Untold Gateway: TRIAL_NAME"
    THE_UNTOLD_GATEWAY_UNLOCK = "Unlock: The Untold Gateway"
    THE_UNTRACEABLE_PATH_TRIAL = "Along the Untraceable Path: TRIAL_NAME"
    THE_UNTRACEABLE_PATH_UNLOCK = "Unlock: The Untraceable Path"
    THE_VANISHING_ARCHWAY_TRIAL = "Beyond the Vanishing Archway: TRIAL_NAME"
    THE_VANISHING_ARCHWAY_UNLOCK = "Unlock: The Vanishing Archway"
    THE_VANISHING_DOOR_TRIAL = "Beyond the Vanishing Door: TRIAL_NAME"
    THE_VANISHING_DOOR_UNLOCK = "Unlock: The Vanishing Door"
    THE_VAULT_OF_WHISPERS_TRIAL = "Inside the Vault of Whispers: TRIAL_NAME"
    THE_VAULT_OF_WHISPERS_UNLOCK = "Unlock: The Vault of Whispers"
    THE_VEILED_PASSAGE_TRIAL = "Along the Veiled Passage: TRIAL_NAME"
    THE_VEILED_PASSAGE_UNLOCK = "Unlock: The Veiled Passage"
    THE_VEILED_PATH_TRIAL = "Along the Veiled Path: TRIAL_NAME"
    THE_VEILED_PATH_UNLOCK = "Unlock: The Veiled Path"
    THE_WHISPERED_PORTAL_TRIAL = "Beyond the Whispered Portal: TRIAL_NAME"
    THE_WHISPERED_PORTAL_UNLOCK = "Unlock: The Whispered Portal"
    THE_WHISPERED_THRESHOLD_TRIAL = "Beyond the Whispered Threshold: TRIAL_NAME"
    THE_WHISPERED_THRESHOLD_UNLOCK = "Unlock: The Whispered Threshold"
    THE_WHISPERING_DOOR_TRIAL = "Beyond the Whispering Door: TRIAL_NAME"
    THE_WHISPERING_DOOR_UNLOCK = "Unlock: The Whispering Door"


class KeymastersKeepRegions(enum.Enum):
    ENDGAME = "Endgame"
    KEYMASTERS_KEEP = "Keymaster's Keep"
    MENU = "Menu"
    THE_ARCANE_DOOR = "The Arcane Door"
    THE_ARCANE_PASSAGE = "The Arcane Passage"
    THE_ARCANE_THRESHOLD = "The Arcane Threshold"
    THE_CLANDESTINE_PASSAGE = "The Clandestine Passage"
    THE_CLOAKED_ENTRANCE = "The Cloaked Entrance"
    THE_CLOAKED_THRESHOLD = "The Cloaked Threshold"
    THE_CLOAKED_VAULT = "The Cloaked Vault"
    THE_CONCEALED_THRESHOLD = "The Concealed Threshold"
    THE_CONCEALED_VAULT = "The Concealed Vault"
    THE_CRYPTIC_CHAMBER = "The Cryptic Chamber"
    THE_CRYPTIC_GATEWAY = "The Cryptic Gateway"
    THE_CRYPTIC_VAULT = "The Cryptic Vault"
    THE_DISGUISED_GATEWAY = "The Disguised Gateway"
    THE_ECHOING_PASSAGE = "The Echoing Passage"
    THE_ELUSIVE_DOOR = "The Elusive Door"
    THE_ENCHANTED_GATEWAY = "The Enchanted Gateway"
    THE_ENCHANTED_PASSAGE = "The Enchanted Passage"
    THE_ENIGMATIC_PORTAL = "The Enigmatic Portal"
    THE_ENIGMATIC_THRESHOLD = "The Enigmatic Threshold"
    THE_FADED_GATEWAY = "The Faded Gateway"
    THE_FAINT_DOORWAY = "The Faint Doorway"
    THE_FAINT_PATH = "The Faint Path"
    THE_FAINT_THRESHOLD = "The Faint Threshold"
    THE_FORBIDDEN_ENTRANCE = "The Forbidden Entrance"
    THE_FORGOTTEN_DOOR = "The Forgotten Door"
    THE_FORGOTTEN_GATEWAY = "The Forgotten Gateway"
    THE_FORGOTTEN_PORTAL = "The Forgotten Portal"
    THE_FORGOTTEN_THRESHOLD = "The Forgotten Threshold"
    THE_GHOSTED_PASSAGEWAY = "The Ghosted Passageway"
    THE_GHOSTLY_PASSAGE = "The Ghostly Passage"
    THE_HIDDEN_ARCHWAY = "The Hidden Archway"
    THE_HIDDEN_CHAMBER = "The Hidden Chamber"
    THE_HIDDEN_DOORWAY = "The Hidden Doorway"
    THE_HIDDEN_ENTRANCE = "The Hidden Entrance"
    THE_HIDDEN_KEYHOLE = "The Hidden Keyhole"
    THE_HIDDEN_PASSAGEWAY = "The Hidden Passageway"
    THE_HIDDEN_PATH = "The Hidden Path"
    THE_HIDDEN_REACH = "The Hidden Reach"
    THE_HIDDEN_VAULT = "The Hidden Vault"
    THE_INCONSPICUOUS_DOOR = "The Inconspicuous Door"
    THE_INVISIBLE_DOORWAY = "The Invisible Doorway"
    THE_KEYMASTERS_CHALLENGE_CHAMBER = "The Keymaster's Challenge Chamber"
    THE_LOCKED_DOORWAY = "The Locked Doorway"
    THE_LOCKED_GATEWAY = "The Locked Gateway"
    THE_LOST_ARCHWAY = "The Lost Archway"
    THE_LOST_PORTAL = "The Lost Portal"
    THE_LOST_THRESHOLD = "The Lost Threshold"
    THE_MYSTERIOUS_ARCH = "The Mysterious Arch"
    THE_MYSTERIOUS_DOORWAY = "The Mysterious Doorway"
    THE_MYSTERIOUS_PASSAGE = "The Mysterious Passage"
    THE_MYSTERIOUS_VAULT = "The Mysterious Vault"
    THE_MYSTICAL_PASSAGE = "The Mystical Passage"
    THE_OBSCURED_ARCH = "The Obscured Arch"
    THE_OBSCURED_DOORWAY = "The Obscured Doorway"
    THE_OBSCURED_PORTAL = "The Obscured Portal"
    THE_OBSCURED_VAULT = "The Obscured Vault"
    THE_OBSCURE_PASSAGE = "The Obscure Passage"
    THE_PHANTOM_PASSAGE = "The Phantom Passage"
    THE_PHANTOM_VAULT = "The Phantom Vault"
    THE_QUIET_ARCHWAY = "The Quiet Archway"
    THE_QUIET_THRESHOLD = "The Quiet Threshold"
    THE_SEALED_CHAMBER = "The Sealed Chamber"
    THE_SEALED_GATEWAY = "The Sealed Gateway"
    THE_SEALED_THRESHOLD = "The Sealed Threshold"
    THE_SECRETED_DOOR = "The Secreted Door"
    THE_SECRETIVE_DOOR = "The Secretive Door"
    THE_SECRET_ARCHWAY = "The Secret Archway"
    THE_SECRET_PASSAGEWAY = "The Secret Passageway"
    THE_SECRET_THRESHOLD = "The Secret Threshold"
    THE_SECRET_VAULT = "The Secret Vault"
    THE_SHADOWED_PORTAL = "The Shadowed Portal"
    THE_SHADOWED_THRESHOLD = "The Shadowed Threshold"
    THE_SHADOWY_PASSAGE = "The Shadowy Passage"
    THE_SHIMMERING_PASSAGE = "The Shimmering Passage"
    THE_SHROUDED_GATEWAY = "The Shrouded Gateway"
    THE_SHROUDED_PORTAL = "The Shrouded Portal"
    THE_SILENT_ARCHWAY = "The Silent Archway"
    THE_SILENT_PASSAGE = "The Silent Passage"
    THE_SILENT_THRESHOLD = "The Silent Threshold"
    THE_SILENT_VAULT = "The Silent Vault"
    THE_UNFATHOMABLE_DOOR = "The Unfathomable Door"
    THE_UNKNOWN_ARCH = "The Unknown Arch"
    THE_UNKNOWN_GATEWAY = "The Unknown Gateway"
    THE_UNMARKED_PASSAGE = "The Unmarked Passage"
    THE_UNMARKED_VAULT = "The Unmarked Vault"
    THE_UNRAVELED_DOOR = "The Unraveled Door"
    THE_UNSEEN_ARCHWAY = "The Unseen Archway"
    THE_UNSEEN_DOOR = "The Unseen Door"
    THE_UNSEEN_PASSAGE = "The Unseen Passage"
    THE_UNSEEN_PORTAL = "The Unseen Portal"
    THE_UNSPOKEN_GATE = "The Unspoken Gate"
    THE_UNTOLD_GATEWAY = "The Untold Gateway"
    THE_UNTRACEABLE_PATH = "The Untraceable Path"
    THE_VANISHING_ARCHWAY = "The Vanishing Archway"
    THE_VANISHING_DOOR = "The Vanishing Door"
    THE_VAULT_OF_WHISPERS = "The Vault of Whispers"
    THE_VEILED_PASSAGE = "The Veiled Passage"
    THE_VEILED_PATH = "The Veiled Path"
    THE_WHISPERED_PORTAL = "The Whispered Portal"
    THE_WHISPERED_THRESHOLD = "The Whispered Threshold"
    THE_WHISPERING_DOOR = "The Whispering Door"


class KeymastersKeepTags(enum.Enum):
    DOOR_UNLOCKS = "Door Unlocks"
    FILLER = "Filler"
    GOAL = "Goal"
    KEYS = "Keys"
    TRIALS = "Trials"
    TRIALS_THE_ARCANE_DOOR = "Trials: The Arcane Door"
    TRIALS_THE_ARCANE_PASSAGE = "Trials: The Arcane Passage"
    TRIALS_THE_ARCANE_THRESHOLD = "Trials: The Arcane Threshold"
    TRIALS_THE_CLANDESTINE_PASSAGE = "Trials: The Clandestine Passage"
    TRIALS_THE_CLOAKED_ENTRANCE = "Trials: The Cloaked Entrance"
    TRIALS_THE_CLOAKED_THRESHOLD = "Trials: The Cloaked Threshold"
    TRIALS_THE_CLOAKED_VAULT = "Trials: The Cloaked Vault"
    TRIALS_THE_CONCEALED_THRESHOLD = "Trials: The Concealed Threshold"
    TRIALS_THE_CONCEALED_VAULT = "Trials: The Concealed Vault"
    TRIALS_THE_CRYPTIC_CHAMBER = "Trials: The Cryptic Chamber"
    TRIALS_THE_CRYPTIC_GATEWAY = "Trials: The Cryptic Gateway"
    TRIALS_THE_CRYPTIC_VAULT = "Trials: The Cryptic Vault"
    TRIALS_THE_DISGUISED_GATEWAY = "Trials: The Disguised Gateway"
    TRIALS_THE_ECHOING_PASSAGE = "Trials: The Echoing Passage"
    TRIALS_THE_ELUSIVE_DOOR = "Trials: The Elusive Door"
    TRIALS_THE_ENCHANTED_GATEWAY = "Trials: The Enchanted Gateway"
    TRIALS_THE_ENCHANTED_PASSAGE = "Trials: The Enchanted Passage"
    TRIALS_THE_ENIGMATIC_PORTAL = "Trials: The Enigmatic Portal"
    TRIALS_THE_ENIGMATIC_THRESHOLD = "Trials: The Enigmatic Threshold"
    TRIALS_THE_FADED_GATEWAY = "Trials: The Faded Gateway"
    TRIALS_THE_FAINT_DOORWAY = "Trials: The Faint Doorway"
    TRIALS_THE_FAINT_PATH = "Trials: The Faint Path"
    TRIALS_THE_FAINT_THRESHOLD = "Trials: The Faint Threshold"
    TRIALS_THE_FORBIDDEN_ENTRANCE = "Trials: The Forbidden Entrance"
    TRIALS_THE_FORGOTTEN_DOOR = "Trials: The Forgotten Door"
    TRIALS_THE_FORGOTTEN_GATEWAY = "Trials: The Forgotten Gateway"
    TRIALS_THE_FORGOTTEN_PORTAL = "Trials: The Forgotten Portal"
    TRIALS_THE_FORGOTTEN_THRESHOLD = "Trials: The Forgotten Threshold"
    TRIALS_THE_GHOSTED_PASSAGEWAY = "Trials: The Ghosted Passageway"
    TRIALS_THE_GHOSTLY_PASSAGE = "Trials: The Ghostly Passage"
    TRIALS_THE_HIDDEN_ARCHWAY = "Trials: The Hidden Archway"
    TRIALS_THE_HIDDEN_CHAMBER = "Trials: The Hidden Chamber"
    TRIALS_THE_HIDDEN_DOORWAY = "Trials: The Hidden Doorway"
    TRIALS_THE_HIDDEN_ENTRANCE = "Trials: The Hidden Entrance"
    TRIALS_THE_HIDDEN_KEYHOLE = "Trials: The Hidden Keyhole"
    TRIALS_THE_HIDDEN_PASSAGEWAY = "Trials: The Hidden Passageway"
    TRIALS_THE_HIDDEN_PATH = "Trials: The Hidden Path"
    TRIALS_THE_HIDDEN_REACH = "Trials: The Hidden Reach"
    TRIALS_THE_HIDDEN_VAULT = "Trials: The Hidden Vault"
    TRIALS_THE_INCONSPICUOUS_DOOR = "Trials: The Inconspicuous Door"
    TRIALS_THE_INVISIBLE_DOORWAY = "Trials: The Invisible Doorway"
    TRIALS_THE_LOCKED_DOORWAY = "Trials: The Locked Doorway"
    TRIALS_THE_LOCKED_GATEWAY = "Trials: The Locked Gateway"
    TRIALS_THE_LOST_ARCHWAY = "Trials: The Lost Archway"
    TRIALS_THE_LOST_PORTAL = "Trials: The Lost Portal"
    TRIALS_THE_LOST_THRESHOLD = "Trials: The Lost Threshold"
    TRIALS_THE_MYSTERIOUS_ARCH = "Trials: The Mysterious Arch"
    TRIALS_THE_MYSTERIOUS_DOORWAY = "Trials: The Mysterious Doorway"
    TRIALS_THE_MYSTERIOUS_PASSAGE = "Trials: The Mysterious Passage"
    TRIALS_THE_MYSTERIOUS_VAULT = "Trials: The Mysterious Vault"
    TRIALS_THE_MYSTICAL_PASSAGE = "Trials: The Mystical Passage"
    TRIALS_THE_OBSCURED_ARCH = "Trials: The Obscured Arch"
    TRIALS_THE_OBSCURED_DOORWAY = "Trials: The Obscured Doorway"
    TRIALS_THE_OBSCURED_PORTAL = "Trials: The Obscured Portal"
    TRIALS_THE_OBSCURED_VAULT = "Trials: The Obscured Vault"
    TRIALS_THE_OBSCURE_PASSAGE = "Trials: The Obscure Passage"
    TRIALS_THE_PHANTOM_PASSAGE = "Trials: The Phantom Passage"
    TRIALS_THE_PHANTOM_VAULT = "Trials: The Phantom Vault"
    TRIALS_THE_QUIET_ARCHWAY = "Trials: The Quiet Archway"
    TRIALS_THE_QUIET_THRESHOLD = "Trials: The Quiet Threshold"
    TRIALS_THE_SEALED_CHAMBER = "Trials: The Sealed Chamber"
    TRIALS_THE_SEALED_GATEWAY = "Trials: The Sealed Gateway"
    TRIALS_THE_SEALED_THRESHOLD = "Trials: The Sealed Threshold"
    TRIALS_THE_SECRETED_DOOR = "Trials: The Secreted Door"
    TRIALS_THE_SECRETIVE_DOOR = "Trials: The Secretive Door"
    TRIALS_THE_SECRET_ARCHWAY = "Trials: The Secret Archway"
    TRIALS_THE_SECRET_PASSAGEWAY = "Trials: The Secret Passageway"
    TRIALS_THE_SECRET_THRESHOLD = "Trials: The Secret Threshold"
    TRIALS_THE_SECRET_VAULT = "Trials: The Secret Vault"
    TRIALS_THE_SHADOWED_PORTAL = "Trials: The Shadowed Portal"
    TRIALS_THE_SHADOWED_THRESHOLD = "Trials: The Shadowed Threshold"
    TRIALS_THE_SHADOWY_PASSAGE = "Trials: The Shadowy Passage"
    TRIALS_THE_SHIMMERING_PASSAGE = "Trials: The Shimmering Passage"
    TRIALS_THE_SHROUDED_GATEWAY = "Trials: The Shrouded Gateway"
    TRIALS_THE_SHROUDED_PORTAL = "Trials: The Shrouded Portal"
    TRIALS_THE_SILENT_ARCHWAY = "Trials: The Silent Archway"
    TRIALS_THE_SILENT_PASSAGE = "Trials: The Silent Passage"
    TRIALS_THE_SILENT_THRESHOLD = "Trials: The Silent Threshold"
    TRIALS_THE_SILENT_VAULT = "Trials: The Silent Vault"
    TRIALS_THE_UNFATHOMABLE_DOOR = "Trials: The Unfathomable Door"
    TRIALS_THE_UNKNOWN_ARCH = "Trials: The Unknown Arch"
    TRIALS_THE_UNKNOWN_GATEWAY = "Trials: The Unknown Gateway"
    TRIALS_THE_UNMARKED_PASSAGE = "Trials: The Unmarked Passage"
    TRIALS_THE_UNMARKED_VAULT = "Trials: The Unmarked Vault"
    TRIALS_THE_UNRAVELED_DOOR = "Trials: The Unraveled Door"
    TRIALS_THE_UNSEEN_ARCHWAY = "Trials: The Unseen Archway"
    TRIALS_THE_UNSEEN_DOOR = "Trials: The Unseen Door"
    TRIALS_THE_UNSEEN_PASSAGE = "Trials: The Unseen Passage"
    TRIALS_THE_UNSEEN_PORTAL = "Trials: The Unseen Portal"
    TRIALS_THE_UNSPOKEN_GATE = "Trials: The Unspoken Gate"
    TRIALS_THE_UNTOLD_GATEWAY = "Trials: The Untold Gateway"
    TRIALS_THE_UNTRACEABLE_PATH = "Trials: The Untraceable Path"
    TRIALS_THE_VANISHING_ARCHWAY = "Trials: The Vanishing Archway"
    TRIALS_THE_VANISHING_DOOR = "Trials: The Vanishing Door"
    TRIALS_THE_VAULT_OF_WHISPERS = "Trials: The Vault of Whispers"
    TRIALS_THE_VEILED_PASSAGE = "Trials: The Veiled Passage"
    TRIALS_THE_VEILED_PATH = "Trials: The Veiled Path"
    TRIALS_THE_WHISPERED_PORTAL = "Trials: The Whispered Portal"
    TRIALS_THE_WHISPERED_THRESHOLD = "Trials: The Whispered Threshold"
    TRIALS_THE_WHISPERING_DOOR = "Trials: The Whispering Door"


class KeymastersKeepTrials(enum.Enum):
    TRIAL_BANSHEE = "Trial of the Banshee"
    TRIAL_BASILISK = "Trial of the Basilisk"
    TRIAL_CHIMERA = "Trial of the Chimera"
    TRIAL_CYCLOPS = "Trial of the Cyclops"
    TRIAL_DIREWOLF = "Trial of the Direwolf"
    TRIAL_DRAGON = "Trial of the Dragon"
    TRIAL_GIANT = "Trial of the Giant"
    TRIAL_GORGON = "Trial of the Gorgon"
    TRIAL_GRIFFIN = "Trial of the Griffin"
    TRIAL_HARPY = "Trial of the Harpy"
    TRIAL_HYDRAGON = "Trial of the Hydra"
    TRIAL_KRAKEN = "Trial of the Kraken"
    TRIAL_MANDRAKE = "Trial of the Mandrake"
    TRIAL_MANTICORE = "Trial of the Manticore"
    TRIAL_MINOTAUR = "Trial of the Minotaur"
    TRIAL_OGRE = "Trial of the Ogre"
    TRIAL_PEGASUS = "Trial of the Pegasus"
    TRIAL_PHOENIX = "Trial of the Phoenix"
    TRIAL_SASQUATCH = "Trial of the Sasquatch"
    TRIAL_SPHINX = "Trial of the Sphinx"
    TRIAL_TROLL = "Trial of the Troll"
    TRIAL_VALKYRIE = "Trial of the Valkyrie"
    TRIAL_WENDIGO = "Trial of the Wendigo"
    TRIAL_WYVERN = "Trial of the Wyvern"
    TRIAL_YETI = "Trial of the Yeti"
