from collections.abc import Callable

from BaseClasses import Item, ItemClassification, Location


class MinishCapItem(Item):
    game: str = "The Minish Cap"


class MinishCapLocation(Location):
    game: str = "The Minish Cap"


class TMCItem:
    SMITHS_SWORD = "Smith's Sword"
    WHITE_SWORD_GREEN = "White Sword (Green)"
    WHITE_SWORD_RED = "White Sword (Red)"
    WHITE_SWORD_BLUE = "White Sword (Blue)"
    FOUR_SWORD = "Four Sword"
    BOMB = "Bomb"
    REMOTE_BOMB = "Remote Bomb"
    BOW = "Bow"
    LIGHT_ARROW = "Light Arrow"
    BOOMERANG = "Boomerang"
    MAGIC_BOOMERANG = "Magic Boomerang"
    SHIELD = "Shield"
    MIRROR_SHIELD = "Mirror Shield"
    LANTERN = "Lantern"
    GUST_JAR = "Gust Jar"
    CANE_OF_PACCI = "Cane of Pacci"
    MOLE_MITTS = "Mole Mitts"
    ROCS_CAPE = "Roc's Cape"
    PEGASUS_BOOTS = "Pegasus Boots"
    FIRE_ROD = "Fire Rod"
    OCARINA = "Ocarina"
    BOTTLE = "Bottle (Null)"
    BOTTLE_1 = "Bottle 1"
    BOTTLE_2 = "Bottle 2"
    BOTTLE_3 = "Bottle 3"
    BOTTLE_4 = "Bottle 4"
    EMPTY_BOTTLE = "Bottle (Empty)"
    LON_LON_BUTTER = "Bottle (Lon Lon Butter)"
    LON_LON_MILK = "Bottle (Lon Lon Milk)"
    LON_LON_MILK_HALF = "Bottle (Lon Lon Milk (1/2))"
    RED_POTION = "Bottle (Red Potion)"
    BLUE_POTION = "Bottle (Blue Potion)"
    WATER = "Bottle (Water)"
    MINERAL_WATER = "Bottle (Mineral Water)"
    BOTTLED_FAIRY = "Bottle (Bottled Fairy)"
    RED_PICOLYTE = "Bottle (Red Picolyte)"
    ORANGE_PICOLYTE = "Bottle (Orange Picolyte)"
    YELLOW_PICOLYTE = "Bottle (Yellow Picolyte)"
    GREEN_PICOLYTE = "Bottle (Green Picolyte)"
    BLUE_PICOLYTE = "Bottle (Blue Picolyte)"
    WHITE_PICOLYTE = "Bottle (White Picolyte)"
    NAYRU_CHARM = "Bottle (Nayru Charm)"
    FARORE_CHARM = "Bottle (Farore Charm)"
    DINS_CHARM = "Bottle (Dins Charm)"
    SMITH_SWORD_QUEST = "Smith Sword (Quest)"
    BROKEN_PICORI_BLADE = "Broken Picori Blade"
    DOG_FOOD = "Dog Food"
    LONLON_KEY = "LonLon Key"
    WAKEUP_MUSHROOM = "Wakeup Mushroom"
    RED_BOOK = "Red Book (Hyrulian Bestiary)"
    GREEN_BOOK = "Green Book (Picori Legend)"
    BLUE_BOOK = "Blue Book (History of Masks)"
    GRAVEYARD_KEY = "Graveyard Key"
    TINGLE_TROPHY = "Tingle Trophy"
    CARLOV_MEDAL = "Carlov Medal"
    SHELLS = "Shells"
    EARTH_ELEMENT = "Earth Element"
    FIRE_ELEMENT = "Fire Element"
    WATER_ELEMENT = "Water Element"
    WIND_ELEMENT = "Wind Element"
    GRIP_RING = "Grip Ring"
    POWER_BRACELETS = "Power Bracelets"
    FLIPPERS = "Flippers"
    HYRULE_MAP = "Hyrule Map"
    SPIN_ATTACK = "Spin Attack"
    ROLL_ATTACK = "Roll Attack"
    DASH_ATTACK = "Dash Attack"
    ROCK_BREAKER = "Rock Breaker"
    SWORD_BEAM = "Sword Beam"
    GREATSPIN = "Greatspin"
    DOWNTHRUST = "DownThrust"
    PERIL_BEAM = "Peril Beam"
    RUPEES_1 = "1 Rupee"
    RUPEES_5 = "5 Rupees"
    RUPEES_20 = "20 Rupees"
    RUPEES_50 = "50 Rupees"
    RUPEES_100 = "100 Rupees"
    RUPEES_200 = "200 Rupees"
    JABBER_NUT = "Jabber Nut"
    KINSTONE = "Broken Kinstone (Report Me!)"
    KINSTONE_GOLD_CLOUD = "Kinstone Cloud Tops"
    KINSTONE_GOLD_SWAMP = "Kinstone Swamp"
    KINSTONE_GOLD_FALLS = "Kinstone Falls"
    KINSTONE_RED_W = "Kinstone Red W"
    KINSTONE_RED_ANGLE = "Kinstone Red >"
    KINSTONE_RED_E = "Kinstone Red E"
    KINSTONE_BLUE_L = "Kinstone Blue L"
    KINSTONE_BLUE_6 = "Kinstone Blue 6"
    KINSTONE_GREEN_ANGLE = "Kinstone Green <"
    KINSTONE_GREEN_SQUARE = "Kinstone Green ["
    KINSTONE_GREEN_P = "Kinstone Green P"
    SHELLS_30 = "30 Shells"
    HEART_CONTAINER = "Heart Container"
    HEART_PIECE = "Heart Piece"
    BIG_WALLET = "Big Wallet"
    BOMB_BAG = "Bomb Bag"
    QUIVER = "Quiver"
    KINSTONE_BAG = "Kinstone Bag"
    BRIOCHE = "Brioche"
    CROISSANT = "Croissant"
    PIE = "Pie"
    CAKE = "Cake"
    HEART_REFILL = "Recovery Heart"
    FAIRY_REFILL = "Fairy Refill"
    BOMB_REFILL_5 = "5 Bomb Refill"
    ARROW_REFILL_5 = "5 Arrow Refill"
    BOMB_REFILL_10 = "10 Bomb Refill"
    BOMB_REFILL_30 = "30 Bomb Refill"
    ARROW_REFILL_10 = "10 Arrow Refill"
    ARROW_REFILL_30 = "30 Arrow Refill"
    BOW_BUTTERFLY = "Bow Butterfly"
    DIG_BUTTERFLY = "Dig Butterfly"
    SWIM_BUTTERFLY = "Swim Butterfly"
    FAST_SPIN_SCROLL = "Fast Spin Scroll"
    FAST_SPLIT_SCROLL = "Fast Split Scroll"
    LONG_SPIN = "Long Spin"
    PROGRESSIVE_SWORD = "Progressive Sword"
    PROGRESSIVE_BOMB = "Progressive Bomb"
    PROGRESSIVE_BOW = "Progressive Bow"
    PROGRESSIVE_BOOMERANG = "Progressive Boomerang"
    PROGRESSIVE_SHIELD = "Progressive Shield"
    PROGRESSIVE_SCROLL = "Progressive Spin Scroll"

    TRAP_ICE = "Freeze Trap"
    TRAP_FIRE = "Burn Trap"
    TRAP_ZAP = "Zap Trap"
    TRAP_BOMB = "Bomb Trap"
    TRAP_MONEY = "Rupee Trap"
    TRAP_STINK = "Stink Trap"
    TRAP_ROPE = "Rope Trap"
    TRAP_BAT = "Bat Trap"
    TRAP_LIKE = "LikeLike Trap"
    TRAP_CURSE = "Curse Trap"

    DUNGEON_MAP_DWS = "Dungeon Map (DWS)"
    DUNGEON_MAP_COF = "Dungeon Map (CoF)"
    DUNGEON_MAP_FOW = "Dungeon Map (FoW)"
    DUNGEON_MAP_TOD = "Dungeon Map (ToD)"
    DUNGEON_MAP_POW = "Dungeon Map (PoW)"
    DUNGEON_MAP_DHC = "Dungeon Map (DHC)"

    DUNGEON_COMPASS_DWS = "Dungeon Compass (DWS)"
    DUNGEON_COMPASS_COF = "Dungeon Compass (CoF)"
    DUNGEON_COMPASS_FOW = "Dungeon Compass (FoW)"
    DUNGEON_COMPASS_TOD = "Dungeon Compass (ToD)"
    DUNGEON_COMPASS_POW = "Dungeon Compass (PoW)"
    DUNGEON_COMPASS_DHC = "Dungeon Compass (DHC)"

    BIG_KEY_DWS = "Big Key (DWS)"
    BIG_KEY_COF = "Big Key (CoF)"
    BIG_KEY_FOW = "Big Key (FoW)"
    BIG_KEY_TOD = "Big Key (ToD)"
    BIG_KEY_POW = "Big Key (PoW)"
    BIG_KEY_DHC = "Big Key (DHC)"

    SMALL_KEY_DWS = "Small Key (DWS)"
    SMALL_KEY_COF = "Small Key (CoF)"
    SMALL_KEY_FOW = "Small Key (FoW)"
    SMALL_KEY_TOD = "Small Key (ToD)"
    SMALL_KEY_POW = "Small Key (PoW)"
    SMALL_KEY_DHC = "Small Key (DHC)"
    SMALL_KEY_RC = "Small Key (RC)"


class TMCLocation:
    SMITH_HOUSE_CHEST = "South Field Smith House Chest"
    SMITH_HOUSE_SWORD = "South Field Smith House Left Item"
    SMITH_HOUSE_SHIELD = "South Field Smith House Right Item"
    SOUTH_FIELD_PUDDLE_FUSION_ITEM1 = "South Field Puddle Fusion Item Top Left"
    SOUTH_FIELD_PUDDLE_FUSION_ITEM2 = "South Field Puddle Fusion Item Top Middle Left"
    SOUTH_FIELD_PUDDLE_FUSION_ITEM3 = "South Field Puddle Fusion Item Top Middle"
    SOUTH_FIELD_PUDDLE_FUSION_ITEM4 = "South Field Puddle Fusion Item Top Middle Right"
    SOUTH_FIELD_PUDDLE_FUSION_ITEM5 = "South Field Puddle Fusion Item Top Right"
    SOUTH_FIELD_PUDDLE_FUSION_ITEM6 = "South Field Puddle Fusion Item Center Left"
    SOUTH_FIELD_PUDDLE_FUSION_ITEM7 = "South Field Puddle Fusion Item Center Middle Left"
    SOUTH_FIELD_PUDDLE_FUSION_ITEM8 = "South Field Puddle Fusion Item Center Middle"
    SOUTH_FIELD_PUDDLE_FUSION_ITEM9 = "South Field Puddle Fusion Item Center Middle Right"
    SOUTH_FIELD_PUDDLE_FUSION_ITEM10 = "South Field Puddle Fusion Item Center Right"
    SOUTH_FIELD_PUDDLE_FUSION_ITEM11 = "South Field Puddle Fusion Item Bottom Left"
    SOUTH_FIELD_PUDDLE_FUSION_ITEM12 = "South Field Puddle Fusion Item Bottom Middle Left"
    SOUTH_FIELD_PUDDLE_FUSION_ITEM13 = "South Field Puddle Fusion Item Bottom Middle"
    SOUTH_FIELD_PUDDLE_FUSION_ITEM14 = "South Field Puddle Fusion Item Bottom Middle Right"
    SOUTH_FIELD_PUDDLE_FUSION_ITEM15 = "South Field Puddle Fusion Item Bottom Right"
    SOUTH_FIELD_FUSION_CHEST = "South Field Fusion Chest"
    SOUTH_FIELD_TREE_FUSION_HP = "South Field Tree Fusion Item"
    SOUTH_FIELD_MINISH_SIZE_WATER_HOLE_HP = "South Field Minish Size Water Hole Item"
    SOUTH_FIELD_TINGLE_NPC = "South Field Tingle NPC"
    TOWN_CAFE_LADY_NPC = "Town Cafe Lady NPC"
    TOWN_SHOP_80_ITEM = "Town Shop 80 Item"
    TOWN_SHOP_300_ITEM = "Town Shop 300 Item"
    TOWN_SHOP_600_ITEM = "Town Shop 600 Item"
    TOWN_SHOP_EXTRA_600_ITEM = "Town Shop 600 Item 2"
    TOWN_SHOP_BEHIND_COUNTER_ITEM = "Town Shop Behind Counter Item"
    TOWN_SHOP_ATTIC_CHEST = "Town Shop Attic Chest"
    TOWN_BAKERY_ATTIC_CHEST = "Town Bakery Attic Chest"
    TOWN_INN_BACKDOOR_HP = "Town Inn Backdoor HP"
    TOWN_INN_LEDGE_CHEST = "Town Inn Ledge Chest"
    TOWN_INN_POT = "Town Inn Pot"
    TOWN_WELL_RIGHT_CHEST = "Town Well Right Chest"
    TOWN_GORON_MERCHANT_1_LEFT = "Town Goron Merchant Left"  # "Town Goron Merchant 1 Left"
    TOWN_GORON_MERCHANT_1_MIDDLE = "Town Goron Merchant Middle"  # "Town Goron Merchant 1 Middle"
    TOWN_GORON_MERCHANT_1_RIGHT = "Town Goron Merchant Right"  # "Town Goron Merchant 1 Right"
    TOWN_GORON_MERCHANT_2_LEFT = "Town Goron Merchant 2 Left"
    TOWN_GORON_MERCHANT_2_MIDDLE = "Town Goron Merchant 2 Middle"
    TOWN_GORON_MERCHANT_2_RIGHT = "Town Goron Merchant 2 Right"
    TOWN_GORON_MERCHANT_3_LEFT = "Town Goron Merchant 3 Left"
    TOWN_GORON_MERCHANT_3_MIDDLE = "Town Goron Merchant 3 Middle"
    TOWN_GORON_MERCHANT_3_RIGHT = "Town Goron Merchant 3 Right"
    TOWN_GORON_MERCHANT_4_LEFT = "Town Goron Merchant 4 Left"
    TOWN_GORON_MERCHANT_4_MIDDLE = "Town Goron Merchant 4 Middle"
    TOWN_GORON_MERCHANT_4_RIGHT = "Town Goron Merchant 4 Right"
    TOWN_GORON_MERCHANT_5_LEFT = "Town Goron Merchant 5 Left"
    TOWN_GORON_MERCHANT_5_MIDDLE = "Town Goron Merchant 5 Middle"
    TOWN_GORON_MERCHANT_5_RIGHT = "Town Goron Merchant 5 Right"
    TOWN_DOJO_NPC_1 = "Town Dojo NPC Sword"
    TOWN_DOJO_NPC_2 = "Town Dojo NPC Green Sword"
    TOWN_DOJO_NPC_3 = "Town Dojo NPC Boots + Sword"
    TOWN_DOJO_NPC_4 = "Town Dojo NPC Cape + Sword"
    TOWN_WELL_TOP_CHEST = "Town Well Top Chest"
    TOWN_SCHOOL_ROOF_CHEST = "Town School Roof Chest"
    TOWN_SCHOOL_PATH_FUSION_CHEST = "Town School Path Fusion Chest"
    TOWN_SCHOOL_PATH_LEFT_CHEST = "Town School Path Left Chest"
    TOWN_SCHOOL_PATH_MIDDLE_CHEST = "Town School Path Middle Chest"
    TOWN_SCHOOL_PATH_RIGHT_CHEST = "Town School Path Right Chest"
    TOWN_SCHOOL_PATH_HP = "Town School Path HP"
    TOWN_DIGGING_TOP_CHEST = "Town Digging Top Chest"
    TOWN_DIGGING_RIGHT_CHEST = "Town Digging Right Chest"
    TOWN_DIGGING_LEFT_CHEST = "Town Digging Left Chest"
    TOWN_WELL_LEFT_CHEST = "Town Well Left Chest"
    TOWN_BELL_HP = "Town Bell HP"
    TOWN_WATERFALL_FUSION_CHEST = "Town Waterfall Fusion Chest"
    TOWN_CARLOV_NPC = "Town Carlov NPC"
    TOWN_WELL_BOTTOM_CHEST = "Town Well Bottom Chest"
    TOWN_CUCCOS_LV_1_NPC = "Town Cuccos Lv 1 NPC"
    TOWN_CUCCOS_LV_2_NPC = "Town Cuccos Lv 2 NPC"
    TOWN_CUCCOS_LV_3_NPC = "Town Cuccos Lv 3 NPC"
    TOWN_CUCCOS_LV_4_NPC = "Town Cuccos Lv 4 NPC"
    TOWN_CUCCOS_LV_5_NPC = "Town Cuccos Lv 5 NPC"
    TOWN_CUCCOS_LV_6_NPC = "Town Cuccos Lv 6 NPC"
    TOWN_CUCCOS_LV_7_NPC = "Town Cuccos Lv 7 NPC"
    TOWN_CUCCOS_LV_8_NPC = "Town Cuccos Lv 8 NPC"
    TOWN_CUCCOS_LV_9_NPC = "Town Cuccos Lv 9 NPC"
    TOWN_CUCCOS_LV_10_NPC = "Town Cuccos NPC"  # "Town Cuccos Lv 10 NPC"
    TOWN_JULLIETA_ITEM = "Town Jullieta Item"
    TOWN_SIMULATION_CHEST = "Town Simulation Chest"
    TOWN_SHOE_SHOP_NPC = "Town Shoe Shop NPC"
    TOWN_MUSIC_HOUSE_LEFT_CHEST = "Town Music House Left Chest"
    TOWN_MUSIC_HOUSE_MIDDLE_CHEST = "Town Music House Middle Chest"
    TOWN_MUSIC_HOUSE_RIGHT_CHEST = "Town Music House Right Chest"
    TOWN_MUSIC_HOUSE_HP = "Town Music House HP"
    TOWN_WELL_PILLAR_CHEST = "Town Well Pillar Chest"
    TOWN_DR_LEFT_ATTIC_ITEM = "Town Dr Left Attic Item"
    TOWN_FOUNTAIN_BIG_CHEST = "Town Fountain Big Chest"
    TOWN_FOUNTAIN_SMALL_CHEST = "Town Fountain Small Chest"
    TOWN_FOUNTAIN_HP = "Town Fountain HP"
    TOWN_LIBRARY_YELLOW_MINISH_NPC = "Town Library Yellow Minish NPC"
    TOWN_UNDER_LIBRARY_FROZEN_CHEST = "Town Under Library Frozen Chest"
    TOWN_UNDER_LIBRARY_BIG_CHEST = "Town Under Library Big Chest"
    TOWN_UNDER_LIBRARY_UNDERWATER = "Town Under Library Underwater"
    NORTH_FIELD_DIG_SPOT = "North Field Dig Spot"
    NORTH_FIELD_HP = "North Field HP"
    NORTH_FIELD_TREE_FUSION_TOP_LEFT_CHEST = "North Field Tree Fusion Top Left Chest"
    NORTH_FIELD_TREE_FUSION_TOP_RIGHT_CHEST = "North Field Tree Fusion Top Right Chest"
    NORTH_FIELD_TREE_FUSION_BOTTOM_LEFT_CHEST = "North Field Tree Fusion Bottom Left Chest"
    NORTH_FIELD_TREE_FUSION_BOTTOM_RIGHT_CHEST = "North Field Tree Fusion Bottom Right Chest"
    NORTH_FIELD_TREE_FUSION_CENTER_BIG_CHEST = "North Field Tree Fusion Center Big Chest"
    NORTH_FIELD_WATERFALL_FUSION_DOJO_NPC = "North Field Waterfall Fusion Dojo NPC"
    CASTLE_MOAT_LEFT_CHEST = "Castle Moat Left Chest"
    CASTLE_MOAT_RIGHT_CHEST = "Castle Moat Right Chest"
    CASTLE_GOLDEN_ROPE = "Castle Golden Rope"
    CASTLE_RIGHT_FOUNTAIN_FUSION_HP = "Castle Right Fountain Fusion HP"
    CASTLE_DOJO_HP = "Castle Dojo HP"
    CASTLE_DOJO_NPC = "Castle Dojo NPC"
    CASTLE_RIGHT_FOUNTAIN_FUSION_MINISH_HOLE_CHEST = "Castle Right Fountain Fusion Minish Hole Chest"
    CASTLE_LEFT_FOUNTAIN_FUSION_MINISH_HOLE_CHEST = "Castle Left Fountain Fusion Minish Hole Chest"
    DHC_MAIN_ENTRANCE = "Dungeon Entrance in Castle Gardens Main Entrance"
    DHC_SIDE_ENTRANCE = "Dungeon Entrance in Castle Gardens Secret Path"
    HILLS_GOLDEN_ROPE = "Hills Golden Rope"
    HILLS_FUSION_CHEST = "Hills Fusion Chest"
    HILLS_BEANSTALK_FUSION_LEFT_CHEST = "Hills Beanstalk Fusion Left Chest"
    HILLS_BEANSTALK_FUSION_HP = "Hills Beanstalk Fusion HP"
    HILLS_BEANSTALK_FUSION_RIGHT_CHEST = "Hills Beanstalk Fusion Right Chest"
    HILLS_BOMB_CAVE_CHEST = "Hills Bomb Cave Chest"
    MINISH_GREAT_FAIRY_NPC = "Minish Great Fairy NPC"
    HILLS_FARM_DIG_CAVE_ITEM = "Hills Farm Dig Cave Item"
    LON_LON_RANCH_POT = "Lon Lon Ranch Pot"
    LON_LON_PUDDLE_FUSION_BIG_CHEST = "Lon Lon Puddle Fusion Big Chest"
    LON_LON_CAVE_CHEST = "Lon Lon Cave Chest"
    LON_LON_CAVE_SECRET_CHEST = "Lon Lon Cave Secret Chest"
    LON_LON_PATH_FUSION_CHEST = "Lon Lon Path Fusion Chest"
    LON_LON_PATH_HP = "Lon Lon Path HP"
    LON_LON_DIG_SPOT = "Lon Lon Dig Spot"
    LON_LON_NORTH_MINISH_CRACK_CHEST = "Lon Lon North Minish Crack Chest"
    LON_LON_GORON_CAVE_FUSION_SMALL_CHEST = "Lon Lon Goron Cave Fusion Small Chest"
    LON_LON_GORON_CAVE_FUSION_BIG_CHEST = "Lon Lon Goron Cave Fusion Big Chest"
    FALLS_LOWER_LON_LON_FUSION_CHEST = "Falls Lower Lon Lon Fusion Chest"
    FALLS_LOWER_HP = "Falls Lower HP"
    FALLS_LOWER_WATERFALL_FUSION_DOJO_NPC = "Falls Lower Waterfall Fusion Dojo NPC"
    FALLS_LOWER_ROCK_ITEM1 = "Falls Lower Rock Item1"
    FALLS_LOWER_ROCK_ITEM2 = "Falls Lower Rock Item2"
    FALLS_LOWER_ROCK_ITEM3 = "Falls Lower Rock Item3"
    FALLS_LOWER_DIG_CAVE_LEFT_CHEST = "Falls Lower Dig Cave Left Chest"
    FALLS_LOWER_DIG_CAVE_RIGHT_CHEST = "Falls Lower Dig Cave Right Chest"
    HYLIA_SUNKEN_HP = "Hylia Sunken HP"
    HYLIA_DOG_NPC = "Hylia Dog NPC"
    HYLIA_SMALL_ISLAND_HP = "Hylia Small Island HP"
    HYLIA_CAPE_CAVE_TOP_RIGHT = "Hylia Cape Cave Top Right"
    HYLIA_CAPE_CAVE_BOTTOM_LEFT = "Hylia Cape Cave Bottom Left"
    HYLIA_CAPE_CAVE_TOP_LEFT = "Hylia Cape Cave Top Left"
    HYLIA_CAPE_CAVE_TOP_MIDDLE = "Hylia Cape Cave Top Middle"
    HYLIA_CAPE_CAVE_RIGHT = "Hylia Cape Cave Right"
    HYLIA_CAPE_CAVE_BOTTOM_RIGHT = "Hylia Cape Cave Bottom Right"
    HYLIA_CAPE_CAVE_BOTTOM_MIDDLE = "Hylia Cape Cave Bottom Middle"
    HYLIA_CAPE_CAVE_LON_LON_HP = "Hylia Cape Cave Lon Lon HP"
    HYLIA_BEANSTALK_FUSION_LEFT_CHEST = "Hylia Beanstalk Fusion Left Chest"
    HYLIA_BEANSTALK_FUSION_HP = "Hylia Beanstalk Fusion HP"
    HYLIA_BEANSTALK_FUSION_RIGHT_CHEST = "Hylia Beanstalk Fusion Right Chest"
    HYLIA_MIDDLE_ISLAND_FUSION_DIG_CAVE_CHEST = "Hylia Middle Island Fusion Dig Cave Chest"
    TOD_ENTRANCE = "Dungeon Entrance in Lake Hylia"
    HYLIA_BOTTOM_HP = "Hylia Bottom HP"
    HYLIA_DOJO_HP = "Hylia Dojo HP"
    HYLIA_DOJO_NPC = "Hylia Dojo NPC"
    HYLIA_CRACK_FUSION_LIBRARI_NPC = "Hylia Crack Fusion Librari NPC"
    HYLIA_NORTH_MINISH_HOLE_CHEST = "Hylia North Minish Hole Chest"
    HYLIA_SOUTH_MINISH_HOLE_CHEST = "Hylia South Minish Hole Chest"
    HYLIA_CABIN_PATH_FUSION_CHEST = "Hylia Cabin Path Fusion Chest"
    HYLIA_MAYOR_CABIN_ITEM = "Hylia Mayor Cabin Item"
    MINISH_WOODS_GOLDEN_OCTO = "Minish Woods Golden Octo"
    MINISH_WOODS_WITCH_HUT_ITEM = "Minish Woods Witch Hut Item"
    WITCH_DIGGING_CAVE_CHEST = "Witch Digging Cave Chest"
    MINISH_WOODS_NORTH_FUSION_CHEST = "Minish Woods North Fusion Chest"
    MINISH_WOODS_TOP_HP = "Minish Woods Top HP"
    MINISH_WOODS_WEST_FUSION_CHEST = "Minish Woods West Fusion Chest"
    MINISH_WOODS_LIKE_LIKE_DIGGING_CAVE_LEFT_CHEST = "Minish Woods Like Like Digging Cave Left Chest"
    MINISH_WOODS_LIKE_LIKE_DIGGING_CAVE_RIGHT_CHEST = "Minish Woods Like Like Digging Cave Right Chest"
    MINISH_WOODS_EAST_FUSION_CHEST = "Minish Woods East Fusion Chest"
    MINISH_WOODS_SOUTH_FUSION_CHEST = "Minish Woods South Fusion Chest"
    MINISH_WOODS_BOTTOM_HP = "Minish Woods Bottom HP"
    MINISH_WOODS_CRACK_FUSION_CHEST = "Minish Woods Crack Fusion Chest"
    MINISH_WOODS_MINISH_PATH_FUSION_CHEST = "Minish Woods Minish Path Fusion Chest"
    MINISH_VILLAGE_BARREL_HOUSE_ITEM = "Minish Village Barrel House Item"
    MINISH_VILLAGE_HP = "Minish Village HP"
    DWS_ENTRANCE = "Dungeon Entrance in Minish Woods"
    MINISH_WOODS_BOMB_MINISH_NPC_1 = "Minish Woods Bomb Minish NPC 1"
    MINISH_WOODS_BOMB_MINISH_NPC_2 = "Minish Woods Bomb Minish NPC 2"
    MINISH_WOODS_POST_VILLAGE_FUSION_CHEST = "Minish Woods Post Village Fusion Chest"
    MINISH_WOODS_FLIPPER_HOLE_MIDDLE_CHEST = "Minish Woods Flipper Hole Middle Chest"
    MINISH_WOODS_FLIPPER_HOLE_RIGHT_CHEST = "Minish Woods Flipper Hole Right Chest"
    MINISH_WOODS_FLIPPER_HOLE_LEFT_CHEST = "Minish Woods Flipper Hole Left Chest"
    MINISH_WOODS_FLIPPER_HOLE_HP = "Minish Woods Flipper Hole HP"
    TRILBY_MIDDLE_FUSION_CHEST = "Trilby Middle Fusion Chest"
    TRILBY_TOP_FUSION_CHEST = "Trilby Top Fusion Chest"
    TRILBY_DIG_CAVE_LEFT_CHEST = "Trilby Dig Cave Left Chest"
    TRILBY_DIG_CAVE_RIGHT_CHEST = "Trilby Dig Cave Right Chest"
    TRILBY_DIG_CAVE_WATER_FUSION_CHEST = "Trilby Dig Cave Water Fusion Chest"
    TRILBY_SCRUB_NPC = "Trilby Scrub NPC"
    TRILBY_BOMB_CAVE_CHEST = "Trilby Bomb Cave Chest"
    TRILBY_PUDDLE_FUSION_ITEM1 = "Trilby Puddle Fusion Item Top Left"
    TRILBY_PUDDLE_FUSION_ITEM2 = "Trilby Puddle Fusion Item Top Middle Left"
    TRILBY_PUDDLE_FUSION_ITEM3 = "Trilby Puddle Fusion Item Top Middle"
    TRILBY_PUDDLE_FUSION_ITEM4 = "Trilby Puddle Fusion Item Top Middle Right"
    TRILBY_PUDDLE_FUSION_ITEM5 = "Trilby Puddle Fusion Item Top Right"
    TRILBY_PUDDLE_FUSION_ITEM6 = "Trilby Puddle Fusion Item Center Left"
    TRILBY_PUDDLE_FUSION_ITEM7 = "Trilby Puddle Fusion Item Center Middle Left"
    TRILBY_PUDDLE_FUSION_ITEM8 = "Trilby Puddle Fusion Item Center Middle"
    TRILBY_PUDDLE_FUSION_ITEM9 = "Trilby Puddle Fusion Item Center Middle Right"
    TRILBY_PUDDLE_FUSION_ITEM10 = "Trilby Puddle Fusion Item Center Right"
    TRILBY_PUDDLE_FUSION_ITEM11 = "Trilby Puddle Fusion Item Bottom Left"
    TRILBY_PUDDLE_FUSION_ITEM12 = "Trilby Puddle Fusion Item Bottom Middle Left"
    TRILBY_PUDDLE_FUSION_ITEM13 = "Trilby Puddle Fusion Item Bottom Middle"
    TRILBY_PUDDLE_FUSION_ITEM14 = "Trilby Puddle Fusion Item Bottom Middle Right"
    TRILBY_PUDDLE_FUSION_ITEM15 = "Trilby Puddle Fusion Item Bottom Right"
    WESTERN_WOODS_FUSION_CHEST = "Western Woods Fusion Chest"
    WESTERN_WOODS_TREE_FUSION_HP = "Western Woods Tree Fusion HP"
    WESTERN_WOODS_TOP_DIG1 = "Western Woods Top Dig 1"
    WESTERN_WOODS_TOP_DIG2 = "Western Woods Top Dig 2"
    WESTERN_WOODS_TOP_DIG3 = "Western Woods Top Dig 3"
    WESTERN_WOODS_TOP_DIG4 = "Western Woods Top Dig 4"
    WESTERN_WOODS_TOP_DIG5 = "Western Woods Top Dig 5"
    WESTERN_WOODS_TOP_DIG6 = "Western Woods Top Dig 6"
    WESTERN_WOODS_PERCY_FUSION_MOBLIN = "Western Woods Percy Fusion Moblin"
    WESTERN_WOODS_PERCY_FUSION_PERCY = "Western Woods Percy Fusion Percy"
    WESTERN_WOODS_BOTTOM_DIG1 = "Western Woods Bottom Dig 1"
    WESTERN_WOODS_BOTTOM_DIG2 = "Western Woods Bottom Dig 2"
    WESTERN_WOODS_GOLDEN_OCTO = "Western Woods Golden Octo"
    WESTERN_WOODS_BEANSTALK_FUSION_CHEST = "Western Woods Beanstalk Fusion Chest"
    WESTERN_WOODS_BEANSTALK_FUSION_ITEM1 = "Western Woods Beanstalk Fusion Item 1"
    WESTERN_WOODS_BEANSTALK_FUSION_ITEM2 = "Western Woods Beanstalk Fusion Item 2"
    WESTERN_WOODS_BEANSTALK_FUSION_ITEM3 = "Western Woods Beanstalk Fusion Item 3"
    WESTERN_WOODS_BEANSTALK_FUSION_ITEM4 = "Western Woods Beanstalk Fusion Item 4"
    WESTERN_WOODS_BEANSTALK_FUSION_ITEM5 = "Western Woods Beanstalk Fusion Item 5"
    WESTERN_WOODS_BEANSTALK_FUSION_ITEM6 = "Western Woods Beanstalk Fusion Item 6"
    WESTERN_WOODS_BEANSTALK_FUSION_ITEM7 = "Western Woods Beanstalk Fusion Item 7"
    WESTERN_WOODS_BEANSTALK_FUSION_ITEM8 = "Western Woods Beanstalk Fusion Item 8"
    WESTERN_WOODS_BEANSTALK_FUSION_ITEM9 = "Western Woods Beanstalk Fusion Item 9"
    WESTERN_WOODS_BEANSTALK_FUSION_ITEM10 = "Western Woods Beanstalk Fusion Item 10"
    WESTERN_WOODS_BEANSTALK_FUSION_ITEM11 = "Western Woods Beanstalk Fusion Item 11"
    WESTERN_WOODS_BEANSTALK_FUSION_ITEM12 = "Western Woods Beanstalk Fusion Item 12"
    WESTERN_WOODS_BEANSTALK_FUSION_ITEM13 = "Western Woods Beanstalk Fusion Item 13"
    WESTERN_WOODS_BEANSTALK_FUSION_ITEM14 = "Western Woods Beanstalk Fusion Item 14"
    WESTERN_WOODS_BEANSTALK_FUSION_ITEM15 = "Western Woods Beanstalk Fusion Item 15"
    WESTERN_WOODS_BEANSTALK_FUSION_ITEM16 = "Western Woods Beanstalk Fusion Item 16"
    CRENEL_BASE_ENTRANCE_VINE = "Crenel Base Entrance Vine"
    CRENEL_BASE_FAIRY_CAVE_ITEM1 = "Crenel Base Fairy Cave Item Left"
    CRENEL_BASE_FAIRY_CAVE_ITEM2 = "Crenel Base Fairy Cave Item Middle"
    CRENEL_BASE_FAIRY_CAVE_ITEM3 = "Crenel Base Fairy Cave Item Right"
    CRENEL_BASE_GREEN_WATER_FUSION_CHEST = "Crenel Base Green Water Fusion Chest"
    CRENEL_BASE_WEST_FUSION_CHEST = "Crenel Base West Fusion Chest"
    CRENEL_BASE_WATER_CAVE_LEFT_CHEST = "Crenel Base Water Cave Left Chest"
    CRENEL_BASE_WATER_CAVE_RIGHT_CHEST = "Crenel Base Water Cave Right Chest"
    CRENEL_BASE_WATER_CAVE_HP = "Crenel Base Water Cave HP"
    CRENEL_BASE_MINISH_VINE_HOLE_CHEST = "Crenel Base Minish Vine Hole Chest"
    CRENEL_BASE_MINISH_CRACK_CHEST = "Crenel Base Minish Crack Chest"
    CRENEL_VINE_TOP_GOLDEN_TEKTITE = "Crenel Vine Top Golden Tektite"
    CRENEL_BRIDGE_CAVE_CHEST = "Crenel Bridge Cave Chest"
    CRENEL_FAIRY_CAVE_HP = "Crenel Fairy Cave HP"
    CRENEL_BELOW_COF_GOLDEN_TEKTITE = "Crenel Below CoF Golden Tektite"
    CRENEL_SCRUB_NPC = "Crenel Scrub NPC"
    CRENEL_DOJO_LEFT_CHEST = "Crenel Dojo Left Chest"
    CRENEL_DOJO_RIGHT_CHEST = "Crenel Dojo Right Chest"
    CRENEL_DOJO_HP = "Crenel Dojo HP"
    CRENEL_DOJO_NPC = "Crenel Dojo NPC"
    CRENEL_GREAT_FAIRY_NPC = "Crenel Great Fairy NPC"
    CRENEL_CLIMB_FUSION_CHEST = "Crenel Climb Fusion Chest"
    CRENEL_DIG_CAVE_HP = "Crenel Dig Cave HP"
    CRENEL_BEANSTALK_FUSION_HP = "Crenel Beanstalk Fusion HP"
    CRENEL_BEANSTALK_FUSION_ITEM1 = "Crenel Beanstalk Fusion Item 1"
    CRENEL_BEANSTALK_FUSION_ITEM2 = "Crenel Beanstalk Fusion Item 2"
    CRENEL_BEANSTALK_FUSION_ITEM3 = "Crenel Beanstalk Fusion Item 3"
    CRENEL_BEANSTALK_FUSION_ITEM4 = "Crenel Beanstalk Fusion Item 4"
    CRENEL_BEANSTALK_FUSION_ITEM5 = "Crenel Beanstalk Fusion Item 5"
    CRENEL_BEANSTALK_FUSION_ITEM6 = "Crenel Beanstalk Fusion Item 6"
    CRENEL_BEANSTALK_FUSION_ITEM7 = "Crenel Beanstalk Fusion Item 7"
    CRENEL_BEANSTALK_FUSION_ITEM8 = "Crenel Beanstalk Fusion Item 8"
    CRENEL_RAIN_PATH_FUSION_CHEST = "Crenel Rain Path Fusion Chest"
    CRENEL_UPPER_BLOCK_CHEST = "Crenel Upper Block Chest"
    CRENEL_MINES_PATH_FUSION_CHEST = "Crenel Mines Path Fusion Chest"
    CRENEL_MELARI_LEFT_DIG = "Melari Mines: Left Dig"
    CRENEL_MELARI_CENTER_DIG = "Melari Mines: Center Dig"
    CRENEL_MELARI_BOTTOM_LEFT_DIG = "Melari Mines: Bottom Left Dig"
    CRENEL_MELARI_BOTTOM_MIDDLE_DIG = "Melari Mines: Bottom Middle Dig"
    CRENEL_MELARI_BOTTOM_RIGHT_DIG = "Melari Mines: Bottom Right Dig"
    CRENEL_MELARI_TOP_RIGHT_DIG = "Melari Mines: Top Right Dig"
    CRENEL_MELARI_TOP_MIDDLE_DIG = "Melari Mines: Top Middle Dig"
    CRENEL_MELARI_TOP_LEFT_DIG = "Melari Mines: Top Left Dig"
    COF_ENTRANCE = "Dungeon Entrance in Mt Crenel"
    SWAMP_BUTTERFLY_FUSION_ITEM = "Swamp Butterfly Fusion Item"
    SWAMP_CENTER_CAVE_DARKNUT_CHEST = "Swamp Center Cave Darknut Chest"
    SWAMP_CENTER_CHEST = "Swamp Center Chest"
    SWAMP_GOLDEN_ROPE = "Swamp Golden Rope"
    SWAMP_NEAR_WATERFALL_CAVE_HP = "Swamp Near Waterfall Cave HP"
    SWAMP_WATERFALL_FUSION_DOJO_NPC = "Swamp Waterfall Fusion Dojo NPC"
    SWAMP_NORTH_CAVE_CHEST = "Swamp North Cave Chest"
    SWAMP_DIGGING_CAVE_LEFT_CHEST = "Swamp Digging Cave Left Chest"
    SWAMP_DIGGING_CAVE_RIGHT_CHEST = "Swamp Digging Cave Right Chest"
    SWAMP_UNDERWATER_TOP = "Swamp Underwater Top"
    SWAMP_UNDERWATER_MIDDLE = "Swamp Underwater Middle"
    SWAMP_UNDERWATER_BOTTOM = "Swamp Underwater Bottom"
    SWAMP_SOUTH_CAVE_CHEST = "Swamp South Cave Chest"
    SWAMP_DOJO_HP = "Swamp Dojo HP"
    SWAMP_DOJO_NPC = "Swamp Dojo NPC"
    SWAMP_MINISH_FUSION_NORTH_CRACK_CHEST = "Swamp Minish Fusion North Crack Chest"
    SWAMP_MINISH_MULLDOZER_BIG_CHEST = "Swamp Minish Mulldozer Big Chest"
    SWAMP_MINISH_FUSION_NORTH_WEST_CRACK_CHEST = "Swamp Minish Fusion North West Crack Chest"
    SWAMP_MINISH_FUSION_WEST_CRACK_CHEST = "Swamp Minish Fusion West Crack Chest"
    SWAMP_MINISH_FUSION_VINE_CRACK_CHEST = "Swamp Minish Fusion Vine Crack Chest"
    SWAMP_MINISH_FUSION_WATER_HOLE_CHEST = "Swamp Minish Fusion Water Hole Chest"
    SWAMP_MINISH_FUSION_WATER_HOLE_HP = "Swamp Minish Fusion Water Hole HP"
    RUINS_BUTTERFLY_FUSION_ITEM = "Ruins Butterfly Fusion Item"
    RUINS_BOMB_CAVE_CHEST = "Ruins Bomb Cave Chest"
    RUINS_MINISH_HOME_CHEST = "Ruins Minish Home Chest"
    RUINS_PILLARS_FUSION_CHEST = "Ruins Pillars Fusion Chest"
    RUINS_BEAN_STALK_FUSION_BIG_CHEST = "Ruins Bean Stalk Fusion Big Chest"
    RUINS_CRACK_FUSION_CHEST = "Ruins Crack Fusion Chest"
    RUINS_MINISH_CAVE_HP = "Ruins Minish Cave HP"
    RUINS_ARMOS_KILL_LEFT_CHEST = "Ruins Armos Kill Left Chest"
    RUINS_ARMOS_KILL_RIGHT_CHEST = "Ruins Armos Kill Right Chest"
    RUINS_GOLDEN_OCTO = "Ruins Golden Octo"
    RUINS_NEAR_FOW_FUSION_CHEST = "Ruins Near Dungeon Fusion Chest"
    FOW_ENTRANCE = "Dungeon Entrance in Wind Ruins"
    VALLEY_PRE_VALLEY_FUSION_CHEST = "Valley Pre Valley Fusion Chest"
    VALLEY_GREAT_FAIRY_NPC = "Valley Great Fairy NPC"
    VALLEY_LOST_WOODS_CHEST = "Valley Lost Woods Chest"
    VALLEY_DAMPE_NPC = "Valley Dampe NPC"
    VALLEY_GRAVEYARD_BUTTERFLY_FUSION_ITEM = "Valley Graveyard Butterfly Fusion Item"
    VALLEY_GRAVEYARD_LEFT_FUSION_CHEST = "Valley Graveyard Left Fusion Chest"
    VALLEY_GRAVEYARD_LEFT_GRAVE_HP = "Valley Graveyard Left Grave HP"
    VALLEY_GRAVEYARD_RIGHT_FUSION_CHEST = "Valley Graveyard Right Fusion Chest"
    VALLEY_GRAVEYARD_RIGHT_GRAVE_FUSION_CHEST = "Valley Graveyard Right Grave Fusion Chest"
    RC_ENTRANCE = "Dungeon Entrance in Graveyard"
    CRYPT_GIBDO_LEFT_ITEM = "Crypt Gibdo Left Item"
    CRYPT_GIBDO_RIGHT_ITEM = "Crypt Gibdo Right Item"
    CRYPT_LEFT_ITEM = "Crypt Left Item"
    CRYPT_RIGHT_ITEM = "Crypt Right Item"
    CRYPT_PRIZE = "Crypt Prize"
    FALLS_ENTRANCE_HP = "Falls Entrance HP"
    FALLS_WATER_DIG_CAVE_FUSION_HP = "Falls Water Dig Cave Fusion HP"
    FALLS_WATER_DIG_CAVE_FUSION_CHEST = "Falls Water Dig Cave Fusion Chest"
    FALLS_1ST_CAVE_CHEST = "Falls 1st Cave Chest"
    FALLS_CLIFF_CHEST = "Falls Cliff Chest"
    FALLS_SOUTH_DIG_SPOT = "Falls South Dig Spot"
    FALLS_GOLDEN_TEKTITE = "Falls Golden Tektite"
    FALLS_NORTH_DIG_SPOT = "Falls North Dig Spot"
    FALLS_ROCK_FUSION_CHEST = "Falls Rock Fusion Chest"
    FALLS_WATERFALL_FUSION_HP = "Falls Waterfall Fusion HP"
    FALLS_RUPEE_CAVE_TOP_TOP = "Falls Rupee Cave Top Top"
    FALLS_RUPEE_CAVE_TOP_LEFT = "Falls Rupee Cave Top Left"
    FALLS_RUPEE_CAVE_TOP_MIDDLE = "Falls Rupee Cave Top Middle"
    FALLS_RUPEE_CAVE_TOP_RIGHT = "Falls Rupee Cave Top Right"
    FALLS_RUPEE_CAVE_TOP_BOTTOM = "Falls Rupee Cave Top Bottom"
    FALLS_RUPEE_CAVE_SIDE_TOP = "Falls Rupee Cave Side Top"
    FALLS_RUPEE_CAVE_SIDE_LEFT = "Falls Rupee Cave Side Left"
    FALLS_RUPEE_CAVE_SIDE_RIGHT = "Falls Rupee Cave Side Right"
    FALLS_RUPEE_CAVE_SIDE_BOTTOM = "Falls Rupee Cave Side Bottom"
    FALLS_RUPEE_CAVE_UNDERWATER_TOP_LEFT = "Falls Rupee Cave Underwater Top Left"
    FALLS_RUPEE_CAVE_UNDERWATER_TOP_RIGHT = "Falls Rupee Cave Underwater Top Right"
    FALLS_RUPEE_CAVE_UNDERWATER_MIDDLE_LEFT = "Falls Rupee Cave Underwater Middle Left"
    FALLS_RUPEE_CAVE_UNDERWATER_MIDDLE_RIGHT = "Falls Rupee Cave Underwater Middle Right"
    FALLS_RUPEE_CAVE_UNDERWATER_BOTTOM_LEFT = "Falls Rupee Cave Underwater Bottom Left"
    FALLS_RUPEE_CAVE_UNDERWATER_BOTTOM_RIGHT = "Falls Rupee Cave Underwater Bottom Right"
    FALLS_TOP_CAVE_BOMB_WALL_CHEST = "Falls Top Cave Bomb Wall Chest"
    FALLS_TOP_CAVE_CHEST = "Falls Top Cave Chest"
    FALLS_BIGGORON = "Falls Biggoron Item"
    CLOUDS_FREE_CHEST = "Clouds Free Chest"
    CLOUDS_NORTH_EAST_DIG_SPOT = "Clouds North East Dig Spot"
    CLOUDS_NORTH_KILL = "Clouds North Shark Kill"
    CLOUDS_NORTH_WEST_RIGHT_CHEST = "Clouds North West Right Chest"
    CLOUDS_NORTH_WEST_LEFT_CHEST = "Clouds North West Left Chest"
    CLOUDS_NORTH_WEST_DIG_SPOT = "Clouds North West Dig Spot"
    CLOUDS_NORTH_WEST_BOTTOM_CHEST = "Clouds North West Bottom Chest"
    CLOUDS_SOUTH_LEFT_CHEST = "Clouds South Left Chest"
    CLOUDS_SOUTH_DIG_SPOT = "Clouds South Dig Spot"
    CLOUDS_SOUTH_MIDDLE_CHEST = "Clouds South Middle Chest"
    CLOUDS_SOUTH_MIDDLE_DIG_SPOT = "Clouds South Middle Dig Spot"
    CLOUDS_SOUTH_KILL = "Clouds South Shark Kill"
    CLOUDS_SOUTH_RIGHT_CHEST = "Clouds South Right Chest"
    CLOUDS_SOUTH_RIGHT_DIG_SPOT = "Clouds South Right Dig Spot"
    CLOUDS_SOUTH_EAST_BOTTOM_DIG_SPOT = "Clouds South East Bottom Dig Spot"
    CLOUDS_SOUTH_EAST_TOP_DIG_SPOT = "Clouds South East Top Dig Spot"
    WIND_TRIBE_1F_LEFT_CHEST = "Wind Tribe 1F Left Chest"
    WIND_TRIBE_1F_RIGHT_CHEST = "Wind Tribe 1F Right Chest"
    WIND_TRIBE_2F_CHEST = "Wind Tribe 2F Chest"
    WIND_TRIBE_2F_GREGAL_NPC_1 = "Wind Tribe 2F Gregal NPC 1"
    WIND_TRIBE_2F_GREGAL_NPC_2 = "Wind Tribe 2F Gregal NPC 2"
    WIND_TRIBE_3F_LEFT_CHEST = "Wind Tribe 3F Left Chest"
    WIND_TRIBE_3F_CENTER_CHEST = "Wind Tribe 3F Center Chest"
    WIND_TRIBE_3F_RIGHT_CHEST = "Wind Tribe 3F Right Chest"
    WIND_TRIBE_4F_LEFT_CHEST = "Wind Tribe 4F Left Chest"
    WIND_TRIBE_4F_RIGHT_CHEST = "Wind Tribe 4F Right Chest"
    POW_ENTRANCE = "Dungeon Entrance in Wind Tribe"
    DEEPWOOD_2F_CHEST = "Deepwood 2F Chest"
    DEEPWOOD_1F_SLUG_TORCHES_CHEST = "Deepwood 1F Slug Torches Chest"
    DEEPWOOD_1F_BARREL_ROOM_CHEST = "Deepwood 1F Barrel Room Chest"
    DEEPWOOD_1F_WEST_BIG_CHEST = "Deepwood 1F West Big Chest"
    DEEPWOOD_1F_WEST_STATUE_PUZZLE_CHEST = "Deepwood 1F West Statue Puzzle Chest"
    DEEPWOOD_1F_EAST_MULLDOZER_FIGHT_ITEM = "Deepwood 1F East Mulldozer Fight Item"
    DEEPWOOD_1F_NORTH_EAST_CHEST = "Deepwood 1F North East Chest"
    DEEPWOOD_B1_SWITCH_ROOM_BIG_CHEST = "Deepwood B1 Switch Room Big Chest"
    DEEPWOOD_B1_SWITCH_ROOM_CHEST = "Deepwood B1 Switch Room Chest"
    DEEPWOOD_1F_BLUE_WARP_HP = "Deepwood 1F Blue Warp HP"
    DEEPWOOD_1F_BLUE_WARP_LEFT_CHEST = "Deepwood 1F Blue Warp Left Chest"
    DEEPWOOD_1F_BLUE_WARP_RIGHT_CHEST = "Deepwood 1F Blue Warp Right Chest"
    DEEPWOOD_1F_MADDERPILLAR_BIG_CHEST = "Deepwood 1F Madderpillar Big Chest"
    DEEPWOOD_1F_MADDERPILLAR_HP = "Deepwood 1F Madderpillar HP"
    DEEPWOOD_B1_WEST_BIG_CHEST = "Deepwood B1 West Big Chest"
    DEEPWOOD_BOSS_ITEM = "Deepwood Boss Item"
    DEEPWOOD_PRIZE = "Deepwood Prize"
    COF_1F_SPIKE_BEETLE_BIG_CHEST = "CoF 1F Spike Beetle Big Chest"
    COF_1F_ITEM1 = "CoF 1F Item Top Left"
    COF_1F_ITEM2 = "CoF 1F Item Top Middle"
    COF_1F_ITEM3 = "CoF 1F Item Top Right"
    COF_1F_ITEM4 = "CoF 1F Item Bottom Left"
    COF_1F_ITEM5 = "CoF 1F Item Bottom Right"
    COF_B1_HAZY_ROOM_BIG_CHEST = "CoF B1 Hazy Room Big Chest"
    COF_B1_HAZY_ROOM_SMALL_CHEST = "CoF B1 Hazy Room Small Chest"
    COF_B1_ROLLOBITE_CHEST = "CoF B1 Rollobite Chest"
    COF_B1_ROLLOBITE_PILLAR_CHEST = "CoF B1 Rollobite Pillar Chest"
    COF_B1_SPIKEY_CHUS_PILLAR_CHEST = "CoF B1 Spikey Chus Pillar Chest"
    COF_B1_HP = "CoF B1 HP"
    COF_B1_SPIKEY_CHUS_BIG_CHEST = "CoF B1 Spikey Chus Big Chest"
    COF_B2_PRE_LAVA_NORTH_CHEST = "CoF B2 Pre Lava North Chest"
    COF_B2_PRE_LAVA_SOUTH_CHEST = "CoF B2 Pre Lava South Chest"
    COF_B2_LAVA_ROOM_BLADE_CHEST = "CoF B2 Lava Room Blade Chest"
    COF_B2_LAVA_ROOM_RIGHT_CHEST = "CoF B2 Lava Room Right Chest"
    COF_B2_LAVA_ROOM_LEFT_CHEST = "CoF B2 Lava Room Left Chest"
    COF_B2_LAVA_ROOM_BIG_CHEST = "CoF B2 Lava Room Big Chest"
    COF_BOSS_ITEM = "CoF Boss Item"
    COF_PRIZE = "CoF Prize"
    CRENEL_MELARI_NPC = "Crenel Melari Dungeon Reward"
    FORTRESS_ENTRANCE_1F_LEFT_CHEST = "Fortress Entrance 1F Left Chest"
    FORTRESS_ENTRANCE_1F_LEFT_WIZZROBE_CHEST = "Fortress Entrance 1F Left Wizzrobe Chest"
    FORTRESS_ENTRANCE_1F_RIGHT_ITEM = "Fortress Entrance 1F Right Item"
    FORTRESS_LEFT_2F_DIG_CHEST = "Fortress Left 2F Dig Chest"
    FORTRESS_LEFT_2F_ITEM1 = "Fortress Left 2F Item 1"
    FORTRESS_LEFT_2F_ITEM2 = "Fortress Left 2F Item 2"
    FORTRESS_LEFT_2F_ITEM3 = "Fortress Left 2F Item 3"
    FORTRESS_LEFT_2F_ITEM4 = "Fortress Left 2F Item 4"
    FORTRESS_LEFT_2F_ITEM5 = "Fortress Left 2F Item 5"
    FORTRESS_LEFT_2F_ITEM6 = "Fortress Left 2F Item 6"
    FORTRESS_LEFT_2F_ITEM7 = "Fortress Left 2F Item 7"
    FORTRESS_LEFT_3F_SWITCH_CHEST = "Fortress Left 3F Switch Chest"
    FORTRESS_LEFT_3F_EYEGORE_BIG_CHEST = "Fortress Left 3F Eyegore Big Chest"
    FORTRESS_LEFT_3F_ITEM_DROP = "Fortress Left 3F Item Drop"
    FORTRESS_MIDDLE_2F_BIG_CHEST = "Fortress Middle 2F Big Chest"
    FORTRESS_MIDDLE_2F_STATUE_CHEST = "Fortress Middle 2F Statue Chest"
    FORTRESS_RIGHT_2F_LEFT_CHEST = "Fortress Right 2F Left Chest"
    FORTRESS_RIGHT_2F_RIGHT_CHEST = "Fortress Right 2F Right Chest"
    FORTRESS_RIGHT_2F_DIG_CHEST = "Fortress Right 2F Dig Chest"
    FORTRESS_RIGHT_3F_DIG_CHEST = "Fortress Right 3F Dig Chest"
    FORTRESS_RIGHT_3F_ITEM_DROP = "Fortress Right 3F Item Drop"
    FORTRESS_ENTRANCE_1F_RIGHT_HP = "Fortress Entrance 1F Right HP"
    FORTRESS_BACK_LEFT_BIG_CHEST = "Fortress Back Left Big Chest"
    FORTRESS_BACK_LEFT_SMALL_CHEST = "Fortress Back Left Small Chest"
    FORTRESS_BACK_RIGHT_STATUE_ITEM_DROP = "Fortress Back Right Statue Item Drop"
    FORTRESS_BACK_RIGHT_MINISH_ITEM_DROP = "Fortress Back Right Minish Item Drop"
    FORTRESS_BACK_RIGHT_DIG_ROOM_TOP_POT = "Fortress Back Right Dig Room Top Pot"
    FORTRESS_BACK_RIGHT_DIG_ROOM_BOTTOM_POT = "Fortress Back Right Dig Room Bottom Pot"
    FORTRESS_BACK_RIGHT_BIG_CHEST = "Fortress Back Right Big Chest"
    FORTRESS_BOSS_ITEM = "Fortress Boss Item"
    FORTRESS_PRIZE = "Fortress Prize"
    DROPLETS_ENTRANCE_B2_EAST_ICEBLOCK = "Droplets Entrance B2 East Iceblock"
    DROPLETS_ENTRANCE_B2_WEST_ICEBLOCK = "Droplets Entrance B2 West Iceblock"
    DROPLETS_LEFT_PATH_B1_UNDERPASS_ITEM1 = "Droplets Left Path B1 Underpass Item1"
    DROPLETS_LEFT_PATH_B1_UNDERPASS_ITEM2 = "Droplets Left Path B1 Underpass Item2"
    DROPLETS_LEFT_PATH_B1_UNDERPASS_ITEM3 = "Droplets Left Path B1 Underpass Item3"
    DROPLETS_LEFT_PATH_B1_UNDERPASS_ITEM4 = "Droplets Left Path B1 Underpass Item4"
    DROPLETS_LEFT_PATH_B1_UNDERPASS_ITEM5 = "Droplets Left Path B1 Underpass Item5"
    DROPLETS_LEFT_PATH_B1_WATERFALL_BIG_CHEST = "Droplets Left Path B1 Waterfall Big Chest"
    DROPLETS_LEFT_PATH_B1_WATERFALL_UNDERWATER1 = "Droplets Left Path B1 Waterfall Underwater 1"
    DROPLETS_LEFT_PATH_B1_WATERFALL_UNDERWATER2 = "Droplets Left Path B1 Waterfall Underwater 2"
    DROPLETS_LEFT_PATH_B1_WATERFALL_UNDERWATER3 = "Droplets Left Path B1 Waterfall Underwater 3"
    DROPLETS_LEFT_PATH_B1_WATERFALL_UNDERWATER4 = "Droplets Left Path B1 Waterfall Underwater 4"
    DROPLETS_LEFT_PATH_B1_WATERFALL_UNDERWATER5 = "Droplets Left Path B1 Waterfall Underwater 5"
    DROPLETS_LEFT_PATH_B1_WATERFALL_UNDERWATER6 = "Droplets Left Path B1 Waterfall Underwater 6"
    DROPLETS_LEFT_PATH_B2_WATERFALL_UNDERWATER1 = "Droplets Left Path B2 Waterfall Underwater 1"
    DROPLETS_LEFT_PATH_B2_WATERFALL_UNDERWATER2 = "Droplets Left Path B2 Waterfall Underwater 2"
    DROPLETS_LEFT_PATH_B2_WATERFALL_UNDERWATER3 = "Droplets Left Path B2 Waterfall Underwater 3"
    DROPLETS_LEFT_PATH_B2_WATERFALL_UNDERWATER4 = "Droplets Left Path B2 Waterfall Underwater 4"
    DROPLETS_LEFT_PATH_B2_WATERFALL_UNDERWATER5 = "Droplets Left Path B2 Waterfall Underwater 5"
    DROPLETS_LEFT_PATH_B2_WATERFALL_UNDERWATER6 = "Droplets Left Path B2 Waterfall Underwater 6"
    DROPLETS_LEFT_PATH_B2_UNDERWATER_POT = "Droplets Left Path B2 Underwater Pot"
    DROPLETS_LEFT_PATH_B2_ICE_MADDERPILLAR_BIG_CHEST = "Droplets Left Path B2 Ice Madderpillar Big Chest"
    DROPLETS_LEFT_PATH_B2_ICE_PLAIN_FROZEN_CHEST = "Droplets Left Path B2 Ice Plain Frozen Chest"
    DROPLETS_LEFT_PATH_B2_ICE_PLAIN_CHEST = "Droplets Left Path B2 Ice Plain Chest"
    DROPLETS_LEFT_PATH_B2_LILYPAD_CORNER_FROZEN_CHEST = "Droplets Left Path B2 Lilypad Corner Frozen Chest"
    DROPLETS_RIGHT_PATH_B1_1ST_CHEST = "Droplets Right Path B1 1st Chest"
    DROPLETS_RIGHT_PATH_B1_2ND_CHEST = "Droplets Right Path B1 2nd Chest"
    DROPLETS_RIGHT_PATH_B1_POT = "Droplets Right Path B1 Pot"
    DROPLETS_RIGHT_PATH_B3_FROZEN_CHEST = "Droplets Right Path B3Frozen Chest"
    DROPLETS_RIGHT_PATH_B1_BLU_CHU_BIG_CHEST = "Droplets Right Path B1 Blu Chu Big Chest"
    DROPLETS_RIGHT_PATH_B2_FROZEN_CHEST = "Droplets Right Path B2Frozen Chest"
    DROPLETS_RIGHT_PATH_B2_DARK_MAZE_BOTTOM_CHEST = "Droplets Right Path B2 Dark Maze Bottom Chest"
    DROPLETS_RIGHT_PATH_B2_MULLDOZERS_ITEM_DROP = "Droplets Right Path B2 Mulldozers Item Drop"
    DROPLETS_RIGHT_PATH_B2_DARK_MAZE_TOP_RIGHT_CHEST = "Droplets Right Path B2 Dark Maze Top Right Chest"
    DROPLETS_RIGHT_PATH_B2_DARK_MAZE_TOP_LEFT_CHEST = "Droplets Right Path B2 Dark Maze Top Left Chest"
    DROPLETS_RIGHT_PATH_B2_UNDERPASS_ITEM1 = "Droplets Right Path B2 Underpass Item1"
    DROPLETS_RIGHT_PATH_B2_UNDERPASS_ITEM2 = "Droplets Right Path B2 Underpass Item2"
    DROPLETS_RIGHT_PATH_B2_UNDERPASS_ITEM3 = "Droplets Right Path B2 Underpass Item3"
    DROPLETS_RIGHT_PATH_B2_UNDERPASS_ITEM4 = "Droplets Right Path B2 Underpass Item4"
    DROPLETS_RIGHT_PATH_B2_UNDERPASS_ITEM5 = "Droplets Right Path B2 Underpass Item5"
    DROPLETS_BOSS_ITEM = "Droplets Boss Item"
    DROPLETS_PRIZE = "Droplets Prize"
    PALACE_1ST_HALF_1F_GRATE_CHEST = "Palace 1st Half 1F Grate Chest"
    PALACE_1ST_HALF_1F_WIZZROBE_BIG_CHEST = "Palace 1st Half 1F Wizzrobe Big Chest"
    PALACE_1ST_HALF_2F_ITEM1 = "Palace 1st Half 2F Item1"
    PALACE_1ST_HALF_2F_ITEM2 = "Palace 1st Half 2F Item2"
    PALACE_1ST_HALF_2F_ITEM3 = "Palace 1st Half 2F Item3"
    PALACE_1ST_HALF_2F_ITEM4 = "Palace 1st Half 2F Item4"
    PALACE_1ST_HALF_2F_ITEM5 = "Palace 1st Half 2F Item5"
    PALACE_1ST_HALF_3F_POT_PUZZLE_ITEM_DROP = "Palace 1st Half 3F Pot Puzzle Item Drop"
    PALACE_1ST_HALF_4F_BOW_MOBLINS_CHEST = "Palace 1st Half 4F Bow Moblins Chest"
    PALACE_1ST_HALF_5F_BALL_AND_CHAIN_SOLDIERS_ITEM_DROP = "Palace 1st Half 5F Ball And Chain Soldiers Item Drop"
    PALACE_1ST_HALF_5F_FAN_LOOP_CHEST = "Palace 1st Half 5F Fan Loop Chest"
    PALACE_1ST_HALF_5F_BIG_CHEST = "Palace 1st Half 5F Big Chest"
    PALACE_2ND_HALF_1F_DARK_ROOM_BIG_CHEST = "Palace 2nd Half 1F Dark Room Big Chest"
    PALACE_2ND_HALF_1F_DARK_ROOM_SMALL_CHEST = "Palace 2nd Half 1F Dark Room Small Chest"
    PALACE_2ND_HALF_2F_MANY_ROLLERS_CHEST = "Palace 2nd Half 2F Many Rollers Chest"
    PALACE_2ND_HALF_2F_TWIN_WIZZROBES_CHEST = "Palace 2nd Half 2F Twin Wizzrobes Chest"
    PALACE_2ND_HALF_3F_FIRE_WIZZROBES_BIG_CHEST = "Palace 2nd Half 3F Fire Wizzrobes Big Chest"
    PALACE_2ND_HALF_4F_HP = "Palace 2nd Half 4F HP"
    PALACE_2ND_HALF_4F_SWITCH_HIT_CHEST = "Palace 2nd Half 4F Switch Hit Chest"
    PALACE_2ND_HALF_5F_BOMBAROSSA_CHEST = "Palace 2nd Half 5F Bombarossa Chest"
    PALACE_2ND_HALF_4F_BLOCK_MAZE_CHEST = "Palace 2nd Half 4F Block Maze Chest"
    PALACE_2ND_HALF_5F_RIGHT_SIDE_CHEST = "Palace 2nd Half 5F Right Side Chest"
    PALACE_BOSS_ITEM = "Palace Boss Item"
    PALACE_PRIZE = "Palace Prize"
    SANCTUARY_PEDESTAL_ITEM1 = "Sanctuary Pedestal Item1"
    SANCTUARY_PEDESTAL_ITEM2 = "Sanctuary Pedestal Item2"
    SANCTUARY_PEDESTAL_ITEM3 = "Sanctuary Pedestal Item3"
    DHC_B2_KING = "DHC B2 King"
    DHC_B1_BIG_CHEST = "DHC B1 Big Chest"
    DHC_1F_BLADE_CHEST = "DHC 1F Blade Chest"
    DHC_1F_THRONE_BIG_CHEST = "DHC 1F Throne Big Chest"
    DHC_3F_NORTH_WEST_CHEST = "DHC 3F North West Chest"
    DHC_3F_NORTH_EAST_CHEST = "DHC 3F North East Chest"
    DHC_3F_SOUTH_WEST_CHEST = "DHC 3F South West Chest"
    DHC_3F_SOUTH_EAST_CHEST = "DHC 3F South East Chest"
    DHC_2F_BLUE_WARP_BIG_CHEST = "DHC 2F Blue Warp Big Chest"


class TMCEvent:
    CLEAR_DWS = "Clear DWS"
    CLEAR_COF = "Clear CoF"
    CLEAR_FOW = "Clear FoW"
    CLEAR_TOD = "Clear ToD"
    CLEAR_RC = "Clear RC"
    CLEAR_POW = "Clear PoW"
    CLEAR_PED = "Pedestal Complete"
    CLEAR_DHC = "Kill Vaati"


class TMCRegion:
    SOUTH_FIELD = "South Field"
    HYRULE_TOWN = "Hyrule Town"
    NORTH_FIELD = "North Field"
    CASTLE_EXTERIOR = "Castle Exterior"
    EASTERN_HILLS = "Eastern Hills"
    LONLON = "LonLon"
    LOWER_FALLS = "Lower Falls"
    LAKE_HYLIA_NORTH = "Lake Hylia North"
    LAKE_HYLIA_SOUTH = "Lake Hylia South"
    MINISH_WOODS = "Minish Woods"
    TRILBY_HIGHLANDS = "Trilby Highlands"
    WESTERN_WOODS = "Western Woods"
    CRENEL_BASE = "Crenel Base"
    CRENEL = "Crenel"
    MELARI = "Melari"
    CASTOR_WILDS = "Castor Wilds"
    WIND_RUINS = "Ruins"
    ROYAL_VALLEY = "Royal Valley"
    GRAVEYARD = "Graveyard"
    DUNGEON_RC = "Dungeon RC"
    DUNGEON_RC_CLEAR = "Dungeon RC Clear"
    UPPER_FALLS = "Upper Falls"
    CLOUDS = "Clouds"
    WIND_TRIBE = "Wind Tribe"
    DUNGEON_DWS = "Deepwood Shrine"
    DUNGEON_DWS_CLEAR = "Deepwood Shrine Clear"
    DUNGEON_COF = "Cave of Flames"
    DUNGEON_COF_CLEAR = "Cave of Flames Clear"
    DUNGEON_FOW = "Fortress of Winds"
    DUNGEON_FOW_CLEAR = "Fortress of Winds Clear"
    DUNGEON_TOD = "Temple of Droplets"
    DUNGEON_TOD_CLEAR = "Temple of Droplets Clear"
    DUNGEON_TOD_MAIN = "Temple of Droplets After Big key"
    DUNGEON_POW = "Palace of Winds"
    DUNGEON_POW_CLEAR = "Palace of Winds Clear"
    SANCTUARY = "Sanctuary"
    DUNGEON_DHC = "Dark Hyrule Castle"
    VAATI_FIGHT = "Vaati Fight"


class TMCTricks:
    MITTS_FARM = "mitts_farm_rupees"
    BOMB_DUST = "bombable_dust"
    MUSHROOM = "crenel_mushroom_gust_jar"
    ARROWS_BREAK = "light_arrows_break_objects"
    BOBOMB_WALLS = "bobombs_destroy_walls"
    LIKELIKE_SWORDLESS = "like_like_cave_no_sword"
    BOOTS_GUARDS = "boots_skip_town_guard"
    BEAM_CRENEL_SWITCH = "beam_crenel_switch"
    DOWNTHRUST_BEETLE = "down_thrust_spikey_beetle"
    DARK_ROOMS = "dark_rooms_no_lantern"
    CAPE_EXTENSIONS = "cape_extensions"
    LAKE_MINISH = "lake_minish_no_boots"
    CABIN_SWIM = "cabin_swim_no_lilypad"
    SHARKS_SWORDLESS = "cloud_sharks_no_weapons"
    POW_NOCANE = "pow_2f_no_cane"
    POT_PUZZLE = "pot_puzzle_no_bracelets"
    FOW_POT = "fow_pot_gust_jar"
    DHC_CANNONS = "dhc_cannons_no_four_sword"
    DHC_CLONES = "dhc_pads_no_four_sword"
    DHC_SPIN = "dhc_switches_no_four_sword"


ALL_TRICKS = [
    TMCTricks.MITTS_FARM,
    TMCTricks.BOMB_DUST,
    TMCTricks.MUSHROOM,
    TMCTricks.ARROWS_BREAK,
    TMCTricks.BOBOMB_WALLS,
    TMCTricks.LIKELIKE_SWORDLESS,
    TMCTricks.BOOTS_GUARDS,
    TMCTricks.BEAM_CRENEL_SWITCH,
    TMCTricks.DOWNTHRUST_BEETLE,
    TMCTricks.DARK_ROOMS,
    TMCTricks.CAPE_EXTENSIONS,
    TMCTricks.LAKE_MINISH,
    TMCTricks.CABIN_SWIM,
    TMCTricks.SHARKS_SWORDLESS,
    TMCTricks.POW_NOCANE,
    TMCTricks.POT_PUZZLE,
    TMCTricks.FOW_POT,
    TMCTricks.DHC_CANNONS,
    TMCTricks.DHC_CLONES,
    TMCTricks.DHC_SPIN,
]

DUNGEON_ABBR = frozenset({"DWS", "CoF", "ToD", "FoW", "PoW", "RC", "DHC"})
DUNGEON_REGIONS = {
    "DWS": {TMCRegion.DUNGEON_DWS, TMCRegion.DUNGEON_DWS_CLEAR},
    "CoF": {TMCRegion.DUNGEON_COF, TMCRegion.DUNGEON_COF_CLEAR},
    "ToD": {TMCRegion.DUNGEON_TOD, TMCRegion.DUNGEON_TOD_CLEAR, TMCRegion.DUNGEON_TOD_MAIN},
    "FoW": {TMCRegion.DUNGEON_FOW, TMCRegion.DUNGEON_FOW_CLEAR},
    "PoW": {TMCRegion.DUNGEON_POW, TMCRegion.DUNGEON_POW_CLEAR},
    "RC": {TMCRegion.DUNGEON_RC, TMCRegion.DUNGEON_RC_CLEAR},
    "DHC": {TMCRegion.DUNGEON_DHC},
}
EXTERNAL_ITEMS = [0x18, 0x19, 0x1A]
EXTERNAL_ITEM_MAP: dict[ItemClassification, Callable[[object], int]] = {
    ItemClassification.filler: lambda random: 0x1A,
    ItemClassification.progression: lambda random: 0x18,
    ItemClassification.useful: lambda random: 0x19,
    ItemClassification.trap: lambda random: random.choice(EXTERNAL_ITEMS),
    ItemClassification.skip_balancing: lambda random: 0x19,
    ItemClassification.progression_skip_balancing: lambda random: 0x18,
}

ALL_REGIONS = [
    TMCRegion.SOUTH_FIELD,
    TMCRegion.HYRULE_TOWN,
    TMCRegion.NORTH_FIELD,
    TMCRegion.CASTLE_EXTERIOR,
    TMCRegion.EASTERN_HILLS,
    TMCRegion.LONLON,
    TMCRegion.LOWER_FALLS,
    TMCRegion.LAKE_HYLIA_NORTH,
    TMCRegion.LAKE_HYLIA_SOUTH,
    TMCRegion.MINISH_WOODS,
    TMCRegion.TRILBY_HIGHLANDS,
    TMCRegion.WESTERN_WOODS,
    TMCRegion.CRENEL_BASE,
    TMCRegion.CRENEL,
    TMCRegion.MELARI,
    TMCRegion.CASTOR_WILDS,
    TMCRegion.WIND_RUINS,
    TMCRegion.ROYAL_VALLEY,
    TMCRegion.GRAVEYARD,
    TMCRegion.DUNGEON_RC,
    TMCRegion.DUNGEON_RC_CLEAR,
    TMCRegion.UPPER_FALLS,
    TMCRegion.CLOUDS,
    TMCRegion.WIND_TRIBE,
    TMCRegion.DUNGEON_DWS,
    TMCRegion.DUNGEON_DWS_CLEAR,
    TMCRegion.DUNGEON_COF,
    TMCRegion.DUNGEON_COF_CLEAR,
    TMCRegion.DUNGEON_FOW,
    TMCRegion.DUNGEON_FOW_CLEAR,
    TMCRegion.DUNGEON_TOD,
    TMCRegion.DUNGEON_TOD_CLEAR,
    TMCRegion.DUNGEON_TOD_MAIN,
    TMCRegion.DUNGEON_POW,
    TMCRegion.DUNGEON_POW_CLEAR,
    TMCRegion.SANCTUARY,
    TMCRegion.DUNGEON_DHC,
    TMCRegion.VAATI_FIGHT,
]
