from . import Levels
from .ObjectTypes import ObjectType, SETObject
from .Names import REGION_INDICIES, REGION_RESTRICTION_TYPES
from .Weapons import WEAPONS

DESIRABLE_OBJECTS_THE_DOOM = [

    SETObject(ObjectType.HEAL_SERVER, Levels.STAGE_THE_DOOM, 397, "Heal Server 1"),
    SETObject(ObjectType.HEAL_SERVER, Levels.STAGE_THE_DOOM, 396, "Heal Server 2"),
    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_THE_DOOM, 258, "Special Weapons Box 1",
              region=0, weapon=WEAPONS.SEMI_AUTOMATIC_RIFLE),
    SETObject(ObjectType.KEY_DOOR, Levels.STAGE_THE_DOOM, 178, "Secret Door",
              region=REGION_INDICIES.THE_DOOM_KEY_DOOR),
    SETObject(ObjectType.STANDARD_PULLEY, Levels.STAGE_THE_DOOM, 189, "Pulley To Secret Door"),
    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_THE_DOOM, 109, "Special Weapons Box 2",
              region=0, weapon=WEAPONS.HEAVY_MACHINE_GUN),

    SETObject(ObjectType.BOMB_SERVER, Levels.STAGE_THE_DOOM, 214, "Bomb Server 1"),
    SETObject(ObjectType.HEAL_SERVER, Levels.STAGE_THE_DOOM, 398, "Heal Server 2"),
    SETObject(ObjectType.BOMB_SERVER, Levels.STAGE_THE_DOOM, 285, "Bomb Server 2"),
    SETObject(ObjectType.HEAL_SERVER, Levels.STAGE_THE_DOOM, 403, "Heal Server 3"),
    SETObject(ObjectType.STANDARD_PULLEY, Levels.STAGE_THE_DOOM, 194, "Pulley (Key 4)"),
    SETObject(ObjectType.HEAL_SERVER, Levels.STAGE_THE_DOOM, 400, "Heal Server 4"),

    SETObject(ObjectType.BOMB_SERVER, Levels.STAGE_THE_DOOM, 222, "Bomb Server 3"),
    SETObject(ObjectType.HEAL_SERVER, Levels.STAGE_THE_DOOM, 399, "Heal Server 5"),
    SETObject(ObjectType.HEAL_SERVER, Levels.STAGE_THE_DOOM, 401, "Heal Server 6"),
    SETObject(ObjectType.HEAL_SERVER, Levels.STAGE_THE_DOOM, 402, "Heal Server 7"),
    SETObject(ObjectType.SHADOW_BOX, Levels.STAGE_THE_DOOM, 265, "Special Weapons Box 3",
              region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH, weapon=WEAPONS.RPG),

    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 408, "Doom Researcher 1",
              region=0, restrictionType=REGION_RESTRICTION_TYPES.Heal),
    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 412, "Doom Researcher 2",
              region=0, restrictionType=REGION_RESTRICTION_TYPES.Heal),
    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 409, "Doom Researcher 3",
              region=0, restrictionType=REGION_RESTRICTION_TYPES.Heal),
    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 407, "Doom Researcher 4",
              region=REGION_INDICIES.THE_DOOM_BOMBS, restrictionType=REGION_RESTRICTION_TYPES.Heal),
    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 413, "Doom Researcher 5",
              region=REGION_INDICIES.THE_DOOM_BOMBS, restrictionType=REGION_RESTRICTION_TYPES.Heal),
    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 410, "Doom Researcher 6",
              region=REGION_INDICIES.THE_DOOM_BOMBS, restrictionType=REGION_RESTRICTION_TYPES.Heal),
    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 483, "Doom Researcher 7",
              region=REGION_INDICIES.THE_DOOM_BOMBS, restrictionType=REGION_RESTRICTION_TYPES.Heal),
    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 411, "Doom Researcher 8",
              region=REGION_INDICIES.THE_DOOM_BOMBS, restrictionType=REGION_RESTRICTION_TYPES.Heal),
    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 405, "Doom Researcher 9",
              region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH, restrictionType=REGION_RESTRICTION_TYPES.Heal),
    SETObject(ObjectType.DOOM_RESEARCHER, Levels.STAGE_THE_DOOM, 406, "Doom Researcher 10",
              region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH, restrictionType=REGION_RESTRICTION_TYPES.Heal),

    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 135, '0', region=0),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 114, '1', region=0),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 122, '2', region=0),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 123, '3', region=0),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 213, '4', region=0),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 187, '5', region=0),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 188, '6', region=0),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 186, '7', region=0),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 140, '8', region=0),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 86, '9', region=0),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 87, '10', region=0),

    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 141, '11', region=REGION_INDICIES.THE_DOOM_BOMBS),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 139, '12', region=REGION_INDICIES.THE_DOOM_BOMBS),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 127, '13', region=REGION_INDICIES.THE_DOOM_BOMBS),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 116, '14', region=REGION_INDICIES.THE_DOOM_BOMBS),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 142, '15', region=REGION_INDICIES.THE_DOOM_BOMBS),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 143, '17', region=REGION_INDICIES.THE_DOOM_BOMBS),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 144, '18', region=REGION_INDICIES.THE_DOOM_BOMBS),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 145, '19', region=REGION_INDICIES.THE_DOOM_BOMBS),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 161, '21', region=REGION_INDICIES.THE_DOOM_BOMBS),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 162, '22', region=REGION_INDICIES.THE_DOOM_BOMBS),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 163, '23', region=REGION_INDICIES.THE_DOOM_BOMBS),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 166, '24', region=REGION_INDICIES.THE_DOOM_BOMBS),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 167, '25', region=REGION_INDICIES.THE_DOOM_BOMBS),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 217, '26', region=REGION_INDICIES.THE_DOOM_BOMBS),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 219, '27', region=REGION_INDICIES.THE_DOOM_BOMBS),

    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 224, '28', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 226, '29', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),

    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 195, '30', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 259, '31', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 196, '32', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 228, '33', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 233, '34', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 231, '35', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 237, '36', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 235, '37', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 236, '38', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 239, '39', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 238, '40', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 206, '41', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 230, '42', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 260, '43', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 242, '44', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 240, '45', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),

    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 229, '45.5', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 249, '45.51', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),

    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 244, '46', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 245, '47', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 243, '48', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 246, '49', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 247, '50', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 210, '51', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 250, '52', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 252, '53', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_SOLIDER, Levels.STAGE_THE_DOOM, 251, '54', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 255, '55', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 254, '56', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_ROBOT, Levels.STAGE_THE_DOOM, 253, '57', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),
    SETObject(ObjectType.GUN_BEETLE, Levels.STAGE_THE_DOOM, 256, '58', region=REGION_INDICIES.THE_DOOM_DOOR_1_SWITCH),

    SETObject(ObjectType.GOLD_BEETLE, Levels.STAGE_THE_DOOM, 363, 'Gold Beetle',
              region=REGION_INDICIES.THE_DOOM_GOLD_BEETLE),

]