from typing import List, Set

from dataclasses import dataclass

from Options import OptionSet

from ..game import Game
from ..game_objective_template import GameObjectiveTemplate

from ..enums import KeymastersKeepGamePlatforms


class PathofExileGame(Game):
    name = "Path of Exile"
    platform = KeymastersKeepGamePlatforms.PC

    platforms_other = [
        KeymastersKeepGamePlatforms.PS4,
        KeymastersKeepGamePlatforms.PS5,
        KeymastersKeepGamePlatforms.XONE,
    ]

    is_adult_only_or_unrated = True

    should_autoregister = False

    def optional_game_constraint_templates(self) -> List[GameObjectiveTemplate]:
        return [
            GameObjectiveTemplate(
                label="Create a new ASCENDANCY character.  Solo Self-Found: SSF  Hardcore: HC",
                data={
                    "ASCENDANCY": (self.ascendancies, 1),
                    "SSF": (self.ssf, 1),
                    "HC": (self.hc, 1),
                },
            ),
        ]

    ## Items
    # Collect a high-tier item base
    # Collect X unique items
    # Collect a specific unique item

    ## Crafting
    # Use an Ancient Orb on an item
    # Roll a perfect implicit value on an item after using a Blessed Orb
    # Get X COLOR sockets on an item after using a Chromatic Orb
    # Roll a perfect affix value on an item after using a Divine Orb
    # Obtain a T1 affix on an item after using an Exalted Orb
    # Get a gem to X quality after using a Gemcutter's Prism
    # Get X sockets on an item after using a Jeweller's Orb
    # Use a Lesser Eldritch Ember on an item
    # Use a Lesser Eldritch Ichor on an item
    # Roll 2 T1 affixes on an item after using an Orb of Alteration
    # Use an Orb of Annulment on an item
    # Obtain a T1 affix on an item after using an Orb of Augmentation
    # Obtain a rare item with 6 affixes after using an Orb of Chance
    # X-link an item after using an Orb of Fusing
    # Obtain a T1 affix on an item after using a Regal Orb
    # Obtain a better defense value on an item after using a Sacred Orb
    # Pull a Divination Card from a Stacked Deck

    ## Vaal Orb Crafting
    # Get a white socket on an item after using a Vaal Orb
    # Roll a Vaal implicit on an item after using a Vaal
    # Turn a Jewel into a corruption-exclusive Jewel after using a Vaal Orb
    # Turn a map into an 8 affix map after using a Vaal Orb
    # Obtain a 23% quality gem after using a Vaal Orb
    # Obtain a level 21 gem after using a Vaal Orb

    # Collect currency items
    # Complete vendor recipes
    # Complete encounters: Rogue Exiles, Monsters possessed by Tormented Spirits
    # Collect a rare abyss jewel of each type: Murderous Eye, Searching Eye, Hypnotic Eye, Ghastly Eye
    # Complete a Vaal side area
    # Defeat act bosses
    # Defeat gods
    # Complete the Abyssal Depths
    # Complete unIDed rare maps
    # Reach Level X
    # Defeat a breachlord
    # Level a gem to level X
    # Complete unique maps
    # Enter the Viridian Wildwood

    def game_objective_templates(self) -> List[GameObjectiveTemplate]:
        return [
            # Collect Loot
            GameObjectiveTemplate(
                label="Collect Xx CURRENCY_ITEM",
                data={
                    "X": (self.currency_item_range, 1),
                    "CURRENCY_ITEM": (self.currency_items, 1)
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=10,
            ),
            GameObjectiveTemplate(
                label="Collect 1x CURRENCY_ITEM",
                data={
                    "CURRENCY_ITEM": (self.currency_items_rare, 1)
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=1,
            ),
            GameObjectiveTemplate(
                label="Collect Xx FRAGMENT",
                data={
                    "X": (self.fragment_range, 1),
                    "FRAGMENT": (self.fragments, 1)
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=5,
            ),
            GameObjectiveTemplate(
                label="Collect Xx FRAGMENT",
                data={
                    "X": (self.fragment_high_count_range, 1),
                    "FRAGMENT": (self.fragments_high_count, 1)
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=2,
            ),
            GameObjectiveTemplate(
                label="Collect 1x FRAGMENT",
                data={
                    "FRAGMENT": (self.fragments_rare, 1)
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=1,
            ),
            GameObjectiveTemplate(
                label="Collect X Tattoos",
                data={
                    "X": (self.tattoo_total_range, 1),
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=1,
            ),
            GameObjectiveTemplate(
                label="Collect Xx TATTOO",
                data={
                    "X": (self.tattoo_range, 1),
                    "TATTOO": (self.tattoos, 1)
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=2,
            ),
            GameObjectiveTemplate(
                label="Collect 1x TATTOO",
                data={
                    "TATTOO": (self.tattoos_rare, 1)
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=1,
            ),
            GameObjectiveTemplate(
                label="Collect Xx OMEN",
                data={
                    "X": (self.omen_range, 1),
                    "OMEN": (self.omens, 1)
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Collect 1x OMEN",
                data={
                    "OMEN": (self.omens_rare, 1)
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=1,
            ),
            GameObjectiveTemplate(
                label="Collect a full set of DIVINATION_CARD divination cards",
                data={
                    "DIVINATION_CARD": (self.divination_cards, 1)
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=7,
            ),
            GameObjectiveTemplate(
                label="Collect a DIVINATION_CARD divination card",
                data={
                    "DIVINATION_CARD": (self.divination_cards_rare, 1)
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=1,
            ),
            GameObjectiveTemplate(
                label="Collect Xx OIL",
                data={
                    "X": (self.oil_range, 1),
                    "OIL": (self.oils, 1)
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=4,
            ),
            GameObjectiveTemplate(
                label="Collect Xx OIL",
                data={
                    "X": (self.oil_rare_range, 1),
                    "OIL": (self.oils_rare, 1)
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=1,
            ),
            GameObjectiveTemplate(
                label="Collect Xx INCUBATOR",
                data={
                    "X": (self.incubator_range, 1),
                    "INCUBATOR": (self.incubators, 1)
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=3,
            ),
            GameObjectiveTemplate(
                label="Collect X unique UNIQUE_ITEM_TYPE",
                data={
                    "X": (self.unique_item_type_range, 1),
                    "UNIQUE_ITEM_TYPE": (self.unique_item_types, 1)
                },
                is_time_consuming=True,
                is_difficult=False,
                weight=3,
            ),
        ]

    @staticmethod
    def ascendancies() -> List[str]:
        return [
            "Ascendant",
            "Assassin",
            "Berserker",
            "Champion",
            "Chieftain",
            "Deadeye",
            "Elementalist",
            "Gladiator",
            "Guardian",
            "Hierophant",
            "Inquisitor",
            "Juggernaut",
            "Necromancer",
            "Occultist",
            "Pathfinder",
            "Saboteur",
            "Slayer",
            "Trickster",
            "Warden",
        ]

    @staticmethod
    def ssf() -> List[str]:
        return ["No", "Yes"]

    @staticmethod
    def hc() -> List[str]:
        return ["No", "No", "No", "No", "Yes"]

    @staticmethod
    def currency_items() -> List[str]:
        return [
            "Abrasive Catalyst",
            "Accelerating Catalyst",
            "Ancient Orb",
            "Armourer's Scrap",
            "Astragali",
            "Blacksmith's Whetstone",
            "Blessed Orb",
            "Blessing of Esh",
            "Blessing of Tul",
            "Blessing of Uul-Netol",
            "Blessing of Xoph",
            "Blighted Scouting Report",
            "Burial Medallion",
            "Cartographer's Chisel",
            "Chromatic Orb",
            "Comprehensive Scouting Report",
            "Delirious Scouting Report",
            "Divine Orb",
            "Eldritch Chaos Orb",
            "Eldritch Exalted Orb",
            "Eldritch Orb of Annulment",
            "Engineer's Orb",
            "Enkindling Orb",
            "Exalted Orb",
            "Exceptional Eldritch Ember",
            "Exceptional Eldritch Ichor",
            "Exotic Coinage",
            "Explorer's Scouting Report",
            "Fertile Catalyst",
            "Fracturing Shard",
            "Gemcutter's Prism",
            "Glassblower's Bauble",
            "Grand Eldritch Ember",
            "Grand Eldritch Ichor",
            "Great Eldritch Ichor",
            "Greater Eldritch Ichor",
            "Harbinger's Orb",
            "Imbued Catalyst",
            "Influenced Scouting Report",
            "Instilling Orb",
            "Intrinsic Catalyst",
            "Jeweller's Orb",
            "Lesser Eldritch Ember",
            "Lesser Eldritch Ichor",
            "Maven's Chisel of Avarice",
            "Maven's Chisel of Divination",
            "Maven's Chisel of Procurement",
            "Maven's Chisel of Proliferation",
            "Maven's Chisel of Scarabs",
            "Noxious Catalyst",
            "Orb of Alchemy",
            "Orb of Alteration",
            "Orb of Annulment",
            "Orb of Augmentation",
            "Orb of Binding",
            "Orb of Chance",
            "Orb of Fusing",
            "Orb of Horizons",
            "Orb of Regret",
            "Orb of Scouring",
            "Orb of Unmaking",
            "Otherworldly Scouting Report",
            "Prismatic Catalyst",
            "Regal Orb",
            "Ritual Vessel",
            "Sacred Crystallised Lifeforce",
            "Sacred Orb",
            "Scrap Metal",
            "Singular Scouting Report",
            "Stacked Deck",
            "Tainted Armourer's Scrap",
            "Tainted Blacksmith's Whetstone",
            "Tainted Catalyst",
            "Tainted Chaos Orb",
            "Tainted Chromatic Orb",
            "Tainted Exalted Orb",
            "Tainted Jeweller's Orb",
            "Tainted Mythic Orb",
            "Tainted Orb of Fusing",
            "Tempering Catalyst",
            "Tempering Orb",
            "Turbulent Catalyst",
            "Unstable Catalyst",
            "Vaal Orb",
            "Vaal Scouting Report",
        ]

    @staticmethod
    def currency_item_range() -> range:
        return range(3, 16)

    @staticmethod
    def currency_items_rare() -> List[str]:
        return [
            "Awakener's Orb",
            "Blessing of Chayula",
            "Crusader's Exalted Orb",
            "Fracturing Orb",
            "Hinekora's Lock",
            "Hunter's Exalted Orb",
            "Mirror Shard",
            "Mirror of Kalandra",
            "Orb of Conflict",
            "Orb of Dominance",
            "Redeemer's Exalted Orb",
            "Reflecting Mist",
            "Tailoring Orb",
            "Tainted Divine Teardrop",
            "Veiled Orb",
            "Warlord's Exalted Orb",
        ]

    @staticmethod
    def fragments() -> List[str]:
        return [
            "Al-Hezmin's Crest",
            "Alva's Memory",
            "Awakening Fragment",
            "Baran's Crest",
            "Blazing Fragment",
            "Chayula's Breachstone",
            "Cosmic Fragment",
            "Crescent Splinter",
            "Decaying Fragment",
            "Dedication to the Goddess",
            "Devouring Fragment",
            "Divine Vessel",
            "Drox's Crest",
            "Einhar's Memory",
            "Esh's Breachstone",
            "Fragment of Constriction",
            "Fragment of Emptiness",
            "Fragment of Enslavement",
            "Fragment of Eradication",
            "Fragment of Knowledge",
            "Fragment of Purification",
            "Fragment of Shape",
            "Fragment of Terror",
            "Fragment of the Chimera",
            "Fragment of the Hydra",
            "Fragment of the Minotaur",
            "Fragment of the Phoenix",
            "Kirac's Memory",
            "Mortal Grief",
            "Mortal Hope",
            "Mortal Ignorance",
            "Mortal Rage",
            "Niko's Memory",
            "Offering to the Goddess",
            "Reality Fragment",
            "Sacred Blossom",
            "Sacrifice at Dawn",
            "Sacrifice at Dusk",
            "Sacrifice at Midnight",
            "Sacrifice at Noon",
            "Simulacrum",
            "Synthesising Fragment",
            "Timeless Eternal Emlbem",
            "Timeless Karui Emblem",
            "Timeless Maraketh Emblem",
            "Timeless Templar Emblem",
            "Timeless Vaal Emblem",
            "Tribute to the Goddess",
            "Tul's Breachstone",
            "Uul-Netol's Breachstone",
            "Veritania's Crest",
            "Xoph's Breachstone",
        ]

    @staticmethod
    def fragment_range() -> range:
        return range(1, 6)

    @staticmethod
    def fragments_high_count() -> List[str]:
        return [
            "Simulacrum Splinter",
            "Splinter of Chayula",
            "Splinter of Esh",
            "Splinter of Tul",
            "Splinter of Uul-Netol",
            "Splinter of Xoph",
            "Timeless Eternal Empire Splinter",
            "Timeless Karui Splinter",
            "Timeless Maraketh Splinter",
            "Timeless Templar Splinter",
            "Timeless Vaal Splinter",
        ]

    @staticmethod
    def fragment_high_count_range() -> range:
        return range(20, 100)

    @staticmethod
    def fragments_rare() -> List[str]:
        return [
            "An Audience With The King",
            "Gift to the Goddess",
            "The Maven's Writ",
            "Valdo's Puzzle Box",
            "Voidborn Reliquary Key",
        ]

    @staticmethod
    def tattoo_total_range() -> range:
        return range(10, 26)

    @staticmethod
    def tattoos() -> List[str]:
        return [
            "Tattoo of the Arohongui Moonwarden",
            "Tattoo of the Arohongui Scout",
            "Tattoo of the Arohongui Shaman",
            "Tattoo of the Arohongui Warmonger",
            "Tattoo of the Arohongui Warrior",
            "Tattoo of the Hinekora Deathwarden",
            "Tattoo of the Hinekora Shaman",
            "Tattoo of the Hinekora Storyteller",
            "Tattoo of the Hinekora Warmonger",
            "Tattoo of the Hinekora Warrior",
            "Tattoo of the Kitava Blood Drinker",
            "Tattoo of the Kitava Heart Eater",
            "Tattoo of the Kitava Rebel",
            "Tattoo of the Kitava Shaman",
            "Tattoo of the Kitava Warrior",
            "Tattoo of the Ngamahu Firewalker",
            "Tattoo of the Ngamahu Shaman",
            "Tattoo of the Ngamahu Warmonger",
            "Tattoo of the Ngamahu Warrior",
            "Tattoo of the Ngamahu Woodcarver",
            "Tattoo of the Ramako Archer",
            "Tattoo of the Ramako Fleetfoot",
            "Tattoo of the Ramako Scout",
            "Tattoo of the Ramako Shaman",
            "Tattoo of the Ramako Sniper",
            "Tattoo of the Rongokurai Brute",
            "Tattoo of the Rongokurai Goliath",
            "Tattoo of the Rongokurai Guard",
            "Tattoo of the Rongokurai Turtle",
            "Tattoo of the Rongokurai Warrior",
            "Tattoo of the Tasalio Bladedancer",
            "Tattoo of the Tasalio Scout",
            "Tattoo of the Tasalio Shaman",
            "Tattoo of the Tasalio Tideshifter",
            "Tattoo of the Tasalio Warrior",
            "Tattoo of the Tawhoa Herbalist",
            "Tattoo of the Tawhoa Naturalist",
            "Tattoo of the Tawhoa Scout",
            "Tattoo of the Tawhoa Shaman",
            "Tattoo of the Tawhoa Warrior",
            "Tattoo of the Tukohama Brawler",
            "Tattoo of the Tukohama Shaman",
            "Tattoo of the Tukohama Warcaller",
            "Tattoo of the Tukohama Warmonger",
            "Tattoo of the Tukohama Warrior",
            "Tattoo of the Valako Scout",
            "Tattoo of the Valako Shaman",
            "Tattoo of the Valako Shieldbearer",
            "Tattoo of the Valako Stormrider",
            "Tattoo of the Valako Warrior",
        ]

    @staticmethod
    def tattoo_range() -> range:
        return range(2, 11)

    @staticmethod
    def tattoos_rare() -> List[str]:
        return [
            "Journey Tattoo of the Body",
            "Journey Tattoo of the Mind",
            "Journey Tattoo of the Soul",
        ]

    @staticmethod
    def omens() -> List[str]:
        return [
            "Omen of Adrenaline",
            "Omen of Amelioration",
            "Omen of Blanching",
            "Omen of Brilliance",
            "Omen of Death's Door",
            "Omen of Death-dancing",
            "Omen of Refreshment",
            "Omen of Return",
            "Omen of the Jeweller",
            "Omen of the Soul Devourer",
        ]

    @staticmethod
    def omen_range() -> range:
        return range(2, 11)

    @staticmethod
    def omens_rare() -> List[str]:
        return [
            "Omen of Fortune",
            "Omen of Connections",
        ]

    @staticmethod
    def divination_cards() -> List[str]:
        return [
            "A Chilling Wind",
            "A Dab of Ink",
            "A Dusty Memory",
            "A Familiar Call",
            "A Fate Worse Than Death",
            "A Modest Request",
            "A Mother's Parting Gift",
            "A Note in the Wind",
            "A Sea of Blue",
            "A Stone Perfected",
            "Abandoned Wealth",
            "Acclimatisation",
            "Akil's Prophecy",
            "Alivia's Grace",
            "Alluring Bounty",
            "Alone in the Darkness",
            "Altered Perception",
            "Anarchy's Price",
            "Arrogance of the Vaal",
            "Assassin's Favour",
            "Assassin's Gift",
            "Astral Protection",
            "Atziri's Arsenal",
            "Audacity",
            "Auspicious Ambitions",
            "Azure Rage",
            "Azyran's Reward",
            "Baited Expectations",
            "Beauty Through Death",
            "Bijoux",
            "Blind Venture",
            "Boon of Justice",
            "Boon of the First Ones",
            "Boundless Realms",
            "Bowyer's Dream",
            "Broken Truce",
            "Brother's Gift",
            "Brother's Stash",
            "Brotherhood in Exile",
            "Brush, Paint and Palette",
            "Buried Treasure",
            "Burning Blood",
            "Call to the First Ones",
            "Cameria's Cut",
            "Cartographer's Delight",
            "Chaotic Disposition",
            "Checkmate",
            "Costly Curio",
            "Council of Cats",
            "Coveted Possession",
            "Cursed Words",
            "Dark Dreams",
            "Dark Temptation",
            "Deadly Joy",
            "Death",
            "Deathly Designs",
            "Dementophobia",
            "Demigod's Wager",
            "Desperate Crusade",
            "Destined to Crumble",
            "Dialla's Subjugation",
            "Disdain",
            "Doedre's Madness",
            "Doryani's Epiphany",
            "Draped in Dreams",
            "Duality",
            "Dying Anguish",
            "Dying Light",
            "Earth Drinker",
            "Echoes of Love",
            "Eldritch Perfection",
            "Emperor of Purity",
            "Emperor's Luck",
            "Endless Night",
            "Etched in Blood",
            "Eternal Bonds",
            "Ever-Changing",
            "Fateful Meeting",
            "Father's Love",
            "Forbidden Power",
            "Friendship",
            "From Bone to Ashes",
            "Further Invention",
            "Gemcutter's Mercy",
            "Gemcutter's Promise",
            "Gift of Asenath",
            "Gift of the Gemling Queen",
            "Glimmer of Hope",
            "Grave Knowledge",
            "Guardian's Challenge",
            "Harmony of Souls",
            "Haunting Shadows",
            "Her Mask",
            "Heterochromia",
            "Home",
            "Hope",
            "Hubris",
            "Humility",
            "Hunter's Resolve",
            "Hunter's Reward",
            "Immortal Resolve",
            "Imperial Legacy",
            "Jack in the Box",
            "Judging Voices",
            "Justified Ambition",
            "Lachrymal Necrosis",
            "Lantador's Lost Love",
            "Last Hope",
            "Left to Fate",
            "Lethean Temptation",
            "Light and Truth",
            "Lingering Remnants",
            "Lost Worlds",
            "Loyalty",
            "Lucky Connections",
            "Lucky Deck",
            "Lysah's Respite",
            "Man With Bear",
            "Matryoshka",
            "Mawr Blaidd",
            "Merciless Armament",
            "Might is Right",
            "Misery in Darkness",
            "Mitts",
            "More is Never Enough",
            "No Traces",
            "Nook's Crown",
            "Parasitic Passengers",
            "Peaceful Moments",
            "Perfection",
            "Poisoned Faith",
            "Prejudice",
            "Pride Before the Fall",
            "Pride of the First Ones",
            "Prometheus' Armoury",
            "Prosperity",
            "Rain Tempter",
            "Rain of Chaos",
            "Rats",
            "Rebirth and Renewal",
            "Rebirth",
            "Reckless Ambition",
            "Sambodhi's Vow",
            "Scholar of the Seas",
            "Shard of Fate",
            "Silence and Frost",
            "Society's Remorse",
            "Something Dark",
            "Struck by Lightning",
            "Temperance",
            "Terrible Secret of Space",
            "The Academic",
            "The Admirer",
            "The Adventuring Spirit",
            "The Aesthete",
            "The Archmage's Right Hand",
            "The Arena Champion",
            "The Army of Blood",
            "The Artist",
            "The Aspirant",
            "The Astromancer",
            "The Avenger",
            "The Awakened",
            "The Battle Born",
            "The Bear Woman",
            "The Beast",
            "The Betrayal",
            "The Bitter Blossom",
            "The Blazing Fire",
            "The Blessing of Moosh",
            "The Body",
            "The Bones",
            "The Brawny Battle Mage",
            "The Breach",
            "The Brittle Emperor",
            "The Cache",
            "The Cacophony",
            "The Calling",
            "The Card Sharp",
            "The Carrion Crow",
            "The Cartographer",
            "The Cataclysm",
            "The Catalyst",
            "The Catch",
            "The Celestial Justicar",
            "The Celestial Stone",
            "The Chains that Bind",
            "The Chosen",
            "The Coming Storm",
            "The Conduit",
            "The Craving",
            "The Cursed King",
            "The Dapper Prodigy",
            "The Dark Mage",
            "The Darkest Dream",
            "The Deal",
            "The Deceiver",
            "The Deep Ones",
            "The Demoness",
            "The Doppelganger",
            "The Dragon",
            "The Dreamer",
            "The Dreamland",
            "The Drunken Aristocrat",
            "The Dungeon Master",
            "The Easy Stroll",
            "The Eldritch Decay",
            "The Emptiness",
            "The Encroaching Darkness",
            "The Endurance",
            "The Enforcer",
            "The Enthusiasts",
            "The Escape",
            "The Eternal War",
            "The Ethereal",
            "The Explorer",
            "The Eye of Terror",
            "The Eye of the Dragon",
            "The Fathomless Depths",
            "The Feast",
            "The Finishing Touch",
            "The Fletcher",
            "The Flora's Gift",
            "The Fool",
            "The Forgotten Treasure",
            "The Formless Sea",
            "The Forsaken",
            "The Fortunate",
            "The Forward Gaze",
            "The Fox in the Brambles",
            "The Fox",
            "The Gambler",
            "The Garish Power",
            "The Gemcutter",
            "The Gentleman",
            "The Gladiator",
            "The Golden Era",
            "The Greatest Intentions",
            "The Hale Heart",
            "The Harvester",
            "The Hermit",
            "The Heroic Shot",
            "The Hive of Knowledge",
            "The Hoarder",
            "The Hook",
            "The Hunger",
            "The Incantation",
            "The Innocent",
            "The Inoculated",
            "The Insatiable",
            "The Inventor",
            "The Jester",
            "The Jeweller's Boon",
            "The Journalist",
            "The Journey",
            "The King's Blade",
            "The King's Heart",
            "The Landing",
            "The Last Supper",
            "The Leviathan",
            "The Lich",
            "The Life Thief",
            "The Lion",
            "The Long Con",
            "The Long Watch",
            "The Lord in Black",
            "The Lord of Celebration",
            "The Lover",
            "The Lunaris Priestess",
            "The Mad King",
            "The Magma Crab",
            "The Master Artisan",
            "The Mercenary",
            "The Messenger",
            "The Metalsmith's Gift",
            "The Mind's Eyes",
            "The Mountain",
            "The Nurse",
            "The Oath",
            "The Obscured",
            "The Offering",
            "The Offspring",
            "The Old Man",
            "The One That Got Away",
            "The One With All",
            "The Opulent",
            "The Pack Leader",
            "The Pact",
            "The Patient",
            "The Penitent",
            "The Poet",
            "The Polymath",
            "The Porcupine",
            "The Price of Loyalty",
            "The Price of Prescience",
            "The Price of Protection",
            "The Primordial",
            "The Prince of Darkness",
            "The Professor",
            "The Puzzle",
            "The Queen",
            "The Rabbit's Foot",
            "The Rabid Rhoa",
            "The Realm",
            "The Return of the Rat",
            "The Risk",
            "The Rite of Elements",
            "The Road to Power",
            "The Rusted Bard",
            "The Ruthless Ceinture",
            "The Sacrifice",
            "The Saint's Treasure",
            "The Scarred Meadow",
            "The Scavenger",
            "The Scholar",
            "The Scout",
            "The Seeker",
            "The Shepherd's Sandals",
            "The Shortcut",
            "The Side Quest",
            "The Sigil",
            "The Siren",
            "The Skeleton",
            "The Spark and the Flame",
            "The Spoiled Prince",
            "The Standoff",
            "The Stormcaller",
            "The Strategist",
            "The Summoner",
            "The Sun",
            "The Surgeon",
            "The Surveyor",
            "The Survivalist",
            "The Sword King's Salute",
            "The Thaumaturgist",
            "The Throne",
            "The Tinkerer's Table",
            "The Tireless Extractor",
            "The Tower",
            "The Traitor",
            "The Transformation",
            "The Trial",
            "The Tumbleweed",
            "The Twilight Moon",
            "The Twins",
            "The Tyrant",
            "The Undaunted",
            "The Undisputed",
            "The Unexpected Prize",
            "The Union",
            "The Valkyrie",
            "The Visionary",
            "The Void",
            "The Warden",
            "The Warlord",
            "The Watcher",
            "The Web",
            "The Wedding Gift",
            "The White Knight",
            "The Whiteout",
            "The Wilted Rose",
            "The Wind",
            "The Witch",
            "The Wolf",
            "The Wolf's Legacy",
            "The Wolf's Shadow",
            "The Wolven King's Bite",
            "The Wolverine",
            "The World Eater",
            "The Wrath",
            "The Wretched",
            "Thirst for Knowledge",
            "Three Faces in the Dark",
            "Three Voices",
            "Thunderous Skies",
            "Time-Lost Relic",
            "Toxic Tidings",
            "Tranquillity",
            "Treasure Hunter",
            "Triskaidekaphobia",
            "Turn the Other Cheek",
            "Unchained",
            "Vanity",
            "Vile Power",
            "Vinia's Token",
            "Void of the Elements",
            "Volatile Power",
            "Who Asked",
        ]

    @staticmethod
    def divination_cards_rare() -> List[str]:
        return [
            "Ambitious Obsession",
            "Avian Pursuit",
            "Broken Promises",
            "Chasing Risk",
            "Choking Guilt",
            "Darker Half",
            "Desecrated Virtue",
            "Divine Beauty",
            "Divine Justice",
            "Fire Of Unknown Origin",
            "House of Mirrors",
            "I See Brothers",
            "Imperfect Memories",
            "Keeper's Corruption",
            "Lonely Warrior",
            "Love Through Ice",
            "Luminous Trove",
            "Magnum Opus",
            "Remembrance",
            "Seven Years Bad Luck",
            "Succor of the Sinless",
            "The Apothecary",
            "The Cheater",
            "The Damned",
            "The Demon",
            "The Destination",
            "The Doctor",
            "The Dragon's Heart",
            "The Endless Darkness",
            "The Enlightened",
            "The Fiend",
            "The Fishmonger",
            "The Gulf",
            "The Immortal",
            "The Insane Cat",
            "The Last One Standing",
            "The Price of Devotion",
            "The Progeny of Lunaris",
            "The Samurai's Eye",
            "The Sephirot",
            "The Shieldbearer",
            "The Soul",
            "The Vast",
            "Unrequited Love",
            "Wealth and Power",
            "Winter's Embrace",
        ]

    @staticmethod
    def oils() -> List[str]:
        return [
            "Amber Oil",
            "Azure Oil",
            "Clear Oil",
            "Crimson Oil",
            "Indigo Oil",
            "Sepia Oil",
            "Teal Oil",
            "Verdant Oil",
            "Violet Oil",
        ]

    @staticmethod
    def oil_range() -> range:
        return range(5, 21)

    @staticmethod
    def oils_rare() -> List[str]:
        return [
            "Black Oil",
            "Golden Oil",
            "Opalescent Oil",
            "Prismatic Oil",
            "Reflective Oil",
            "Silver Oil",
            "Tainted Oil",
        ]

    @staticmethod
    def oil_rare_range() -> range:
        return range(1, 4)

    @staticmethod
    def incubators() -> List[str]:
        return [
            "Abyssal Incubator",
            "Blighted Incubator",
            "Cartographer's Incubator",
            "Celestial Armoursmith's Incubator",
            "Celestial Blacksmith's Incubator",
            "Celestial Jeweller's Incubator",
            "Diviner's Incubator",
            "Foreboding Incubator",
            "Fossilised Incubator",
            "Fragmented Incubator",
            "Gemcutter's Incubator",
            "Geomancer's Incubator",
            "Infused Incubator",
            "Kalguuran Incubator",
            "Maddening Incubator",
            "Mysterious Incubator",
            "Obscured Incubator",
            "Ornate Incubator",
            "Otherworldly Incubator",
            "Primal Incubator",
            "Singular Incubator",
            "Skittering Incubator",
            "Thaumaturge's Incubator",
        ]

    @staticmethod
    def incubator_range() -> range:
        return range(3, 11)

    @staticmethod
    def unique_item_types() -> List[str]:
        return [
            "Amulets",
            "Axes",
            "Belts",
            "Body Armours",
            "Boots",
            "Bows",
            "Claws",
            "Daggers",
            "Flasks",
            "Gloves",
            "Helmets",
            "Jewels",
            "Maces",
            "Maps",
            "Quivers",
            "Rings",
            "Sceptres",
            "Shields",
            "Staves",
            "Swords",
            "Wands",
        ]

    @staticmethod
    def unique_item_type_range() -> range:
        return range(2, 6)

    @staticmethod
    def unique_items() -> List[str]:
        return [
            # Amulets
            "Araku Tiki",
            "Ashes of the Stars",
            "Astramentis",
            "Atziri's Foible",
            "Aul's Uprising",
            "Badge of the Brotherhood",
            "Blightwell",
            "Blood of Corruption",
            "Bloodgrip",
            "Bloodsoaked Medallion",
            "Carnage Heart",
            "Daresso's Salute",
            "Doedre's Tongue",
            "Eternal Damnation",
            "Extractor Mentis",
            "Eye of Chayula",
            "Eye of Innocence",
            "Eyes of the Greatwolf",
            "Fury Valve",
            "Gloomfang",
            "Hinekora's Sight",
            "Hyrri's Truth",
            "Ikiaho's Promise",
            "Impresence",
            "Karui Ward",
            "Leadership's Price",
            "Maligaro's Cruelty",
            "Marylene's Fallacy",
            "Natural Hierarchy",
            "Night's Hold",
            "Perquil's Toe",
            "Rashkaldor's Patience",
            "Replica Atziri's Foible",
            "Replica Badge of the Brotherhood",
            "Replica Dragonfang's Flight",
            "Replica Hinekora's Sight",
            "Replica Hyrri's Truth",
            "Replica Karui Ward",
            "Replica Winterheart",
            "Retaliation Charm",
            "Rigwald's Curse",
            "Sacrificial Heart",
            "Shaper's Seed",
            "Sidhebreath",
            "Solstice Vigil",
            "Star of Wraeclast",
            "Stone of Lazhwar",
            "Tainted Pact",
            "Tavukai",
            "Tear of Purity",
            "The Anvil",
            "The Aylardex",
            "The Ephemeral Bond",
            "The Eternal Struggle",
            "The Felbog Fang",
            "The Halcyon",
            "The Ignomon",
            "The Jinxed Juju",
            "The Pandemonius",
            "The Primordial Chain",
            "The Untouched Soul",
            "Ungil's Harmony",
            "Victario's Acuity",
            "Voll's Devotion",
            "Warped Timepiece",
            "Willowgift",
            "Winterheart",
            "Xoph's Blood",
            "Xoph's Heart",
            "Zerphi's Heart",
            # Belts
            "Arn's Anguish",
            "Ascent From Flesh",
            "Auxium",
            "Bated Breath",
            "Bear's Girdle",
            "Belt of the Deceiver",
            "Bisco's Leash",
            "Bound Fate",
            "Ceinture of Benevolence",
            "Chain of Endurance",
            "Chains of Emancipation",
            "Coward's Chains",
            "Coward's Legacy",
            "Cyclopean Coil",
            "Darkness Enthroned",
            "Doryani's Invitation",
            "Dyadian Dawn",
            "Faminebind",
            "Feastbind",
            "Gluttony",
            "Graven's Secret",
            "Hyperboreus",
            "Immortal Flesh",
            "Kaom's Binding",
            "Leash of Oblation",
            "Maligaro's Restraint",
            "Meginord's Girdle",
            "Mother's Embrace",
            "Nevalius Inheritance",
            "Olesya's Delight",
            "Perandus Blazon",
            "Perseverance",
            "Prismweave",
            "Pyroshock Clasp",
            "Replica Prismweave",
            "Replica Siegebreaker",
            "Replica Soul Tether",
            "Ryslatha's Coil",
            "Siegebreaker",
            "Soul Tether",
            "Soulthirst",
            "String of Servitude",
            "Sunblast",
            "Survivor's Guilt",
            "The Burden of Truth",
            "The Druggery",
            "The Flow Untethered",
            "The Magnate",
            "The Retch",
            "The Tides of Time",
            "Umbilicus Immortalis",
            "Wurm's Molt",
            # Rings
            "Ahkeli's Meadow",
            "Ahkeli's Mountain",
            "Ahkeli's Valley",
            "Andvarius",
            "Angler's Plait",
            "Astral Projector",
            "Berek's Grip",
            "Berek's Pass",
            "Berek's Respite",
            "Blackflame",
            "Blackheart",
            "Brinerot Mark",
            "Call of the Brotherhood",
            "Call of the Void",
            "Circle of Ambition",
            "Circle of Anguish",
            "Circle of Fear",
            "Circle of Guilt",
            "Circle of Nostalgia",
            "Circle of Regret",
            "Death Rush",
            "Doedre's Damning",
            "Dream Fragments",
            "Emberwake",
            "Essence Worm",
            "Fated End",
            "Gifts from Above",
            "Grattus Signet",
            "Heartbound Loop",
            "Icefang Orbit",
            "Ixchel's Temptation",
            "Kaom's Sign",
            "Kikazaru",
            "Le Heup of All",
            "Lori's Lantern",
            "Malachai's Artifice",
            "Mark of Submission",
            "Mark of the Elder",
            "Mark of the Shaper",
            "Ming's Heart",
            "Mokou's Embrace",
            "Mutewind Seal",
            "Ngamahu's Sign",
            "Perandus Signet",
            "Polaric Devastation",
            "Praxis",
            "Profane Proxy",
            "Putembo's Meadow",
            "Putembo's Valley",
            "Pyre",
            "Redblade Band",
            "Replica Doedre's Damning",
            "Replica Emberwake",
            "Replica Malachai's Artifice",
            "Replica Tasalio's Sign",
            "Replica Voideye",
            "Rigwald's Crest",
            "Romira's Banquet",
            "Rotblood Promise",
            "Shavronne's Revelation",
            "Sibyl's Lament",
            "Snakepit",
            "Soulbound",
            "Storm Secret",
            "Stormfire",
            "Tasalio's Sign",
            "Tawhanuku's Timing",
            "The Hateful Accuser",
            "The Highwayman",
            "The Hungry Loop",
            "The Pariah",
            "The Queller of Minds",
            "The Selfish Shepherd",
            "The Taming",
            "The Warden's Brand",
            "Thief's Torment",
            "Timeclasp",
            "Triumvirate Authority",
            "Uzaza's Meadow",
            "Uzaza's Mountain",
            "Valako's Sign",
            "Valyrium",
            "Venopuncture",
            "Ventor's Gamble",
            "Vivinsect",
            "Voideye",
            "Warrior's Legacy",
            "Winterweave",
            # Body Armours
            "Ambu's Charge",
            "Ashrend",
            "Atziri's Splendour",
            "Belly of the Beast",
            "Bloodbond",
            "Blunderbore",
            "Bramblejack",
            "Briskwrap",
            "Bronn's Lithe",
            "Carcass Jack",
            "Chains of Command",
            "Cherrubim's Maleficence",
            "Cloak of Defiance",
            "Cloak of Flame",
            "Cloak of Tawm'r Isley",
            "Cospri's Will",
            "Craiceann's Carapace",
            "Daresso's Defiance",
            "Death's Oath",
            "Dendrobate",
            "Doedre's Skin",
            "Doppelgänger Guise",
            "Doryani's Prototype",
            "Expedition's End",
            "Farrul's Fur",
            "Fenumus' Shroud",
            "Fleshcrafter",
            "Foxshade",
            "Garb of the Ephemeral",
            "Geofri's Sanctuary",
            "Ghostwrithe",
            "Greed's Embrace",
            "Gruthkul's Pelt",
            "Hyrri's Ire",
            "Icetomb",
            "Incandescent Heart",
            "Infernal Mantle",
            "Inpulsa's Broken Heart",
            "Kaom's Heart",
            "Kingsguard",
            "Kintsugi",
            "Lightbane Raiment",
            "Lightning Coil",
            "Lioneye's Vision",
            "Loreweave",
            "Perfidy",
            "Pragmatism",
            "Queen of the Forest",
            "Replica Ambu's Charge",
            "Replica Covenant",
            "Replica Eternity Shroud",
            "Replica Kaom's Heart",
            "Replica Loreweave",
            "Replica Perfect Form",
            "Replica Restless Ward",
            "Saqawal's Nest",
            "Shadowstitch",
            "Shavronne's Wrappings",
            "Shroud of the Lightless",
            "Skin of the Lords",
            "Skin of the Loyal",
            "Solaris Lorica",
            "Soul Mantle",
            "Tabula Rasa",
            "The Admiral",
            "The Beast Fur Shawl",
            "The Brass Dome",
            "The Coming Calamity",
            "The Covenant",
            "The Eternity Shroud",
            "The Fourth Vow",
            "The Iron Fortress",
            "The Ivory Tower",
            "The Perfect Form",
            "The Queen's Hunger",
            "The Rat Cage",
            "The Restless Ward",
            "The Snowblind Grace",
            "Thousand Ribbons",
            "Tinkerskin",
            "Utula's Hunger",
            "Victario's Influence",
            "Vis Mortis",
            "Voll's Protector",
            "Yriel's Fostering",
            "Zahndethus' Cassock",
            # Boots
            "Abberath's Hooves",
            "Alberon's Warpath",
            "Annihilation's Approach",
            "Atziri's Step",
            "Beacon of Madness",
            "Bones of Ullr",
            "Brinerot Whalers",
            "Bubonic Trail",
            "Corpsewalker",
            "Craiceann's Tracks",
            "Dance of the Offered",
            "Darkray Vectors",
            "Dawnstrider",
            "Deerstalker",
            "Doryani's Delusion",
            "Dusktoe",
            "Farrul's Chase",
            "Fenumus' Spinnerets",
            "Gamblesprint",
            "Gang's Momentum",
            "Garukhan's Flight",
            "Goldwyrm",
            "Inextricable Fate",
            "Inya's Epiphany",
            "Kahuturoa's Certainty",
            "Kaom's Roots",
            "Legacy of Fury",
            "Lioneye's Paws",
            "March of the Legion",
            "Mutewind Whispersteps",
            "Nomic's Storm",
            "Olroth's Charge",
            "Omeyocan",
            "Orbala's Stand",
            "Rainbowstride",
            "Redblade Tramplers",
            "Replica Bones of Ullr",
            "Replica Inya's Epiphany",
            "Replica Lioneye's Paws",
            "Replica Red Trail",
            "Replica Stampede",
            "Replica Three-step Assault",
            "Replica Voidwalker",
            "Saqawal's Talons",
            "Seven-League Step",
            "Shavronne's Pace",
            "Sin Trek",
            "Skyforth",
            "Steppan Eard",
            "Stormcharger",
            "Sundance",
            "Temptation Step",
            "The Blood Dance",
            "The Infinite Pursuit",
            "The Red Trail",
            "The Stampede",
            "The Tempest Rising",
            "Three-step Assault",
            "Torchoak Step",
            "Veruso's Ambition",
            "Victario's Flight",
            "Voidwalker",
            "Vorana's March",
            "Wake of Destruction",
            "Wanderlust",
            "Windscream",
            "Wondertrap",
            # Gloves
            "Abhorrent Interrogation",
            "Admiral's Arrogance",
            "Algor Mortis",
            "Allelopathy",
            "Architect's Hand",
            "Asenath's Gentle Touch",
            "Atziri's Acuity",
            "Aukuna's Will",
            "Aurseize",
            "Black Zenith",
            "Blasphemer's Grasp",
            "Breathstealer",
            "Ceaseless Feast",
            "Command of the Pit",
            "Craiceann's Pincers",
            "Demon Stitcher",
            "Doedre's Tenure",
            "Doryani's Fist",
            "Empire's Grasp",
            "Entropic Devastation",
            "Facebreaker",
            "Farrul's Pounce",
            "Fenumus' Weave",
            "Flesh and Spirit",
            "Giantsbane",
            "Gravebind",
            "Great Old One's Tentacles",
            "Grip of the Council",
            "Haemophilia",
            "Hand of the Fervent",
            "Hands of the High Templar",
            "Hrimsorrow",
            "Kalisa's Grace",
            "Kaom's Spirit",
            "Lochtonial Caress",
            "Machina Mitts",
            "Malachai's Mark",
            "Maligaro's Virtuosity",
            "Medved's Challenge",
            "Meginord's Vise",
            "Mercenary's Lot",
            "Nightgrip",
            "Null and Void",
            "Offering to the Serpent",
            "Ondar's Clasp",
            "Oskarm",
            "Painseeker",
            "Repentance",
            "Replica Allelopathy",
            "Replica Atziri's Acuity",
            "Replica Grip of the Council",
            "Replica Kalisa's Grace",
            "Replica Volkuur's Guidance",
            "Sadima's Touch",
            "Saqawal's Winds",
            "Shackles of the Wretched",
            "Shadows and Dust",
            "Shaper's Touch",
            "Slitherpinch",
            "Snakebite",
            "Southbound",
            "Storm's Gift",
            "Stormseeker",
            "Surgebinders",
            "Tanu Ahi",
            "The Celestial Brace",
            "The Embalmer",
            "The Hand of Phrecia",
            "Thunderfist",
            "Tombfist",
            "Triad Grip",
            "Vaal Caress",
            "Veruso's Battering Rams",
            "Vixen's Entrapment",
            "Voidbringer",
            "Volkuur's Guidance",
            "Winds of Change",
            "Wyrmsign",
            # Helmets
            "Abyssus",
            "Ahn's Contempt",
            "Akoya's Gaze",
            "Alpha's Howl",
            "Ancient Skull",
            "Asenath's Mark",
            "Assailum",
            "Black Sun Crest",
            "Blood Price",
            "Cadigan's Crown",
            "Chitus' Apex",
            "Cowl of the Ceraunophile",
            "Cowl of the Cryophile",
            "Cowl of the Thermophile",
            "Craiceann's Chitin",
            "Crown of Eyes",
            "Crown of the Inward Eye",
            "Crown of the Pale King",
            "Crown of Thorns",
            "Curtain Call",
            "Deidbell",
            "Devoto's Devotion",
            "Doedre's Scorn",
            "Eber's Unification",
            "Echoes of Creation",
            "Elevore",
            "Eye of Malice",
            "Ezomyte Peak",
            "Fairgraves' Tricorne",
            "Farrul's Bite",
            "Fenumus' Toxins",
            "Flamesight",
            "Forbidden Shako",
            "Fractal Thoughts",
            "Galesight",
            "Geofri's Crest",
            "Glimpse of Chaos",
            "Goldrim",
            "Gorgon's Gaze",
            "Hale Negator",
            "Heatshiver",
            "Heretic's Veil",
            "Honourhome",
            "Hrimnor's Resolve",
            "Indigon",
            "Kaom's Command",
            "Kitava's Thirst",
            "Leer Cast",
            "Lightpoacher",
            "Malachai's Simula",
            "Malachai's Vision",
            "Mark of the Red Covenant",
            "Mask of the Spirit Drinker",
            "Mask of the Tribunal",
            "Maw of Conquest",
            "Maw of Mischief",
            "Memory Vault",
            "Mind of the Council",
            "Mindspiral",
            "Obscurantis",
            "Plume of Pursuit",
            "Rat's Nest",
            "Ravenous Passion",
            "Replica Abyssus",
            "Replica Alpha's Howl",
            "Replica Heatshiver",
            "Replica Leer Cast",
            "Replica Veil of the Night",
            "Rime Gaze",
            "Saqawal's Flock",
            "Scold's Bridle",
            "Skullhead",
            "Speaker's Wreath",
            "Starkonja's Head",
            "Sudden Dawn",
            "The Baron",
            "The Brine Crown",
            "The Bringer of Rain",
            "The Broken Crown",
            "The Devourer of Minds",
            "The Devouring Diadem",
            "The Fledgling",
            "The Formless Flame",
            "The Formless Inferno",
            "The Gull",
            "The Tempest's Binding",
            "The Tempest's Liberation",
            "The Three Dragons",
            "The Trickster's Smile",
            "The Vertex",
            "Thrillsteel",
            "Thundersight",
            "Usurper's Penance",
            "Veil of the Night",
            "Viridi's Veil",
            "Voll's Vision",
            "Willclash",
            "Wilma's Requital",
            "Wraithlord",
            "Wreath of Phrecia",
            "Ylfeban's Trickery",
            # Shields
            "Aegis Aurora",
            "Ahn's Heritage",
            "Apep's Slumber",
            "Bitterbind Point",
            "Brinerot Flag",
            "Broken Faith",
            "Chalice of Horrors",
            "Chernobog's Pillar",
            "Crest of Perandus",
            "Daresso's Courage",
            "Dawnbreaker",
            "Emperor's Vigilance",
            "Esh's Mirror",
            "Esh's Visage",
            "Font of Thunder",
            "Great Old One's Ward",
            "Invictus Solaris",
            "Jaws of Agony",
            "Kaltenhalt",
            "Kiloava's Bluster",
            "Kongming's Stratagem",
            "Leper's Alms",
            "Light of Lunaris",
            "Lioneye's Remorse",
            "Lycosidae",
            "Magna Eclipsis",
            "Mahuxotl's Machination",
            "Malachai's Loop",
            "Maligaro's Lens",
            "Manastorm",
            "Matua Tupuna",
            "Mistwall",
            "Mutewind Pennant",
            "Perepiteia",
            "Prism Guardian",
            "Qotra's Regulator",
            "Rathpith Globe",
            "Redblade Banner",
            "Replica Mistwall",
            "Replica Victario's Charity",
            "Rise of the Phoenix",
            "Saffell's Frame",
            "Sentari's Answer",
            "Shattershard",
            "Springleaf",
            "The Anticipation",
            "The Deep One's Hide",
            "The Eternal Apple",
            "The Flawed Refuge",
            "The Ghastly Theatre",
            "The Immortal Will",
            "The Oppressor",
            "The Surrender",
            "The Unshattered Will",
            "Thousand Teeth Temu",
            "Titucius' Span",
            "Trolltimber Spire",
            "Tukohama's Fortress",
            "Unyielding Flame",
            "Victario's Charity",
            "Vix Lunaris",
            "Wheel of the Stormsail",
            "Zeel's Amplifier",
            # Quivers
            "Ahuana's Bite",
            "Asphyxia's Wrath",
            "Blackgleam",
            "Craghead",
            "Drillneck",
            "Hyrri's Bite",
            "Maloney's Mechanism",
            "Maloney's Nightfall",
            "Rearguard",
            "Replica Maloney's Mechanism",
            "Replica Soul Strike",
            "Rigwald's Quills",
            "Saemus' Gift",
            "Scorpion's Call",
            "Skirmish",
            "Soul Strike",
            "Steelworm",
            "The Fracturing Spinner",
            "The Poised Prism",
            "The Shattered Divinity",
            "Voidfletcher",
            # Axes
            "Actum",
            "Atziri's Disfavour",
            "Debeon's Dirge",
            "Dreadarc",
            "Dyadus",
            "Hezmana's Bloodlust",
            "Jack, the Axe",
            "Kaom's Primacy",
            "Kitava's Feast",
            "Limbsplit",
            "Moonbender's Wing",
            "Ngamahu's Flame",
            "Reaper's Pursuit",
            "Relentless Fury",
            "Replica Harvest",
            "Replica Wings of Entropy",
            "Rigwald's Savagery",
            "Sinvicta's Mettle",
            "The Blood Reaper",
            "The Harvest",
            "The Screaming Eagle",
            "Uul-Netol's Kiss",
            "Wideswing",
            "Wings of Entropy",
            # Bows
            "Arborix",
            "Chin Sol",
            "Darkscorn",
            "Death's Harp",
            "Doomfletch",
            "Hopeshredder",
            "Infractem",
            "Iron Commander",
            "Null's Inclination",
            "Nuro's Harp",
            "Quill Rain",
            "Reach of the Council",
            "Replica Infractem",
            "Replica Iron Commander",
            "Replica Quill Rain",
            "Replica Windripper",
            "Roth's Reach",
            "Silverbranch",
            "Slivertongue",
            "Storm Cloud",
            "The Crimson Storm",
            "The Gluttonous Tide",
            "Widowhail",
            "Windripper",
            "Xoph's Inception",
            "Xoph's Nurture",
            # Claws
            "Advancing Fortress",
            "Al Dhih",
            "Allure",
            "Cybil's Paw",
            "Hand of Thought and Motion",
            "Hand of Wisdom and Action",
            "Last Resort",
            "Law of the Wilds",
            "Mortem Morsu",
            "Ornament of the East",
            "Replica Advancing Fortress",
            "Replica Allure",
            "Replica Last Resort",
            "Rive",
            "The Scourge",
            "The Wasp Nest",
            "Touch of Anguish",
            "Wildslash",
            # Maces
            "Brain Rattler",
            "Brightbeak",
            "Callinellus Malleus",
            "Cameria's Avarice",
            "Cameria's Maul",
            "Chober Chaber",
            "Clayshaper",
            "Flesh-Eater",
            "Frostbreath",
            "Geofri's Baptism",
            "Gorebreaker",
            "Hrimnor's Hymn",
            "Jorrhast's Blacksteel",
            "Kongor's Undying Rage",
            "Lavianga's Wisdom",
            "Mjölner",
            "Nebuloch",
            "Quecholli",
            "Replica Frostbreath",
            "Replica Trypanon",
            "Serle's Masterwork",
            "Tawhoa's Felling",
            "Tidebreaker",
            "Trypanon",
            "Voidhome",
            # Sceptres
            "Augyre",
            "Axiom Perpetuum",
            "Balefire",
            "Bitterdream",
            "Breath of the Council",
            "Brutus' Lead Sprinkler",
            "Cerberus Limb",
            "Death's Hand",
            "Doon Cuebiyari",
            "Doryani's Catalyst",
            "Earendel's Embrace",
            "Maata's Teaching",
            "Mon'tregul's Grasp",
            "Nebulis",
            "Nycta's Lantern",
            "Replica Bitterdream",
            "Replica Earendel's Embrace",
            "Replica Nebulis",
            "Sign of the Sin Eater",
            "Singularity",
            "The Black Cane",
            "The Supreme Truth",
            "Yaomac's Accord",
            # Staves
            "Agnerod East",
            "Agnerod North",
            "Agnerod South",
            "Agnerod West",
            "Atziri's Rule",
            "Cane of Kulemak",
            "Cane of Unravelling",
            "Disintegrator",
            "Dying Breath",
            "Femurs of the Saints",
            "Fencoil",
            "Hegemony's Era",
            "Martyr of Innocence",
            "Pillar of the Caged God",
            "Realmshaper",
            "Replica Blood Thorn",
            "Replica Fencoil",
            "Sire of Shards",
            "Soulwrest",
            "Taryn's Shiver",
            "The Annihilating Light",
            "The Blood Thorn",
            "The Burden of Shadows",
            "The Enmity Divine",
            "The Fulcrum",
            "The Grey Spire",
            "The Searing Touch",
            "The Stormheart",
            "The Whispering Ice",
            "The Yielding Mortality",
            "Tremor Rod",
            "Witchhunter's Judgment",
            "Xirgil's Crank",
            # Swords
            "Ahn's Might",
            "Aurumvorax",
            "Beltimber Blade",
            "Cospri's Malice",
            "Daresso's Passion",
            "Doomsower",
            "Dreamfeather",
            "Edge of Madness",
            "Ephemeral Edge",
            "Ewar's Mirage",
            "Fidelitas' Spike",
            "Grelwood Shank",
            "Hiltless",
            "Hyaon's Fury",
            "Ichimonji",
            "Innsbury Edge",
            "Kondo's Pride",
            "Lakishu's Blade",
            "Nametaker",
            "Oni-Goroshi",
            "Oro's Sacrifice",
            "Paradoxica",
            "Prismatic Eclipse",
            "Queen's Decree",
            "Razor of the Seventh Sun",
            "Rebuke of the Vaal",
            "Redbeak",
            "Replica Dreamfeather",
            "Replica Innsbury Edge",
            "Replica Oro's Sacrifice",
            "Replica Paradoxica",
            "Replica Tempestuous Steel",
            "Rigwald's Charge",
            "Rigwald's Command",
            "Scaeva",
            "Severed in Sleep",
            "Shiversting",
            "Story of the Vaal",
            "Terminus Est",
            "The Dancing Dervish",
            "The Goddess Bound",
            "The Goddess Scorned",
            "The Iron Mass",
            "The Living Blade",
            "The Princess",
            "The Rippling Thoughts",
            "The Saviour",
            "The Surging Thoughts",
            "The Tempestuous Steel",
            "United in Dream",
            "Varunastra",
            # Wands
            "Abberath's Horn",
            "Apep's Rage",
            "Ashcaller",
            "Eclipse Solaris",
            "Lifesprig",
            "Midnight Bargain",
            "Moonsorrow",
            "Obliteration",
            "Piscator's Vigil",
            "Relic of the Pact",
            "Replica Midnight Bargain",
            "Replica Tulfall",
            "Replica Twyzel",
            "Reverberation Rod",
            "Shade of Solaris",
            "Shimmeron",
            "Storm Prison",
            "The Poet's Pen",
            "Tulborn",
            "Tulfall",
            "Twyzel",
            # Flasks
            "Atziri's Promise",
            "Blood of the Karui",
            "Cinderswallow Urn",
            "Coralito's Signature",
            "Coruscating Elixir",
            "Divination Distillate",
            "Doedre's Elixir",
            "Forbidden Taste",
            "Kiara's Determination",
            "Lavianga's Spirit",
            "Lion's Roar",
            "Replica Lavianga's Spirit",
            "Replica Rumi's Concoction",
            "Replica Sorrow of the Divine",
            "Replica Witchfire Brew",
            "Rotgut",
            "Rumi's Concoction",
            "Sin's Rebirth",
            "Soul Catcher",
            "Soul Ripper",
            "Taste of Hate",
            "The Overflowing Chalice",
            "The Sorrow of the Divine",
            "The Wise Oak",
            "The Writhing Jar",
            "Vessel of Vinktar",
            "Vorana's Preparation",
            "Witchfire Brew",
            "Zerphi's Last Breath",
            # Jewels
            "Apex Mode",
            "Atziri's Reign",
            "Bloodnotch",
            "Brutal Restraint",
            "Brute Force Solution",
            "Calamitous Visions",
            "Careful Planning",
            "Chill of Corruption",
            "Combat Focus",
            "Dead Reckoning",
            "Dissolution of the Flesh",
            "Efficient Training",
            "Elegant Hubris",
            "Emperor's Mastery",
            "Emperor's Wit",
            "Energised Armour",
            "Energy From Within",
            "Fertile Mind",
            "Fevered Mind",
            "Firesong",
            "Fluid Motion",
            "Forbidden Flame",
            "Forbidden Flesh",
            "Fortress Covenant",
            "Fragility",
            "Glorious Vanity",
            "Grand Spectrum",
            "Healthy Mind",
            "Hidden Potential",
            "Immutable Force",
            "Impossible Escape",
            "Inertia",
            "Inspired Learning",
            "Intuitive Leap",
            "Kitava's Teachings",
            "Kurgal's Gaze",
            "Lethal Pride",
            "Lioneye's Fall",
            "Megalomaniac",
            "Melding of the Flesh",
            "Might of the Meek",
            "Militant Faith",
            "Nadir Mode",
            "Natural Affinity",
            "One With Nothing",
            "Pacifism",
            "Powerlessness",
            "Primordial Eminence",
            "Primordial Harmony",
            "Primordial Might",
            "Pure Talent",
            "Quickening Covenant",
            "Rain of Splinters",
            "Reckless Defence",
            "Replica Primordial Might",
            "Replica Reckless Defence",
            "Seething Fury",
            "Self-Flagellation",
            "Split Personality",
            "Tecrod's Gaze",
            "Tempered Flesh",
            "Tempered Mind",
            "Tempered Spirit",
            "The Adorned",
            "The Anima Stone",
            "The Balance of Terror",
            "The Blue Dream",
            "The Blue Nightmare",
            "The Front Line",
            "The Golden Rule",
            "The Green Dream",
            "The Interrogation",
            "The Light of Meaning",
            "The Red Dream",
            "The Siege",
            "Thread of Hope",
            "To Dust",
            "Transcendent Flesh",
            "Transcendent Mind",
            "Transcendent Spirit",
            "Ulaman's Gaze",
            "Unending Hunger",
            "Watcher's Eye",
            "Witchbane",
        ]

    @staticmethod
    def unique_items_rare() -> List[str]:
        return [
            # Amulets
            "Choir of the Storm",
            "Crystallised Omniscience",
            "Defiance of Destiny",
            "Presence of Chayula",
            "Stranglegasp",
            "The Utmost",
            "Uul-Netol's Vow",
            "Voice of the Storm",
            "Yoke of Suffering",
            # Belts
            "Headhunter",
            "Mageblood",
            "Replica Bated Breath",
            "Replica Headhunter",
            "The Torrent's Reclamation",
            "Ynda's Stand",
            # Rings
            "Anathema",
            "Kalandra's Touch",
            "Nimis",
            "Original Sin",
            "Precursor's Emblem",
            "Putembo's Mountain",
            "Uzaza's Valley",
            # Body Armours
            "Dialla's Malefaction",
            "Replica Farrul's Fur",
            "Replica Hyrri's Ire",
            "Replica Shroud of the Lightless",
            "Sporeguard",
            "Stasis Prison",
            "The Apostate",
            # Boots
            "Death's Door",
            "Ralakesh's Impatience",
            "Replica Alberon's Warpath",
            # Gloves
            "Hateforge",
            "Slavedriver's Hand",
            "Soul Ascension",
            # Helmets
            "Crest of Desire",
            "Crown of the Tyrant",
            "Faithguard",
            "Mask of the Stitched Demon",
            "Sandstorm Visage",
            # Shields
            "Apep's Supremacy",
            "Atziri's Reflection",
            "Replica Tukohama's Fortress",
            "Svalinn",
            "The Squire",
            # Quivers
            # Axes
            "Kingmaker",
            "Soul Taker",
            "Uul-Netol's Embrace",
            # Bows
            "Lioneye's Glare",
            "Voltaxic Rift",
            # Claws
            "Bloodseeker",
            "Essentia Sanguis",
            # Maces
            "Marohi Erqi",
            "Replica Kongor's Undying Rage",
            # Sceptres
            "The Dark Seer",
            # Staves
            "Duskdawn",
            "Pledge of Hands",
            "Replica Duskdawn",
            "The Winds of Fate",
            # Swords
            "Echoforge",
            "Fate of the Vaal",
            "Rakiata's Dance",
            "Starforge",
            "Voidforge",
            # Wands
            "Grace of the Goddess",
            "Void Battery",
            # Flasks
            "Bottled Faith",
            "Dying Sun",
            "Elixir of the Unbroken Circle",
            "Olroth's Resolve",
            "Oriath's End",
            "Progenesis",
            "Starlight Chalice",
            # Jewels
            "Amanamu's Gaze",
            "Ancestral Vision",
            "Emperor's Might",
            "Rational Doctrine",
            "Stormshroud",
            "Sublime Vision",
            "The Green Nightmare",
            "The Red Nightmare",
            "Unnatural Instinct",
            "Voices",
        ]

    # Unique Relics
    # Unique Maps


# Archipelago Options
@dataclass
class PathofExileArchipelagoOptions:
    pass
