import os

a = """ReCastle (1F Ca) - G 0 (Black): Ditto (Black)
AbShrine - G 0 (Black): Ditto (Black)
ViRoad (7F C) - G 0 (Black): Blissey (Black)
ViRoad (7F C) - RG 3 (Black): Regigigas (Black)
Dyard (R) - DG 2 (Black): Azumarill (Black)
r12 - G 5 (Black): Kakuna (Black)
r9 - G 4 (Black): Unown (L) (Black)
ChrgCave (B1F) - G 2 (Black): Darumaka (Black)
ReCastle (B6F To) - G 4 (Black): Drifloon (Black)
ChlnCave (B2F) - RG 0 (Black): Rayquaza (Black)
TrChamber - G 5 (Black): Clamperl (Black)
ViRoad (1F LC) - RG 1 (Black): Keldeo (Black)
ViBridge - DG 5 (Black): Flareon (Black)
ChlnCave (B1F) - RG 0 (Black): Latias (Black)
r4 - S 0 (Black): Frillish (Black)
r12 - DG 5 (Black): Happiny (Black)
ChrgCave (1F) - G 5 (Black): Machop (Black)
ViBridge - DG 4 (Black): Dusknoir (Black)
ReCastle (B3F Ca) - G 4 (Black): Growlithe (Black)
GiChasm (C) - G 3 (Black): Pineco (Black)
ViRoad (1F MC) - RG 5 (Black): Regice (Black)
CeTower (Top) - G 0 (Black): Meditite (Black)
ChlnCave (B1F) - RG 1 (Black): Lugia (Black)
r11 - DG 0 (Black): Vanilluxe (Black)
ViRoad (4F MC) - RG 4 (Black): Sceptile (Black)
r14 - G 0 (Black): Seismitoad (Black)
ViBridge - G 1 (Black): Raticate (Black)
MaBridge - RG 5 (Black): Clefable (Black)
MiCave (2F) - G 3 (Black): Snivy (Black)
ViRoad (1F RC) - RG 5 (Black): Rotom (Mow) (Black)
GiChasm (C) - G 2 (Black): Chikorita (Black)
PiForest (I) - G 5 (Black): Diglett (Black)
r14 - DG 3 (Black): Hippowdon (Black)
r9 - RG 0 (Black): Liepard (Black)
WeCave (B1F) - RG 4 (Black): Drowzee (Black)
GiChasm (C) - DG 3 (Black): Barboach (Black)
ViBridge - SR 1 (Black): Seviper (Black)
r15 - DG 0 (Black): Sunflora (Black)
r13 - G 5 (Black): Floatzel (Black)
r3 - SR 1 (Black): Mantine (Black)
ViRoad (4F RC) - RG 0 (Black): Rotom (Wash) (Black)
ReCastle (B7F VE) - G 5 (Black): Wailord (Black)
r18 - F 1 (Black): Meowth (Black)
ViRoad (1F MC) - RG 4 (Black): Aggron (Black)
AbShrine - DG 3 (Black): Castform (Snowy) (Black)
ViRoad (3F RC) - G 5 (Black): Mantyke (Black)
r1 - FR 0 (Black): Wurmple (Black)
r18 - S 1 (Black): Unown (Z) (Black)
ReCastle (B7F VE) - G 0 (Black): Claydol (Black)
UnTown - SR 0 (Black): Roselia (Black)
DrTower (1F) - G 5 (Black): Miltank (Black)
ViRoad (3F MC) - G 3 (Black): Gothorita (Black)
ChlnCave (B1F) - G 3 (Black): Kadabra (Black)
PiForest (I) - DG 1 (Black): Lickitung (Black)
ViRoad (1F RC) - RG 3 (Black): Samurott (Black)
ViRoad (3F LC) - RG 0 (Black): Kyogre (Black)
ReCastle (B7F BoL) - G 4 (Black): Farfetch'd (Black)
GiChasm (KC) - RG 0 (Black): Arceus (Dragon) (Black)
r13 - FR 2 (Black): Gastrodon (East) (Black)
ViRoad (4F LC) - RG 3 (Black): Krookodile (Black)
ViRoad (2F RC) - RG 1 (Black): Arceus (Normal) (Black)
Dyard (R) - DG 0 (Black): Castform (Rainy) (Black)
r9 - DG 4 (Black): Unown (J) (Black)
GiChasm (OE) - RG 3 (Black): Jumpluff (Black)
DrTower (2F) - G 0 (Black): Croagunk (Black)
ViRoad (6F C) - RG 4 (Black): Haxorus (Black)
r11 - DG 1 (Black): Porygon2 (Black)
TrChamber - G 4 (Black): Charmander (Black)
CeTower (Top) - G 3 (Black): Unown (O) (Black)
r11 - G 4 (Black): Dusclops (Black)
PiForest (O) - DG 0 (Black): Blitzle (Black)
ViRoad (3F LC) - G 3 (Black): Boldore (Black)
LoForest - DG 5 (Black): Hoothoot (Black)
r4 - SR 1 (Black): Cacturne (Black)
r13 - F 2 (Black): Clefairy (Black)
r14 - G 3 (Black): Rhyhorn (Black)
ViRoad (7F C) - RG 1 (Black): Arceus (Rock) (Black)
Dyard (B) - DG 0 (Black): Bibarel (Black)
r4 - S 1 (Black): Unown (P) (Black)
ReCastle (B1F To) - G 2 (Black): Ekans (Black)
PiForest (I) - DG 5 (Black): Whirlipede (Black)
ViBridge - DG 0 (Black): Houndoom (Black)
DrDraw - RG 5 (Black): Ducklett (Black)
WeCave (1F) - RG 2 (Black): Stunky (Black)
CeTower (2F) - G 2 (Black): Jigglypuff (Black)
ViBridge - G 0 (Black): Simipour (Black)
GiChasm (OE) - DG 5 (Black): Heracross (Black)
GiChasm (KC) - G 4 (Black): Lunatone (Black)
DrCity - S 0 (Black): Unown (S) (Black)
ChlnCave (B2F) - FR 0 (Black): Ariados (Black)
GiChasm (KC) - RG 5 (Black): Yanmega (Black)
ViRoad (5F C) - RG 3 (Black): Rotom (Frost) (Black)
Dyard (B) - DG 3 (Black): Sudowoodo (Black)
PiForest (I) - G 2 (Black): Tynamo (Black)
GiChasm (OE) - RG 5 (Black): Seadra (Black)
CeTower (4F) - G 0 (Black): Lillipup (Black)
ViBridge - DG 1 (Black): Gurdurr (Black)
r17 - F 2 (Black): Baltoy (Black)
r5 - G 0 (Black): Solosis (Black)
r12 - G 0 (Black): Combee (Black)
GiChasm (KC) - RG 4 (Black): Deoxys (Black)
r3 - G 5 (Black): Paras (Black)
r1 - G 0 (Black): Spinarak (Black)
r4 - SR 0 (Black): Sawsbuck (Spring) (Black)
ViRoad (4F MC) - RG 5 (Black): Meloetta (Black)
r13 - FR 0 (Black): Yamask (Black)
MiCave (2F) - G 1 (Black): Squirtle (Black)
LoForest - G 4 (Black): Spinda (Black)
ViRoad (1F MC) - F 0 (Black): Cubchoo (Black)
ChlnCave (B2F) - G 3 (Black): Yanma (Black)
ReCastle (VR) - G 4 (Black): Gengar (Black)
r10 - G 0 (Black): Flaaffy (Black)
CeTower (4F) - G 5 (Black): Unown (F) (Black)
ViRoad (4F LC) - RG 5 (Black): Gallade (Black)
r13 - S 0 (Black): Taillow (Black)
Dyard (R) - G 0 (Black): Hoppip (Black)
ViRoad (2F RC) - RG 3 (Black): Regirock (Black)
r12 - DG 3 (Black): Aipom (Black)
r5 - RG 2 (Black): Masquerain (Black)
ViRoad (O) - G 2 (Black): Vullaby (Black)
r13 - DG 0 (Black): Misdreavus (Black)
r11 - F 0 (Black): Panpour (Black)
r14 - DG 5 (Black): Poliwrath (Black)
MiCave (1F) - RG 5 (Black): Drilbur (Black)
ChlnCave (E) - RG 2 (Black): Umbreon (Black)
r11 - DG 4 (Black): Hitmonlee (Black)
r1 - G 1 (Black): Mareep (Black)
ReCastle (To FrR) - G 2 (Black): Glalie (Black)
ViBridge - G 2 (Black): Banette (Black)
r14 - G 4 (Black): Kangaskhan (Black)
ViRoad (1F RC) - F 0 (Black): Ferroseed (Black)
Dyard (R) - G 4 (Black): Shuppet (Black)
P2Lab - S 0 (Black): Unown (N) (Black)
ViRoad (3F LC) - RG 2 (Black): Arceus (Fighting) (Black)
r16 - DG 3 (Black): Buizel (Black)
r9 - G 3 (Black): Gastrodon (West) (Black)
CeTower (Top) - G 1 (Black): Unown (A) (Black)
ViRoad (4F LC) - RG 1 (Black): Raikou (Black)
r4 - FR 1 (Black): Cacnea (Black)
IBGate - G 4 (Black): Slowbro (Black)
r17 - F 0 (Black): Deerling (Autumn) (Black)
r18 - DG 5 (Black): Wormadam (Trash) (Black)
ChlnCave (B2F) - RG 3 (Black): Celebi (Black)
P2Lab - F 2 (Black): Geodude (Black)
ViRoad (3F RC) - G 4 (Black): Cyndaquil (Black)
ReCastle (B7F TC) - G 5 (Black): Carnivine (Black)
IBGate - DG 4 (Black): Altaria (Black)
CeTower (3F) - G 1 (Black): Litwick (Black)
DrTower (1F) - G 3 (Black): Sigilyph (Black)
ViRoad (6F C) - G 3 (Black): Monferno (Black)
r12 - G 1 (Black): Igglybuff (Black)
r12 - DG 0 (Black): Whismur (Black)
DrCity - FR 1 (Black): Deerling (Summer) (Black)
P2Lab - S 1 (Black): Unown (R) (Black)
ViRoad (3F MC) - RG 4 (Black): Latios (Black)
ViRoad (5F C) - G 1 (Black): Marshtomp (Black)
StCity - SR 1 (Black): Jynx (Black)
r1 - SR 1 (Black): Breloom (Black)
r14 - F 0 (Black): Pansear (Black)
r12 - DG 1 (Black): Sentret (Black)
ViRoad (4F LC) - G 3 (Black): Plusle (Black)
TrChamber - RG 3 (Black): Garchomp (Black)
ViRoad (7F C) - RG 4 (Black): Walrein (Black)
r1 - DG 1 (Black): Nidorina (Black)
ChlnCave (B2F) - RG 1 (Black): Vaporeon (Black)
ViRoad (3F MC) - G 0 (Black): Beheeyem (Black)
DrCity - FR 0 (Black): Tentacool (Black)
P2Lab - G 0 (Black): Castform (Black)
ReCastle (B1F To) - G 1 (Black): Smoochum (Black)
r18 - S 0 (Black): Unown (U) (Black)
DrTower (1F) - G 0 (Black): Sandshrew (Black)
ViRoad (2F LC) - RG 0 (Black): Jolteon (Black)
r16 - RG 0 (Black): Cherrim (Sunshine) (Black)
MiCave (2F) - RG 5 (Black): Hippopotas (Black)
r13 - S 1 (Black): Unown (I) (Black)
r3 - DG 0 (Black): Seedot (Black)
Dyard (R) - DG 3 (Black): Horsea (Black)
ChlnCave (B1F) - RG 5 (Black): Tyranitar (Black)
ViRoad (1F MC) - F 1 (Black): Absol (Black)
ChlnCave (E) - G 1 (Black): Tepig (Black)
r3 - DG 3 (Black): Ledyba (Black)
ReCastle (B7F VE) - G 4 (Black): Shuckle (Black)
ViRoad (3F MC) - RG 0 (Black): Arceus (Dark) (Black)
ViRoad (7F C) - RG 2 (Black): Mew (Black)
Dyard (R) - G 5 (Black): Trapinch (Black)
r4 - G 3 (Black): Totodile (Black)
ReCastle (B7F LoVE) - G 4 (Black): Scraggy (Black)
r10 - G 4 (Black): Tauros (Black)
r4 - G 1 (Black): Piplup (Black)
r13 - G 4 (Black): Tangela (Black)
GiChasm (KC) - G 1 (Black): Primeape (Black)
r15 - G 0 (Black): Metang (Black)
ViRoad (4F LC) - RG 0 (Black): Uxie (Black)
LoForest - F 1 (Black): Maractus (Black)
ChlnCave (E) - RG 5 (Black): Steelix (Black)
AbShrine - RG 2 (Black): Wormadam (Plant) (Black)
ViRoad (1F RC) - G 2 (Black): Spiritomb (Black)
WeCave (1F) - G 3 (Black): Gastly (Black)
GiChasm (KC) - RG 2 (Black): Rotom (Fan) (Black)
DrTower (2F) - G 5 (Black): Deino (Black)
ReCastle (B7F BoL) - G 1 (Black): Purugly (Black)
r5 - DG 3 (Black): Snover (Black)
PiForest (O) - DG 1 (Black): Spearow (Black)
ViRoad (7F C) - RG 0 (Black): Deoxys (Speed) (Black)
AbShrine - SR 0 (Black): Mime Jr. (Black)
LoForest - DG 0 (Black): Riolu (Black)
CeTower (Top) - G 5 (Black): Unown (D) (Black)
ChlnCave (E) - RG 1 (Black): Jirachi (Black)
ReCastle (B7F VE) - G 1 (Black): Muk (Black)
ViRoad (4F RC) - RG 4 (Black): Meloetta (Pirouette) (Black)
r12 - DG 2 (Black): Espeon (Black)
GiChasm (EC) - RG 5 (Black): Thundurus (Black)
CeTower (4F) - G 3 (Black): Unown (Question Mark) (Black)
r18 - SR 1 (Black): Xatu (Black)
ViRoad (6F C) - RG 0 (Black): Arceus (Bug) (Black)
r14 - F 2 (Black): Slowpoke (Black)
r5 - G 1 (Black): Beldum (Black)
r2 - G 0 (Black): Poochyena (Black)
CeTower (3F) - G 4 (Black): Slakoth (Black)
r10 - DG 5 (Black): Leavanny (Black)
r9 - G 1 (Black): Timburr (Black)
ReCastle (VR) - G 1 (Black): Lapras (Black)
WeCave (1F) - RG 4 (Black): Trubbish (Black)
PiForest (O) - G 2 (Black): Vulpix (Black)
ViRoad (4F MC) - RG 3 (Black): Giratina (Origin) (Black)
ViRoad (3F RC) - RG 0 (Black): Cresselia (Black)
ViRoad (3F MC) - RG 3 (Black): Milotic (Black)
r18 - G 5 (Black): Fraxure (Black)
ViRoad (1F MC) - RG 3 (Black): Deoxys (Attack) (Black)
r3 - G 0 (Black): Weedle (Black)
TrChamber - RG 5 (Black): Ho-Oh (Black)
GiChasm (EC) - S 1 (Black): Skorupi (Black)
ReCastle (B4F Ca) - G 3 (Black): Whimsicott (Black)
ChlnCave (E) - G 2 (Black): Pachirisu (Black)
r4 - F 0 (Black): Krabby (Black)
r2 - G 2 (Black): Caterpie (Black)
MiCave (1F) - G 4 (Black): Combusken (Black)
r1 - G 4 (Black): Togepi (Black)
r17 - S 0 (Black): Unown (X) (Black)
r3 - DG 2 (Black): Gible (Black)
ViRoad (4F RC) - RG 1 (Black): Gardevoir (Black)
StCity - FR 1 (Black): Basculin (Blue-Striped) (Black)
PiForest (I) - RG 3 (Black): Psyduck (Black)
WeCave (B1F) - RG 1 (Black): Shellos (West) (Black)
ViRoad (1F RC) - RG 0 (Black): Weavile (Black)
ViRoad (4F MC) - RG 1 (Black): Mesprit (Black)
r18 - G 2 (Black): Dunsparce (Black)
AbShrine - F 1 (Black): Dodrio (Black)
GuChamber - RG 1 (Black): Delibird (Black)
P2Lab - SR 0 (Black): Pidgeot (Black)
r13 - SR 1 (Black): Corsola (Black)
P2Lab - RG 0 (Black): Solrock (Black)
IBGate - DG 2 (Black): Nosepass (Black)
ReCastle (B7F RoC) - G 5 (Black): Hitmontop (Black)
ReCastle (B7F VE) - G 3 (Black): Glaceon (Black)
r13 - G 0 (Black): Pelipper (Black)
ReCastle (B7F LoVE) - G 0 (Black): Pidgeotto (Black)
UnTown - S 1 (Black): Koffing (Black)
PiForest (O) - G 3 (Black): Venipede (Black)
r17 - SR 1 (Black): Dewgong (Black)
r2 - G 4 (Black): Purrloin (Black)
PiForest (O) - G 1 (Black): Wynaut (Black)
TrChamber - RG 1 (Black): Arceus (Psychic) (Black)
r11 - FR 0 (Black): Axew (Black)
r1 - G 2 (Black): Shedinja (Black)
ChrgCave (B1F) - RG 4 (Black): Voltorb (Black)
r16 - DG 1 (Black): Minccino (Black)
AbShrine - DG 1 (Black): Chatot (Black)
r13 - DG 5 (Black): Escavalier (Black)
ViRoad (2F LC) - G 3 (Black): Illumise (Black)
r15 - DG 2 (Black): Swoobat (Black)
PiForest (O) - G 4 (Black): Remoraid (Black)
r18 - DG 2 (Black): Pupitar (Black)
Dyard (R) - G 2 (Black): Azurill (Black)
MiCave (1F) - G 1 (Black): Treecko (Black)
DrDraw - RG 1 (Black): Minccino (Black)
CeTower (2F) - G 3 (Black): Nidoran♀ (Black)
ViRoad (6F C) - RG 1 (Black): Dialga (Black)
PiForest (I) - DG 4 (Black): Luxio (Black)
r10 - G 5 (Black): Bouffalant (Black)
TrChamber - RG 4 (Black): Mienshao (Black)
GiChasm (OE) - DG 0 (Black): Quagsire (Black)
r17 - S 1 (Black): Unown (M) (Black)
r14 - G 2 (Black): Hitmonchan (Black)
ViRoad (3F RC) - RG 3 (Black): Arceus (Ghost) (Black)
ChrgCave (1F) - G 0 (Black): Oddish (Black)
r13 - FR 1 (Black): Deerling (Spring) (Black)
GiChasm (OE) - G 5 (Black): Politoed (Black)
ViRoad (2F RC) - RG 0 (Black): Shaymin (Black)
r11 - G 1 (Black): Magmar (Black)
ReCastle (VR) - G 3 (Black): Ursaring (Black)
r1 - DG 2 (Black): Sealeo (Black)
ViRoad (4F RC) - G 0 (Black): Golurk (Black)
GiChasm (KC) - FR 0 (Black): Kricketune (Black)
IBGate - RG 2 (Black): Dewott (Black)
WeCave (1F) - G 1 (Black): Corphish (Black)
ReCastle (B3F Ca) - G 5 (Black): Unfezant (Black)
ViRoad (3F MC) - RG 2 (Black): Suicune (Black)
LoForest - G 5 (Black): Zubat (Black)
r4 - F 1 (Black): Staryu (Black)
DrCity - S 1 (Black): Unown (C) (Black)
MiCave (1F) - RG 3 (Black): Seel (Black)
WeCave (B1F) - RG 3 (Black): Dwebble (Black)
P2Lab - G 2 (Black): Dragonair (Black)
DeResort (I) - G 3 (Black): Abra (Black)
ViRoad (4F RC) - G 4 (Black): Torchic (Black)
GuChamber - RG 5 (Black): Magnemite (Black)
ViRoad (1F LC) - G 4 (Black): Sewaddle (Black)
WeCave (1F) - G 5 (Black): Swablu (Black)
CeTower (3F) - G 5 (Black): Staravia (Black)
ChrgCave (B2F) - G 4 (Black): Chimchar (Black)
ViRoad (4F RC) - G 3 (Black): Ivysaur (Black)
ChlnCave (B1F) - RG 2 (Black): Honchkrow (Black)
ChrgCave (B2F) - RG 3 (Black): Spoink (Black)
r18 - DG 3 (Black): Manectric (Black)
DrTower (2F) - G 3 (Black): Venonat (Black)
ViRoad (3F MC) - RG 5 (Black): Arceus (Steel) (Black)
CoStorage - DG 5 (Black): Pikachu (Black)
MiCave (2F) - RG 4 (Black): Teddiursa (Black)
r3 - G 1 (Black): Lotad (Black)
WeCave (B1F) - RG 5 (Black): Finneon (Black)
r13 - RG 3 (Black): Audino (Black)
WeCave (1F) - F 2 (Black): Volbeat (Black)
ChlnCave (B2F) - RG 5 (Black): Groudon (Black)
r14 - G 1 (Black): Ralts (Black)
r1 - RG 1 (Black): Piloswine (Black)
r3 - G 3 (Black): Pidove (Black)
r15 - DG 3 (Black): Nidoking (Black)
ReCastle (1F To) - G 4 (Black): Munna (Black)
r18 - G 1 (Black): Natu (Black)
ChlnCave (B1F) - G 4 (Black): Poliwhirl (Black)
ViRoad (4F RC) - RG 5 (Black): Zekrom (Black)
r3 - FR 1 (Black): Sawk (Black)
ChrgCave (B1F) - G 3 (Black): Boldore (Black)
ViRoad (6F C) - RG 3 (Black): Genesect (Black)
PiForest (I) - G 4 (Black): Smeargle (Black)
r13 - SR 0 (Black): Unown (T) (Black)
GiChasm (EC) - F 1 (Black): Girafarig (Black)
ViRoad (6F C) - G 1 (Black): Porygon (Black)
ChlnCave (B2F) - G 1 (Black): Doduo (Black)
r1 - DG 0 (Black): Linoone (Black)
CoStorage - DG 4 (Black): Poliwag (Black)
ViRoad (1F RC) - G 3 (Black): Shelmet (Black)
CoStorage - DG 3 (Black): Glameow (Black)
r18 - FR 1 (Black): Marowak (Black)
ReCastle (B2F Ca) - G 0 (Black): Unown (Y) (Black)
ViRoad (4F LC) - RG 4 (Black): Klinklang (Black)
r5 - DG 0 (Black): Duskull (Black)
r11 - F 2 (Black): Cubone (Black)
ViRoad (5F C) - RG 4 (Black): Cloyster (Black)
P2Lab - FR 1 (Black): Qwilfish (Black)
r16 - DG 0 (Black): Shroomish (Black)
ChlnCave (B2F) - F 2 (Black): Sableye (Black)
UnTown - S 0 (Black): Makuhita (Black)
DrTower (2F) - G 1 (Black): Snorunt (Black)
ViRoad (7F C) - RG 5 (Black): Shaymin (Sky) (Black)
r14 - DG 0 (Black): Donphan (Black)
PiForest (O) - DG 3 (Black): Kricketot (Black)
ViRoad (1F MC) - G 0 (Black): Druddigon (Black)
ViRoad (1F RC) - RG 4 (Black): Arceus (Ice) (Black)
ReCastle (VR) - G 0 (Black): Scyther (Black)
r13 - G 1 (Black): Lairon (Black)
r11 - G 0 (Black): Magby (Black)
ReCastle (B6F To) - G 0 (Black): Unown (G) (Black)
r3 - DG 1 (Black): Bidoof (Black)
r13 - DG 1 (Black): Chimecho (Black)
GiChasm (KC) - F 0 (Black): Numel (Black)
AbShrine - DG 4 (Black): Torkoal (Black)
ViRoad (5F C) - G 3 (Black): Grotle (Black)
CeTower (Top) - G 2 (Black): Tyrogue (Black)
ReCastle (B3F To) - G 5 (Black): Heatmor (Black)
ReCastle (Ca SF) - G 4 (Black): Unown (B) (Black)
r2 - G 5 (Black): Cottonee (Black)
MaBridge - RG 2 (Black): Stunfisk (Black)
r12 - G 3 (Black): Elekid (Black)
ViRoad (2F LC) - G 5 (Black): Rufflet (Black)
ReCastle (B1F Ca) - G 3 (Black): Larvitar (Black)
r17 - FR 1 (Black): Castform (Sunny) (Black)
ViRoad (4F MC) - RG 2 (Black): Arceus (Grass) (Black)
r3 - G 4 (Black): Wingull (Black)
r13 - RG 4 (Black): Klang (Black)
AbShrine - F 0 (Black): Bulbasaur (Black)
ChrgCave (1F) - RG 5 (Black): Luvdisc (Black)
r18 - F 0 (Black): Elgyem (Black)
ViRoad (1F MC) - RG 0 (Black): Gliscor (Black)
ChlnCave (E) - RG 0 (Black): Articuno (Black)
ViRoad (3F LC) - RG 1 (Black): Arceus (Fire) (Black)
GiChasm (EC) - RG 2 (Black): Azelf (Black)
ViRoad (O) - G 3 (Black): Durant (Black)
GuChamber - RG 4 (Black): Eevee (Black)
ChlnCave (B2F) - SR 1 (Black): Throh (Black)
GiChasm (OE) - G 0 (Black): Gligar (Black)
ViRoad (1F LC) - RG 4 (Black): Rotom (Heat) (Black)
ViRoad (1F LC) - RG 3 (Black): Exeggutor (Black)
CeTower (2F) - G 4 (Black): Nidoran♂ (Black)
ReCastle (B7F RoVE) - G 2 (Black): Relicanth (Black)
WeCave (1F) - G 0 (Black): Cherubi (Black)
ViRoad (2F RC) - G 5 (Black): Unown (H) (Black)
r15 - RG 2 (Black): Shelgon (Black)
WeCave (1F) - RG 5 (Black): Chinchou (Black)
r14 - DG 1 (Black): Pichu (Black)
ChrgCave (1F) - RG 3 (Black): Aron (Black)
r17 - SR 0 (Black): Galvantula (Black)
ReCastle (B7F RoC) - G 3 (Black): Mawile (Black)
ChlnCave (E) - RG 3 (Black): Darmanitan (Zen) (Black)
ViRoad (1F LC) - RG 0 (Black): Giratina (Black)
ReCastle (B1F To) - G 3 (Black): Bellsprout (Black)
ReCastle (1F To) - G 2 (Black): Sandile (Black)
ViRoad (3F MC) - RG 1 (Black): Deoxys (Defense) (Black)
ViRoad (5F C) - RG 5 (Black): Moltres (Black)
GiChasm (OE) - RG 2 (Black): Wormadam (Sandy) (Black)
PiForest (I) - DG 2 (Black): Patrat (Black)
r10 - RG 2 (Black): Mothim (Black)
CeTower (Top) - G 4 (Black): Skitty (Black)
ViBridge - FR 0 (Black): Bronzor (Black)
r18 - DG 0 (Black): Pawniard (Black)
r14 - RG 5 (Black): Kecleon (Black)
r3 - DG 5 (Black): Roggenrola (Black)
CeTower (2F) - G 0 (Black): Burmy (Plant) (Black)
r14 - G 5 (Black): Pinsir (Black)
ViBridge - F 2 (Black): Shellder (Black)
ReCastle (VR) - G 2 (Black): Rapidash (Black)
ViRoad (1F MC) - G 3 (Black): Golett (Black)
PiForest (I) - G 0 (Black): Cleffa (Black)
CeTower (2F) - G 1 (Black): Pidgey (Black)
GiChasm (KC) - S 1 (Black): Houndour (Black)
ViRoad (1F RC) - RG 1 (Black): Registeel (Black)
DeResort (I) - G 2 (Black): Electrike (Black)
GiChasm (EC) - RG 1 (Black): Zapdos (Black)
MiCave (2F) - RG 3 (Black): Grimer (Black)
DrTower (1F) - G 4 (Black): Gulpin (Black)
CeTower (2F) - G 5 (Black): Wooper (Black)
ChrgCave (1F) - G 2 (Black): Joltik (Black)
ReCastle (B4F To) - G 2 (Black): Unown (V) (Black)
r18 - RG 2 (Black): Seaking (Black)
ViRoad (4F MC) - G 2 (Black): Lopunny (Black)
ViRoad (1F MC) - G 1 (Black): Ponyta (Black)
GiChasm (EC) - RG 0 (Black): Darkrai (Black)
GiChasm (KC) - F 2 (Black): Magcargo (Black)
Dyard (R) - G 3 (Black): Surskit (Black)
r2 - G 1 (Black): Burmy (Sandy) (Black)
ViRoad (2F LC) - RG 2 (Black): Mewtwo (Black)
StCity - S 0 (Black): Sharpedo (Black)
Dyard (B) - DG 2 (Black): Tympole (Black)
CeTower (4F) - G 4 (Black): Feebas (Black)
ViRoad (5F C) - RG 0 (Black): Heatran (Black)
AbShrine - SR 1 (Black): Ninjask (Black)
DrTower (2F) - G 4 (Black): Klink (Black)
CeTower (4F) - G 2 (Black): Swinub (Black)
GuChamber - G 1 (Black): Woobat (Black)
ViRoad (4F LC) - RG 2 (Black): Arceus (Flying) (Black)
PiForest (I) - DG 0 (Black): Starly (Black)
r5 - DG 2 (Black): Exeggcute (Black)
r1 - G 3 (Black): Zigzagoon (Black)
PiForest (O) - DG 2 (Black): Gothita (Black)
r9 - G 0 (Black): Murkrow (Black)
GiChasm (KC) - FR 2 (Black): Onix (Black)
ChlnCave (B2F) - RG 4 (Black): Entei (Black)
r3 - SR 0 (Black): Skarmory (Black)
CeTower (3F) - G 3 (Black): Sunkern (Black)
GiChasm (C) - DG 2 (Black): Goldeen (Black)
ViRoad (1F MC) - FR 2 (Black): Wailmer (Black)
WeCave (B1F) - G 0 (Black): Nincada (Black)
r5 - G 2 (Black): Phanpy (Black)
ReCastle (B7F RoC) - G 4 (Black): Mienfoo (Black)
ReCastle (B5F To) - G 0 (Black): Unown (Exclamation Mark) (Black)
CeTower (3F) - G 2 (Black): Rattata (Black)
ReCastle (B1F To) - G 4 (Black): Spheal (Black)
ViRoad (3F LC) - G 4 (Black): Karrablast (Black)
r15 - G 2 (Black): Sneasel (Black)
GuChamber - RG 0 (Black): Shellos (East) (Black)
AbShrine - DG 0 (Black): Remoraid (Black)
ViRoad (1F MC) - SR 0 (Black): Stantler (Black)
r2 - G 3 (Black): Slugma (Black)
DrTower (2F) - G 2 (Black): Carvanha (Black)
UnTown - FR 2 (Black): Sawsbuck (Winter) (Black)
DrDraw - RG 0 (Black): Mankey (Black)
ReCastle (B2F To) - G 2 (Black): Unown (W) (Black)
ViRoad (3F MC) - G 4 (Black): Mudkip (Black)
ViBridge - FR 2 (Black): Zangoose (Black)
ViRoad (2F LC) - G 4 (Black): Oshawott (Black)
ViRoad (4F MC) - RG 0 (Black): Manaphy (Black)
ReCastle (Ca SF) - G 0 (Black): Buneary (Black)
ReCastle (B3F Ca) - G 1 (Black): Cryogonal (Black)
UnTown - F 2 (Black): Vanillite (Black)
ViRoad (6F C) - G 2 (Black): Phione (Black)
r9 - G 2 (Black): Alomomola (Black)
ViRoad (3F LC) - RG 4 (Black): Arceus (Poison) (Black)
r14 - S 1 (Black): Deerling (Winter) (Black)
ChrgCave (B1F) - G 5 (Black): Snubbull (Black)
ChrgCave (1F) - G 3 (Black): Minun (Black)
MiCave (1F) - G 5 (Black): Karrablast (Black)
CoStorage - DG 1 (Black): Bagon (Black)
ViRoad (2F LC) - RG 5 (Black): Arceus (Water) (Black)
ReCastle (B7F RoVE) - G 4 (Black): Unown (E) (Black)
ViRoad (2F LC) - RG 4 (Black): Arceus (Ground) (Black)
LoForest - G 2 (Black): Chingling (Black)
ViRoad (1F RC) - RG 2 (Black): Palkia (Black)
ViRoad (6F C) - RG 2 (Black): Arceus (Electric) (Black)
ChrgCave (B2F) - G 0 (Black): Turtwig (Black)
ReCastle (Ca SF) - G 2 (Black): Unown (Q) (Black)
ReCastle (B1F Ca) - G 1 (Black): Dratini (Black)
r13 - G 2 (Black): Tropius (Black)
Dyard (R) - G 1 (Black): Budew (Black)
r4 - G 0 (Black): Bonsly (Black)
ReCastle (B7F BoR) - G 0 (Black): Unown (K) (Black)
LoForest - G 0 (Black): Cottonee (Black)
CeTower (4F) - G 1 (Black): Shinx (Black)
r1 - G 5 (Black): Burmy (Trash) (Black)
IBGate - G 3 (Black): Poliwhirl (Black)
CoStorage - RG 2 (Black): Garbodor (Black)
r2 - RG 5 (Black): Vigoroth (Black)
GiChasm (OE) - RG 4 (Black): Azumarill (Black)
r5 - RG 1 (Black): Meganium (Black)
ViBridge - G 4 (Black): Staravia (Black)
r5 - RG 4 (Black): Shelgon (Black)
r15 - G 1 (Black): Croconaw (Black)
r3 - RG 2 (Black): Carnivine (Black)
PiForest (O) - RG 0 (Black): Alakazam (Black)
IBGate - DG 1 (Black): Deerling (Winter) (Black)
r5 - DG 4 (Black): Dunsparce (Black)
IBGate - DG 0 (Black): Lairon (Black)
r15 - G 4 (Black): Jynx (Black)
Dyard (R) - RG 2 (Black): Fearow (Black)
r16 - G 5 (Black): Crustle (Black)
r3 - RG 1 (Black): Reuniclus (Black)
ViBridge - RG 3 (Black): Girafarig (Black)
r10 - G 1 (Black): Delibird (Black)
GiChasm (C) - DG 4 (Black): Sharpedo (Black)
r2 - RG 4 (Black): Alomomola (Black)
r11 - RG 0 (Black): Seviper (Black)
r3 - RG 4 (Black): Sawsbuck (Winter) (Black)
r14 - RG 4 (Black): Combusken (Black)
r11 - RG 5 (Black): Banette (Black)
AbShrine - RG 3 (Black): Pignite (Black)
LoForest - RG 0 (Black): Quilava (Black)
P2Lab - RG 1 (Black): Shiftry (Black)
r2 - RG 3 (Black): Ursaring (Black)
r9 - RG 1 (Black): Mothim (Black)
P2Lab - RG 4 (Black): Exeggutor (Black)
ReCastle (Ca SF) - G 5 (Black): Phione (Black)
CoStorage - RG 1 (Black): Mr. Mime (Black)
r15 - RG 3 (Black): Persian (Black)
ReCastle (B2F Ca) - G 3 (Black): Kecleon (Black)
ReCastle (B4F Ca) - G 1 (Black): Drapion (Black)
r12 - RG 3 (Black): Watchog (Black)
ReCastle (B7F TL) - G 1 (Black): Druddigon (Black)
r11 - F 1 (Black): Chimecho (Black)
AbShrine - RG 4 (Black): Kingler (Black)
GiChasm (EC) - S 0 (Black): Swalot (Black)
ReCastle (B7F TL) - G 5 (Black): Stunfisk (Black)
ViBridge - RG 1 (Black): Dunsparce (Black)
AbShrine - FR 2 (Black): Mr. Mime (Black)
ViBridge - F 1 (Black): Politoed (Black)
ReCastle (B7F LoTC) - G 5 (Black): Dewgong (Black)
ReCastle (Ca BaR) - G 5 (Black): Klang (Black)
Dyard (R) - RG 4 (Black): Absol (Black)
r18 - G 4 (Black): Piplup (Black)
r10 - G 2 (Black): Vullaby (Black)
ReCastle (Ca BaR) - G 1 (Black): Castform (Snowy) (Black)
GiChasm (C) - DG 1 (Black): Basculin (Red-Striped) (Black)
ViRoad (3F LC) - G 0 (Black): Minun (Black)
r10 - RG 1 (Black): Mightyena (Black)
ReCastle (B3F Ca) - G 3 (Black): Sealeo (Black)
ViRoad (5F C) - G 2 (Black): Durant (Black)
GiChasm (C) - DG 5 (Black): Castform (Sunny) (Black)
r1 - DG 4 (Black): Krokorok (Black)
ReCastle (B7F BoR) - G 2 (Black): Magmar (Black)
IBGate - G 2 (Black): Bagon (Black)
r1 - DG 3 (Black): Shellder (Black)
r14 - SR 1 (Black): Rotom (Frost) (Black)
GiChasm (EC) - SR 1 (Black): Liepard (Black)
ViRoad (1F LC) - G 5 (Black): Munchlax (Black)
ViRoad (2F LC) - G 0 (Black): Shuckle (Black)
WeCave (1F) - SR 0 (Black): Zangoose (Black)
ReCastle (B7F BoL) - G 5 (Black): Relicanth (Black)
DrTower (1F) - G 1 (Black): Unown (O) (Black)
DeResort (O) - G 5 (Black): Deerling (Winter) (Black)
IBGate - DG 3 (Black): Croconaw (Black)
ReCastle (B4F To) - G 4 (Black): Mawile (Black)
r1 - RG 4 (Black): Scizor (Black)
r11 - G 5 (Black): Leafeon (Black)
ReCastle (B7F TR) - G 5 (Black): Mr. Mime (Black)
r16 - DG 4 (Black): Vigoroth (Black)
ReCastle (B7F TR) - G 0 (Black): Scraggy (Black)
Dyard (R) - RG 1 (Black): Gastrodon (West) (Black)
ViRoad (O) - G 0 (Black): Sealeo (Black)
P2Lab - RG 5 (Black): Misdreavus (Black)
GiChasm (C) - G 5 (Black): Dugtrio (Black)
ViRoad (1F RC) - SR 1 (Black): Persian (Black)
r16 - G 4 (Black): Ludicolo (Black)
r18 - G 0 (Black): Unown (Z) (Black)
LoForest - S 1 (Black): Skuntank (Black)
PiForest (O) - RG 2 (Black): Amoonguss (Black)
ReCastle (B4F To) - G 5 (Black): Throh (Black)
ViRoad (1F LC) - G 2 (Black): Golduck (Black)
r14 - S 0 (Black): Mr. Mime (Black)
r2 - RG 1 (Black): Exploud (Black)
ReCastle (B7F LoTC) - G 0 (Black): Turtwig (Black)
PiForest (I) - DG 3 (Black): Marowak (Black)
WeCave (B1F) - F 2 (Black): Swellow (Black)
PiForest (I) - SR 1 (Black): Xatu (Black)
r9 - DG 0 (Black): Parasect (Black)
AbShrine - RG 5 (Black): Jumpluff (Black)
ReCastle (Ca SF) - G 1 (Black): Raichu (Black)
ReCastle (B7F Ce) - G 3 (Black): Porygon (Black)
WeCave (B1F) - FR 0 (Black): Kricketune (Black)
ViRoad (1F RC) - SR 0 (Black): Audino (Black)
ReCastle (B3F To) - G 1 (Black): Stunfisk (Black)
r13 - DG 2 (Black): Garbodor (Black)
TrChamber - G 0 (Black): Gardevoir (Black)
ChlnCave (B2F) - FR 2 (Black): Snubbull (Black)
TrChamber - G 3 (Black): Raticate (Black)
CoStorage - RG 0 (Black): Magneton (Black)
ViRoad (1F RC) - F 2 (Black): Grovyle (Black)
GiChasm (C) - RG 0 (Black): Kingler (Black)
ViRoad (3F LC) - G 1 (Black): Deerling (Spring) (Black)
ReCastle (B7F UTR) - G 1 (Black): Lunatone (Black)
ReCastle (B7F BoR) - G 5 (Black): Basculin (Red-Striped) (Black)
ReCastle (Ca BaR) - G 3 (Black): Omanyte (Black)
IBGate - G 1 (Black): Anorith (Black)
ViRoad (3F MC) - G 2 (Black): Garbodor (Black)
PiForest (I) - S 1 (Black): Rampardos (Black)
ChlnCave (B1F) - G 0 (Black): Weepinbell (Black)
ChlnCave (B2F) - SR 0 (Black): Sawsbuck (Autumn) (Black)
ReCastle (B7F LoVE) - G 5 (Black): Bellossom (Black)
WeCave (B1F) - S 0 (Black): Accelgor (Black)
ReCastle (B7F BoR) - G 3 (Black): Buizel (Black)
GiChasm (OE) - DG 4 (Black): Sandslash (Black)
r11 - FR 1 (Black): Lumineon (Black)
LoForest - SR 1 (Black): Basculin (Blue-Striped) (Black)
ViRoad (6F C) - G 5 (Black): Shelmet (Black)
r9 - RG 3 (Black): Primeape (Black)
r3 - S 1 (Black): Rampardos (Black)
ViRoad (5F C) - G 0 (Black): Whimsicott (Black)
r1 - RG 2 (Black): Unown (Z) (Black)
r1 - SR 0 (Black): Vespiquen (Black)
ReCastle (B5F To) - G 1 (Black): Cherrim (Sunshine) (Black)
ReCastle (Ca BaR) - G 0 (Black): Unown (B) (Black)
ReCastle (B7F RoVE) - G 1 (Black): Mr. Mime (Black)
ViRoad (1F RC) - FR 2 (Black): Unown (A) (Black)
Dyard (R) - DG 4 (Black): Chimchar (Black)
ViRoad (4F RC) - G 2 (Black): Hypno (Black)
r1 - RG 3 (Black): Cherrim (Overcast) (Black)
ReCastle (B7F UTL) - G 0 (Black): Luxio (Black)
ReCastle (B7F TC) - G 4 (Black): Haunter (Black)
AbShrine - FR 1 (Black): Vigoroth (Black)
P2Lab - G 5 (Black): Smoochum (Black)
r3 - RG 0 (Black): Bronzong (Black)
r11 - G 3 (Black): Castform (Sunny) (Black)
r13 - DG 3 (Black): Sawsbuck (Summer) (Black)
ChrgCave (1F) - RG 2 (Black): Drifloon (Black)
MiCave (1F) - RG 0 (Black): Doduo (Black)
MiCave (1F) - RG 2 (Black): Sewaddle (Black)
r18 - RG 1 (Black): Yanma (Black)
ViRoad (1F LC) - G 0 (Black): Chandelure (Black)
ViBridge - G 3 (Black): Durant (Black)
ReCastle (B7F Ce) - G 5 (Black): Cherrim (Sunshine) (Black)
LoForest - F 0 (Black): Vulpix (Black)
ReCastle (B4F To) - G 0 (Black): Corsola (Black)
LoForest - FR 1 (Black): Exploud (Black)
ChrgCave (1F) - RG 0 (Black): Riolu (Black)
r11 - RG 1 (Black): Musharna (Black)
ReCastle (B7F LoTC) - G 1 (Black): Ledian (Black)
LoForest - F 2 (Black): Shellos (East) (Black)
LoForest - RG 3 (Black): Rufflet (Black)
ReCastle (B7F BoL) - G 3 (Black): Azumarill (Black)
ReCastle (B7F LoC) - G 3 (Black): Nidorina (Black)
WeCave (B1F) - RG 0 (Black): Shroomish (Black)
ReCastle (B6F To) - G 3 (Black): Quagsire (Black)
CoStorage - G 0 (Black): Beautifly (Black)
ChlnCave (B2F) - S 1 (Black): Mr. Mime (Black)
ReCastle (B7F TL) - G 2 (Black): Nidoking (Black)
WeCave (B1F) - RG 2 (Black): Scraggy (Black)
ReCastle (B7F UTR) - G 4 (Black): Eevee (Black)
ReCastle (B7F BoL) - G 2 (Black): Zebstrika (Black)
ViRoad (1F RC) - G 5 (Black): Seel (Black)
r3 - RG 5 (Black): Staraptor (Black)
PiForest (O) - RG 1 (Black): Wobbuffet (Black)
r14 - RG 3 (Black): Gligar (Black)
GiChasm (C) - RG 1 (Black): Dodrio (Black)
PiForest (I) - F 2 (Black): Gulpin (Black)
DeResort (I) - G 4 (Black): Amoonguss (Black)
GiChasm (EC) - G 5 (Black): Vigoroth (Black)
r12 - RG 1 (Black): Gastrodon (West) (Black)
ViRoad (1F LC) - G 3 (Black): Butterfree (Black)
r14 - FR 2 (Black): Swalot (Black)
Dyard (R) - DG 5 (Black): Beautifly (Black)
ReCastle (B4F Ca) - G 5 (Black): Ambipom (Black)
GiChasm (KC) - SR 1 (Black): Audino (Black)
r17 - FR 0 (Black): Misdreavus (Black)
ReCastle (B7F UTL) - G 5 (Black): Skarmory (Black)
PiForest (I) - RG 0 (Black): Grumpig (Black)
ReCastle (B7F LoTC) - G 3 (Black): Kabuto (Black)
ViRoad (1F MC) - S 0 (Black): Pidgeot (Black)
ViBridge - SR 0 (Black): Rhydon (Black)
ChrgCave (B2F) - G 3 (Black): Castform (Black)
ReCastle (B7F LoVE) - G 3 (Black): Tranquill (Black)
r10 - RG 4 (Black): Wormadam (Plant) (Black)
ViBridge - S 0 (Black): Kingler (Black)
WeCave (B1F) - G 1 (Black): Unown (F) (Black)
ViRoad (1F RC) - G 0 (Black): Dewgong (Black)
AbShrine - DG 5 (Black): Castform (Black)
PiForest (O) - RG 3 (Black): Grumpig (Black)
TrChamber - G 2 (Black): Stoutland (Black)
ChrgCave (B2F) - RG 0 (Black): Panpour (Black)
r1 - RG 5 (Black): Seadra (Black)
GuChamber - G 0 (Black): Nidorina (Black)
PiForest (I) - G 1 (Black): Snover (Black)
ReCastle (Ca BaR) - G 4 (Black): Unown (Exclamation Mark) (Black)
GuChamber - G 2 (Black): Quilava (Black)
ReCastle (B7F BoL) - G 0 (Black): Staravia (Black)
r1 - F 1 (Black): Crustle (Black)
WeCave (B1F) - G 5 (Black): Unown (Y) (Black)
ViRoad (4F MC) - G 4 (Black): Vanillite (Black)
r5 - DG 5 (Black): Granbull (Black)
ChrgCave (1F) - G 1 (Black): Shellos (East) (Black)
CoStorage - RG 5 (Black): Shiftry (Black)
WeCave (1F) - RG 3 (Black): Koffing (Black)
ViRoad (O) - G 4 (Black): Oshawott (Black)
WeCave (B1F) - F 0 (Black): Snivy (Black)
r1 - RG 0 (Black): Seaking (Black)
ChlnCave (E) - G 3 (Black): Beautifly (Black)
ViBridge - DG 2 (Black): Vileplume (Black)
MiCave (2F) - G 5 (Black): Unown (E) (Black)
ReCastle (B7F RoTC) - G 3 (Black): Gothorita (Black)
GiChasm (C) - G 0 (Black): Numel (Black)
ReCastle (B7F UTR) - G 5 (Black): Swanna (Black)
UnTown - F 1 (Black): Unown (Z) (Black)
PiForest (I) - RG 1 (Black): Carnivine (Black)
ReCastle (B7F Ce) - G 1 (Black): Slowking (Black)
ReCastle (B7F LoC) - G 5 (Black): Garbodor (Black)
GiChasm (C) - RG 5 (Black): Garbodor (Black)
r4 - FR 2 (Black): Drapion (Black)
P2Lab - RG 3 (Black): Crawdaunt (Black)
GiChasm (EC) - G 4 (Black): Graveler (Black)
ViRoad (3F RC) - G 3 (Black): Marowak (Black)
AbShrine - RG 1 (Black): Liepard (Black)
MiCave (2F) - G 0 (Black): Unown (B) (Black)
r10 - RG 0 (Black): Volbeat (Black)
Dyard (R) - RG 5 (Black): Lopunny (Black)
ChlnCave (E) - G 0 (Black): Swoobat (Black)
PiForest (O) - DG 5 (Black): Slowpoke (Black)
ReCastle (B1F Ca) - G 4 (Black): Darumaka (Black)
IBGate - RG 3 (Black): Arbok (Black)
ViRoad (1F MC) - G 4 (Black): Nuzleaf (Black)
ReCastle (B7F UTR) - G 3 (Black): Rufflet (Black)
ViRoad (1F MC) - S 1 (Black): Mandibuzz (Black)
r1 - FR 2 (Black): Gothitelle (Black)
DrTower (1F) - G 2 (Black): Unown (A) (Black)
IBGate - RG 0 (Black): Mightyena (Black)
r16 - RG 1 (Black): Watchog (Black)
LoForest - RG 5 (Black): Dwebble (Black)
ReCastle (To FrR) - G 4 (Black): Krokorok (Black)
r10 - G 3 (Black): Karrablast (Black)
r16 - G 3 (Black): Clamperl (Black)
r12 - RG 0 (Black): Throh (Black)
DeResort (O) - G 0 (Black): Hoothoot (Black)
MaBridge - RG 0 (Black): Whimsicott (Black)
r11 - DG 2 (Black): Swalot (Black)
r9 - G 5 (Black): Lairon (Black)
ReCastle (B7F TC) - G 0 (Black): Wailmer (Black)
r18 - RG 3 (Black): Persian (Black)
r13 - RG 0 (Black): Absol (Black)
r13 - RG 1 (Black): Cinccino (Black)
ReCastle (B2F Ca) - G 2 (Black): Elekid (Black)
ReCastle (To FrR) - G 5 (Black): Emolga (Black)
ReCastle (B7F TL) - G 0 (Black): Croagunk (Black)
r4 - F 2 (Black): Abra (Black)
CoStorage - RG 4 (Black): Wormadam (Trash) (Black)
ViRoad (2F RC) - G 4 (Black): Chikorita (Black)
r18 - DG 4 (Black): Cacnea (Black)
ReCastle (1F To) - G 1 (Black): Stunky (Black)
GuChamber - G 4 (Black): Volbeat (Black)
ChrgCave (1F) - G 4 (Black): Spheal (Black)
ChrgCave (B1F) - RG 3 (Black): Krabby (Black)
ChrgCave (B1F) - RG 5 (Black): Darumaka (Black)
PiForest (O) - DG 4 (Black): Oshawott (Black)
LoForest - FR 2 (Black): Psyduck (Black)
ReCastle (B7F LoC) - G 1 (Black): Pidgeot (Black)
DrDraw - RG 2 (Black): Chikorita (Black)
ChrgCave (B2F) - RG 2 (Black): Staravia (Black)
ReCastle (B5F To) - G 2 (Black): Stunky (Black)
r1 - S 0 (Black): Durant (Black)
GiChasm (EC) - F 2 (Black): Wailmer (Black)
GiChasm (EC) - G 0 (Black): Basculin (Red-Striped) (Black)
WeCave (B1F) - SR 0 (Black): Stoutland (Black)
ReCastle (B4F To) - G 1 (Black): Tauros (Black)
ViRoad (4F RC) - G 5 (Black): Seel (Black)
r12 - G 4 (Black): Mienshao (Black)
ViRoad (2F LC) - G 2 (Black): Crustle (Black)
ViBridge - G 5 (Black): Unown (Exclamation Mark) (Black)
GiChasm (OE) - G 3 (Black): Simisear (Black)
r10 - DG 1 (Black): Tangela (Black)
UnTown - SR 1 (Black): Magby (Black)
r11 - S 0 (Black): Jumpluff (Black)
MiCave (1F) - G 0 (Black): Eelektrik (Black)
LoForest - G 3 (Black): Aron (Black)
CoStorage - G 2 (Black): Nidorino (Black)
r4 - G 2 (Black): Shinx (Black)
GiChasm (EC) - FR 2 (Black): Boldore (Black)
ViRoad (3F MC) - G 5 (Black): Patrat (Black)
ReCastle (B7F RoC) - G 1 (Black): Combusken (Black)
TrChamber - G 1 (Black): Vullaby (Black)
DrCity - F 2 (Black): Stunky (Black)
r16 - DG 5 (Black): Hariyama (Black)
GiChasm (C) - G 4 (Black): Emolga (Black)
ReCastle (B7F TC) - G 1 (Black): Jumpluff (Black)
GuChamber - RG 2 (Black): Unown (Q) (Black)
r11 - RG 2 (Black): Solrock (Black)
ViRoad (O) - G 5 (Black): Houndoom (Black)
WeCave (1F) - S 0 (Black): Politoed (Black)
ViBridge - DG 3 (Black): Rotom (Fan) (Black)
IBGate - RG 4 (Black): Swanna (Black)
CoStorage - G 5 (Black): Oddish (Black)
DrCity - FR 2 (Black): Qwilfish (Black)
AbShrine - S 1 (Black): Joltik (Black)
WeCave (1F) - FR 1 (Black): Skuntank (Black)
WeCave (1F) - FR 0 (Black): Onix (Black)
ReCastle (B7F RoVE) - G 5 (Black): Girafarig (Black)
LoForest - SR 0 (Black): Scyther (Black)
GiChasm (EC) - F 0 (Black): Lotad (Black)
ViRoad (1F MC) - G 5 (Black): Elekid (Black)
ReCastle (B7F LoVE) - G 1 (Black): Mightyena (Black)
ReCastle (B6F To) - G 5 (Black): Abomasnow (Black)
ReCastle (B4F To) - G 3 (Black): Rhydon (Black)
GuChamber - G 5 (Black): Unown (T) (Black)
ReCastle (B1F Ca) - G 5 (Black): Nidoran♂ (Black)
MaBridge - RG 4 (Black): Durant (Black)
r14 - RG 0 (Black): Hitmonlee (Black)
ViRoad (1F RC) - S 1 (Black): Gligar (Black)
r13 - G 3 (Black): Bibarel (Black)
PiForest (I) - F 0 (Black): Mankey (Black)
r17 - F 1 (Black): Psyduck (Black)
ReCastle (B7F Ce) - G 2 (Black): Stoutland (Black)
ReCastle (B7F RoVE) - G 3 (Black): Gloom (Black)
ViRoad (1F RC) - FR 1 (Black): Victreebel (Black)
r16 - RG 3 (Black): Castform (Sunny) (Black)
r11 - G 2 (Black): Octillery (Black)
ReCastle (1F To) - G 3 (Black): Hippopotas (Black)
ViRoad (3F LC) - G 2 (Black): Machamp (Black)
P2Lab - G 1 (Black): Blitzle (Black)
r16 - G 2 (Black): Unown (Z) (Black)
ReCastle (B2F Ca) - G 1 (Black): Exploud (Black)
ViRoad (1F RC) - F 1 (Black): Machoke (Black)
MiCave (2F) - RG 2 (Black): Purrloin (Black)
ViRoad (1F MC) - SR 1 (Black): Conkeldurr (Black)
ReCastle (Ca BaR) - G 2 (Black): Shiftry (Black)
ViRoad (O) - G 1 (Black): Machamp (Black)
ViRoad (4F MC) - G 3 (Black): Noctowl (Black)
ChrgCave (1F) - RG 4 (Black): Unown (I) (Black)
ReCastle (B2F Ca) - G 5 (Black): Golem (Black)
MiCave (2F) - G 2 (Black): Poliwhirl (Black)
AbShrine - S 0 (Black): Gigalith (Black)
DrCity - SR 0 (Black): Qwilfish (Black)
ViRoad (5F C) - G 5 (Black): Unown (S) (Black)
r18 - DG 1 (Black): Lilligant (Black)
PiForest (I) - RG 2 (Black): Vulpix (Black)
ReCastle (B7F LoVE) - G 2 (Black): Primeape (Black)
ChlnCave (B2F) - G 0 (Black): Kabuto (Black)
r9 - DG 3 (Black): Donphan (Black)
ReCastle (B5F To) - G 4 (Black): Duosion (Black)
ViRoad (4F LC) - G 1 (Black): Murkrow (Black)
r11 - DG 3 (Black): Relicanth (Black)
ReCastle (B3F Ca) - G 0 (Black): Duosion (Black)
r16 - G 1 (Black): Cyndaquil (Black)
Dyard (B) - DG 1 (Black): Magby (Black)
r18 - FR 0 (Black): Dodrio (Black)
ReCastle (B3F Ca) - G 2 (Black): Horsea (Black)
ViRoad (3F RC) - G 1 (Black): Vanillish (Black)
ViRoad (6F C) - G 4 (Black): Turtwig (Black)
ViBridge - S 1 (Black): Skarmory (Black)
ReCastle (B7F RoTC) - G 0 (Black): Staryu (Black)
ChrgCave (B2F) - G 5 (Black): Tympole (Black)
Dyard (B) - DG 5 (Black): Jigglypuff (Black)
P2Lab - FR 2 (Black): Rhydon (Black)
r15 - RG 4 (Black): Forretress (Black)
WeCave (B1F) - SR 1 (Black): Qwilfish (Black)
ChlnCave (E) - G 5 (Black): Illumise (Black)
r12 - RG 4 (Black): Granbull (Black)
r4 - G 5 (Black): Bulbasaur (Black)
MiCave (1F) - RG 4 (Black): Swablu (Black)
ReCastle (B7F TR) - G 4 (Black): Unown (Exclamation Mark) (Black)
ReCastle (B4F Ca) - G 2 (Black): Piplup (Black)
P2Lab - F 1 (Black): Corphish (Black)
ReCastle (B7F LoTC) - G 4 (Black): Lombre (Black)
UnTown - FR 0 (Black): Ferroseed (Black)
ViRoad (4F LC) - G 4 (Black): Charmander (Black)
ReCastle (B2F To) - G 1 (Black): Quagsire (Black)
r1 - FR 1 (Black): Cinccino (Black)
r14 - RG 2 (Black): Seadra (Black)
r5 - G 3 (Black): Krabby (Black)
PiForest (I) - FR 0 (Black): Tentacool (Black)
ReCastle (B7F RoC) - G 0 (Black): Spinda (Black)
WeCave (1F) - SR 1 (Black): Dunsparce (Black)
r10 - DG 3 (Black): Vibrava (Black)
r18 - SR 0 (Black): Omastar (Black)
PiForest (I) - RG 5 (Black): Lanturn (Black)
r3 - F 2 (Black): Luxio (Black)
DrCity - F 0 (Black): Dratini (Black)
GiChasm (EC) - FR 0 (Black): Luxio (Black)
ReCastle (B7F TR) - G 2 (Black): Yanmega (Black)
CoStorage - G 1 (Black): Snorunt (Black)
WeCave (1F) - S 1 (Black): Cofagrigus (Black)
r1 - F 2 (Black): Cherrim (Overcast) (Black)
ReCastle (B4F Ca) - G 4 (Black): Staryu (Black)
ReCastle (B7F TL) - G 3 (Black): Luxio (Black)
ViRoad (4F MC) - G 0 (Black): Simisage (Black)
GiChasm (C) - G 1 (Black): Castform (Rainy) (Black)
AbShrine - FR 0 (Black): Oddish (Black)
PiForest (O) - RG 4 (Black): Seaking (Black)
IBGate - RG 1 (Black): Liepard (Black)
ViRoad (3F RC) - RG 2 (Black): Machamp (Black)
ReCastle (B7F TC) - G 3 (Black): Gloom (Black)
r3 - G 2 (Black): Staravia (Black)
ChrgCave (B1F) - RG 2 (Black): Farfetch'd (Black)
WeCave (B1F) - F 1 (Black): Wigglytuff (Black)
ViRoad (1F RC) - G 1 (Black): Poliwhirl (Black)
r3 - RG 3 (Black): Exploud (Black)
TrChamber - RG 0 (Black): Darmanitan (Black)
r13 - DG 4 (Black): Clefable (Black)
GiChasm (EC) - G 2 (Black): Sandslash (Black)
ViRoad (1F MC) - FR 0 (Black): Machoke (Black)
DeResort (O) - G 3 (Black): Growlithe (Black)
ChlnCave (B2F) - G 2 (Black): Butterfree (Black)
ViRoad (3F LC) - RG 3 (Black): Golem (Black)
ReCastle (To FrR) - G 0 (Black): Unown (C) (Black)
ReCastle (B7F UTL) - G 1 (Black): Tangela (Black)
ChlnCave (B1F) - RG 3 (Black): Electivire (Black)
ViRoad (1F LC) - RG 2 (Black): Golduck (Black)
ViRoad (1F RC) - S 0 (Black): Piloswine (Black)
ReCastle (B7F BoR) - G 4 (Black): Sandile (Black)
ViRoad (3F LC) - G 5 (Black): Unown (Q) (Black)
StCity - FR 2 (Black): Hariyama (Black)
r5 - DG 1 (Black): Shellder (Black)
ReCastle (B7F LoC) - G 4 (Black): Unown (F) (Black)
ViRoad (5F C) - G 4 (Black): Snorunt (Black)
DeResort (I) - G 1 (Black): Emolga (Black)
r13 - F 0 (Black): Combusken (Black)
GiChasm (C) - RG 4 (Black): Purugly (Black)
GiChasm (KC) - F 1 (Black): Forretress (Black)
StCity - S 1 (Black): Watchog (Black)
MiCave (1F) - RG 1 (Black): Riolu (Black)
P2Lab - F 0 (Black): Unown (Exclamation Mark) (Black)
r3 - FR 2 (Black): Lampent (Black)
AbShrine - RG 0 (Black): Lilligant (Black)
ChrgCave (B2F) - RG 5 (Black): Unown (N) (Black)
r9 - DG 2 (Black): Reuniclus (Black)
WeCave (B1F) - S 1 (Black): Linoone (Black)
P2Lab - FR 0 (Black): Electrode (Black)
r12 - RG 2 (Black): Wailmer (Black)
GiChasm (EC) - RG 3 (Black): Honchkrow (Black)
LoForest - DG 4 (Black): Bayleef (Black)
GiChasm (EC) - FR 1 (Black): Galvantula (Black)
MiCave (1F) - G 3 (Black): Unown (X) (Black)
ChlnCave (B2F) - G 4 (Black): Lampent (Black)
ChlnCave (B2F) - F 1 (Black): Hitmonchan (Black)
MiCave (2F) - RG 1 (Black): Dwebble (Black)
r15 - DG 1 (Black): Girafarig (Black)
ViBridge - RG 5 (Black): Skarmory (Black)
ReCastle (B4F Ca) - G 0 (Black): Qwilfish (Black)
ViRoad (4F RC) - RG 2 (Black): Chandelure (Black)
r1 - DG 5 (Black): Rufflet (Black)
r18 - G 3 (Black): Ledyba (Black)
PiForest (O) - RG 5 (Black): Carnivine (Black)
ReCastle (B7F UTL) - G 3 (Black): Castform (Snowy) (Black)
r15 - DG 5 (Black): Poliwrath (Black)
GiChasm (KC) - RG 1 (Black): Ambipom (Black)
ViRoad (6F C) - RG 5 (Black): Zoroark (Black)
ReCastle (B7F RoVE) - G 0 (Black): Charmander (Black)
r12 - RG 5 (Black): Plusle (Black)
ViRoad (4F RC) - RG 3 (Black): Liepard (Black)
r16 - G 0 (Black): Mareep (Black)
r9 - DG 1 (Black): Paras (Black)
GiChasm (OE) - G 1 (Black): Masquerain (Black)
ReCastle (B5F To) - G 5 (Black): Gastrodon (East) (Black)
ChlnCave (B2F) - RG 2 (Black): Houndoom (Black)
ViRoad (2F RC) - G 1 (Black): Lairon (Black)
ViRoad (4F LC) - G 0 (Black): Grumpig (Black)
ChlnCave (E) - G 4 (Black): Vanillish (Black)
DrDraw - RG 3 (Black): Oshawott (Black)
WeCave (1F) - FR 2 (Black): Illumise (Black)
ViRoad (3F RC) - RG 4 (Black): Politoed (Black)
ReCastle (B3F To) - G 4 (Black): Skiploom (Black)
ViRoad (4F LC) - G 5 (Black): Unown (V) (Black)
r5 - RG 0 (Black): Ivysaur (Black)
ViRoad (3F RC) - G 0 (Black): Galvantula (Black)
ReCastle (B7F TR) - G 1 (Black): Musharna (Black)
ViBridge - F 0 (Black): Chikorita (Black)
ReCastle (B7F RoTC) - G 2 (Black): Stunfisk (Black)
ViRoad (1F MC) - G 2 (Black): Seviper (Black)
r10 - DG 2 (Black): Unown (M) (Black)
ReCastle (B3F To) - G 0 (Black): Unown (Exclamation Mark) (Black)
P2Lab - G 4 (Black): Slakoth (Black)
LoForest - RG 1 (Black): Camerupt (Black)
ReCastle (B3F To) - G 2 (Black): Ledian (Black)
ReCastle (B6F To) - G 2 (Black): Unown (B) (Black)
ReCastle (B7F RoTC) - G 1 (Black): Solrock (Black)
ChrgCave (B1F) - RG 1 (Black): Cubchoo (Black)
WeCave (B1F) - FR 1 (Black): Sneasel (Black)
ReCastle (B2F To) - G 3 (Black): Gorebyss (Black)
UnTown - FR 1 (Black): Horsea (Black)
ChlnCave (B2F) - G 5 (Black): Cherrim (Overcast) (Black)
r17 - FR 2 (Black): Dusclops (Black)
GiChasm (OE) - G 2 (Black): Froslass (Black)
r2 - RG 2 (Black): Murkrow (Black)
GuChamber - G 3 (Black): Vulpix (Black)
MaBridge - RG 1 (Black): Mienshao (Black)
ReCastle (B5F To) - G 3 (Black): Xatu (Black)
r11 - SR 0 (Black): Farfetch'd (Black)
ReCastle (B1F To) - G 0 (Black): Chingling (Black)
LoForest - S 0 (Black): Vileplume (Black)
r12 - DG 4 (Black): Cherrim (Sunshine) (Black)
WeCave (1F) - G 2 (Black): Unown (C) (Black)
ChlnCave (B2F) - F 0 (Black): Karrablast (Black)
ReCastle (To FrR) - G 3 (Black): Vullaby (Black)
ChrgCave (B2F) - G 1 (Black): Lillipup (Black)
WeCave (1F) - G 4 (Black): Unown (R) (Black)
PiForest (O) - G 0 (Black): Barboach (Black)
ReCastle (Ca SF) - G 3 (Black): Armaldo (Black)
ReCastle (B7F LoTC) - G 2 (Black): Roserade (Black)
PiForest (I) - G 3 (Black): Pidove (Black)
ChlnCave (E) - RG 4 (Black): Mandibuzz (Black)
GiChasm (KC) - RG 3 (Black): Forretress (Black)
r13 - RG 2 (Black): Parasect (Black)
GiChasm (KC) - SR 0 (Black): Venipede (Black)
ViRoad (4F MC) - G 5 (Black): Grimer (Black)
ReCastle (B1F To) - G 5 (Black): Anorith (Black)
Dyard (B) - DG 4 (Black): Minun (Black)
ReCastle (B2F Ca) - G 4 (Black): Aipom (Black)
r14 - FR 1 (Black): Gallade (Black)
GiChasm (EC) - G 1 (Black): Chimecho (Black)
UnTown - F 0 (Black): Vulpix (Black)
ReCastle (B1F Ca) - G 0 (Black): Taillow (Black)
r14 - DG 4 (Black): Accelgor (Black)
r14 - F 1 (Black): Spiritomb (Black)
PiForest (I) - FR 1 (Black): Gastrodon (West) (Black)
CoStorage - DG 2 (Black): Unown (X) (Black)
GiChasm (OE) - RG 1 (Black): Arbok (Black)
r16 - RG 4 (Black): Stantler (Black)
Dyard (R) - DG 1 (Black): Fearow (Black)
ViRoad (4F RC) - G 1 (Black): Frillish (Black)
ChrgCave (B2F) - RG 4 (Black): Snover (Black)
DeResort (O) - G 2 (Black): Hippopotas (Black)
ViRoad (2F LC) - RG 3 (Black): Aggron (Black)
GiChasm (KC) - G 2 (Black): Kadabra (Black)
r16 - DG 2 (Black): Shellos (West) (Black)
ViRoad (1F MC) - FR 1 (Black): Sawsbuck (Autumn) (Black)
r15 - DG 4 (Black): Rhydon (Black)
WeCave (B1F) - G 4 (Black): Foongus (Black)
r18 - F 2 (Black): Cherubi (Black)
ChlnCave (B2F) - S 0 (Black): Castform (Rainy) (Black)
r9 - RG 2 (Black): Dunsparce (Black)
GuChamber - RG 3 (Black): Luvdisc (Black)
ViRoad (2F RC) - G 3 (Black): Roselia (Black)
ReCastle (B2F To) - G 5 (Black): Toxicroak (Black)
StCity - F 2 (Black): Psyduck (Black)
r3 - S 0 (Black): Sawk (Black)
GiChasm (OE) - RG 0 (Black): Primeape (Black)
WeCave (1F) - F 0 (Black): Remoraid (Black)
ViRoad (3F RC) - G 2 (Black): Torkoal (Black)
r4 - FR 0 (Black): Omastar (Black)
DrCity - SR 1 (Black): Venomoth (Black)
PiForest (I) - S 0 (Black): Amoonguss (Black)
LoForest - DG 3 (Black): Unown (Q) (Black)
GiChasm (KC) - G 5 (Black): Probopass (Black)
ReCastle (B7F Ce) - G 4 (Black): Ferroseed (Black)
ReCastle (B7F VE) - G 2 (Black): Gastrodon (West) (Black)
ViRoad (2F RC) - RG 5 (Black): Galvantula (Black)
ChlnCave (B1F) - G 1 (Black): Barboach (Black)
StCity - SR 0 (Black): Cofagrigus (Black)
MiCave (2F) - G 4 (Black): Vanillish (Black)
PiForest (I) - F 1 (Black): Flygon (Black)
GiChasm (KC) - G 3 (Black): Unown (S) (Black)
r5 - G 4 (Black): Chimecho (Black)
DeResort (O) - G 4 (Black): Rotom (Fan) (Black)
StCity - F 0 (Black): Totodile (Black)
WeCave (B1F) - G 2 (Black): Snubbull (Black)
GiChasm (OE) - DG 2 (Black): Cryogonal (Black)
LoForest - G 1 (Black): Chikorita (Black)
ReCastle (B7F UTR) - G 2 (Black): Hypno (Black)
WeCave (1F) - F 1 (Black): Cherrim (Overcast) (Black)
IBGate - RG 5 (Black): Alomomola (Black)
ViRoad (5F C) - RG 1 (Black): Kingdra (Black)
PiForest (I) - SR 0 (Black): Parasect (Black)
r5 - RG 5 (Black): Minun (Black)
ViRoad (2F LC) - RG 1 (Black): Maractus (Black)
r11 - FR 2 (Black): Roselia (Black)
ViBridge - RG 0 (Black): Ferrothorn (Black)
ChrgCave (B1F) - RG 0 (Black): Luvdisc (Black)
ReCastle (B7F LoC) - G 2 (Black): Nidoqueen (Black)
r10 - RG 3 (Black): Pidgeot (Black)
r18 - FR 2 (Black): Jolteon (Black)
GiChasm (EC) - G 3 (Black): Deerling (Autumn) (Black)
ReCastle (B7F BoR) - G 1 (Black): Rotom (Black)
ViRoad (3F LC) - RG 5 (Black): Crawdaunt (Black)
LoForest - RG 4 (Black): Stunky (Black)
Dyard (R) - RG 0 (Black): Mismagius (Black)
ViBridge - RG 2 (Black): Misdreavus (Black)
DrCity - F 1 (Black): Teddiursa (Black)
WeCave (B1F) - G 3 (Black): Cubchoo (Black)
ViRoad (1F LC) - RG 5 (Black): Nidoqueen (Black)
r14 - DG 2 (Black): Golurk (Black)
ReCastle (B7F UTL) - G 2 (Black): Altaria (Black)
ChlnCave (B1F) - G 5 (Black): Ariados (Black)
ViRoad (5F C) - RG 2 (Black): Excadrill (Black)
ReCastle (B7F RoC) - G 2 (Black): Jolteon (Black)
GiChasm (EC) - SR 0 (Black): Duosion (Black)
DeResort (I) - G 0 (Black): Diglett (Black)
ReCastle (To FrR) - G 1 (Black): Simipour (Black)
ChrgCave (B1F) - G 1 (Black): Bonsly (Black)
ViRoad (2F RC) - G 0 (Black): Sawsbuck (Autumn) (Black)
ReCastle (B7F Ce) - G 0 (Black): Elgyem (Black)
IBGate - G 0 (Black): Onix (Black)
ReCastle (B7F TL) - G 4 (Black): Unown (Exclamation Mark) (Black)
ViRoad (3F RC) - RG 5 (Black): Relicanth (Black)
ReCastle (VR) - G 5 (Black): Magmar (Black)
r11 - RG 3 (Black): Gligar (Black)
r15 - RG 0 (Black): Throh (Black)
MiCave (2F) - RG 0 (Black): Pikachu (Black)
ReCastle (B6F To) - G 1 (Black): Shiftry (Black)
WeCave (1F) - RG 1 (Black): Rufflet (Black)
StCity - FR 0 (Black): Squirtle (Black)
ViRoad (1F MC) - F 2 (Black): Flaaffy (Black)
ChlnCave (B1F) - G 2 (Black): Magby (Black)
ReCastle (1F To) - G 0 (Black): Glameow (Black)
r1 - F 0 (Black): Rapidash (Black)
r10 - RG 5 (Black): Conkeldurr (Black)
GiChasm (OE) - DG 1 (Black): Magcargo (Black)
GiChasm (EC) - RG 4 (Black): Mienshao (Black)
ChrgCave (B1F) - G 4 (Black): Finneon (Black)
ViRoad (2F RC) - RG 2 (Black): Hydreigon (Black)
MaBridge - RG 3 (Black): Rotom (Black)
ChrgCave (B2F) - G 2 (Black): Cherubi (Black)
ChrgCave (1F) - RG 1 (Black): Stunky (Black)
ChlnCave (B1F) - RG 4 (Black): Rotom (Fan) (Black)
DeResort (O) - G 1 (Black): Shinx (Black)
StCity - F 1 (Black): Golem (Black)
r12 - G 2 (Black): Camerupt (Black)
r5 - RG 3 (Black): Reuniclus (Black)
PiForest (O) - G 5 (Black): Yamask (Black)
ReCastle (B7F UTL) - G 4 (Black): Unown (U) (Black)
P2Lab - RG 2 (Black): Gabite (Black)
ViRoad (1F LC) - G 1 (Black): Unown (F) (Black)
P2Lab - SR 1 (Black): Glalie (Black)
ReCastle (B7F UTR) - G 0 (Black): Palpitoad (Black)
LoForest - RG 2 (Black): Ferrothorn (Black)
r3 - F 1 (Black): Hitmonchan (Black)
r9 - RG 5 (Black): Solrock (Black)
ViBridge - FR 1 (Black): Piloswine (Black)
ReCastle (B7F RoTC) - G 4 (Black): Loudred (Black)
r18 - RG 4 (Black): Simisear (Black)
ReCastle (B2F To) - G 4 (Black): Delcatty (Black)
GiChasm (KC) - S 0 (Black): Claydol (Black)
r3 - F 0 (Black): Munna (Black)
ViRoad (6F C) - G 0 (Black): Basculin (Red-Striped) (Black)
IBGate - G 5 (Black): Froslass (Black)
r14 - SR 0 (Black): Aipom (Black)
P2Lab - G 3 (Black): Roselia (Black)
r11 - DG 5 (Black): Basculin (Red-Striped) (Black)
ReCastle (B2F To) - G 0 (Black): Staryu (Black)
r10 - DG 4 (Black): Rotom (Frost) (Black)
r11 - SR 1 (Black): Scolipede (Black)
GiChasm (KC) - G 0 (Black): Victreebel (Black)
ViRoad (1F MC) - RG 2 (Black): Aerodactyl (Black)
r9 - DG 5 (Black): Blaziken (Black)
ReCastle (B3F To) - G 3 (Black): Tentacruel (Black)
DrDraw - RG 4 (Black): Ferroseed (Black)
ViRoad (2F RC) - RG 4 (Black): Tentacruel (Black)
ChrgCave (B1F) - G 0 (Black): Lombre (Black)
ViRoad (1F RC) - FR 0 (Black): Wailmer (Black)
GiChasm (C) - RG 2 (Black): Lilligant (Black)
r3 - DG 4 (Black): Nuzleaf (Black)
r1 - S 1 (Black): Mr. Mime (Black)
ViRoad (3F RC) - RG 1 (Black): Ferrothorn (Black)
ViRoad (2F LC) - G 1 (Black): Drilbur (Black)
r14 - RG 1 (Black): Staraptor (Black)
ReCastle (B7F TR) - G 3 (Black): Duosion (Black)
ViRoad (2F RC) - G 2 (Black): Miltank (Black)
DeResort (I) - G 5 (Black): Scizor (Black)
AbShrine - DG 2 (Black): Timburr (Black)
CoStorage - DG 0 (Black): Swadloon (Black)
r16 - RG 2 (Black): Sunflora (Black)
ChlnCave (B2F) - FR 1 (Black): Girafarig (Black)
ViRoad (1F MC) - RG 1 (Black): Muk (Black)
GiChasm (C) - RG 3 (Black): Ivysaur (Black)
WeCave (B1F) - FR 2 (Black): Magcargo (Black)
Dyard (R) - RG 3 (Black): Misdreavus (Black)
WeCave (1F) - RG 0 (Black): Clefairy (Black)
ChrgCave (B2F) - RG 1 (Black): Smoochum (Black)
r14 - FR 0 (Black): Cacnea (Black)
LoForest - FR 0 (Black): Unown (B) (Black)
CoStorage - G 3 (Black): Blitzle (Black)
ViRoad (3F MC) - G 1 (Black): Haunter (Black)
CeTower (3F) - G 0 (Black): Budew (Black)
GiChasm (KC) - FR 1 (Black): Raichu (Black)
ReCastle (B1F Ca) - G 2 (Black): Pansear (Black)
PiForest (I) - RG 4 (Black): Unown (Exclamation Mark) (Black)
r11 - RG 4 (Black): Tangela (Black)
r11 - S 1 (Black): Spheal (Black)
GiChasm (OE) - G 4 (Black): Mr. Mime (Black)
CoStorage - G 4 (Black): Shellos (East) (Black)
TrChamber - RG 2 (Black): Absol (Black)
ReCastle (B7F TC) - G 2 (Black): Crawdaunt (Black)
r16 - RG 5 (Black): Liepard (Black)
ViRoad (4F MC) - G 1 (Black): Stantler (Black)
CoStorage - RG 3 (Black): Girafarig (Black)
r15 - RG 5 (Black): Vigoroth (Black)
r5 - G 5 (Black): Raichu (Black)
ViRoad (4F LC) - G 2 (Black): Kangaskhan (Black)
MiCave (1F) - G 2 (Black): Kricketune (Black)
LoForest - DG 1 (Black): Beedrill (Black)
GiChasm (C) - DG 0 (Black): Unown (R) (Black)
PiForest (I) - FR 2 (Black): Swoobat (Black)
ViRoad (1F RC) - G 4 (Black): Pansear (Black)
ViBridge - RG 4 (Black): Victreebel (Black)
r3 - FR 0 (Black): Dratini (Black)
ReCastle (B7F LoC) - G 0 (Black): Mudkip (Black)
r15 - G 3 (Black): Ferrothorn (Black)
r15 - G 5 (Black): Illumise (Black)
r18 - RG 0 (Black): Arbok (Black)
LoForest - DG 2 (Black): Oddish (Black)
r9 - RG 4 (Black): Castform (Snowy) (Black)
r15 - RG 1 (Black): Rotom (Black)
r10 - DG 0 (Black): Larvesta (Black)
ReCastle (B7F RoTC) - G 5 (Black): Xatu (Black)
r13 - F 1 (Black): Marill (Black)
Desert Resort Static Encounter 1 (Black): Darmanitan (Black)
Desert Resort Static Encounter 2 (Black): Darmanitan (Black)
Desert Resort Static Encounter 3 (Black): Darmanitan (Black)
Desert Resort Static Encounter 4 (Black): Darmanitan (Black)
Desert Resort Static Encounter 5 (Black): Darmanitan (Black)
Dreamyard Static Encounter (Black): Musharna (Black)
Relic Castle Static Encounter (Black): Volcarona (Black)
Route 6 Item Encounter 1 (Black): Foongus (Black)
Route 6 Item Encounter 2 (Black): Foongus (Black)
Route 10 Item Encounter 1 (Black): Foongus (Black)
Route 10 Item Encounter 2 (Black): Foongus (Black)
Route 10 Item Encounter 3 (Black): Amoonguss (Black)
Route 10 Item Encounter 4 (Black): Amoonguss (Black)
Lostlorn Forest Static Encounter (Black): Zoroark (Black)
Guidance Chamber Static Encounter (Black): Cobalion (Black)
Trial Chamber Static Encounter (Black): Terrakion (Black)
Rumination Field Static Encounter (Black): Virizion (Black)
Abundant Shrine Static Encounter (Black): Landorus (Black)
Giant Chasm Static Encounter (Black): Kyurem (Black)
Liberty Garden Static Encounter (Black): Victini (Black)
Dragonspiral Tower Static Encounter (Black): Reshiram (Black)
Roaming Encounter (Black): Tornadus (Black)
Root Fossil Reanimation (Black): Lileep (Black)
Claw Fossil Reanimation (Black): Anorith (Black)
Helix Fossil Reanimation (Black): Omanyte (Black)
Dome Fossil Reanimation (Black): Kabuto (Black)
Old Amber Reanimation (Black): Aerodactyl (Black)
Armor Fossil Reanimation (Black): Shieldon (Black)
Skull Fossil Reanimation (Black): Cranidos (Black)
Cover Fossil Reanimation (Black): Tirtouga (Black)
Plume Fossil Reanimation (Black): Archen (Black)
Marvelous Bridge Sold Encounter (Black): Magikarp (Black)
Route 18 Egg Encounter (Black): Larvesta (Black)
Castelia City Gift Encounter (Black): Zorua (Black)
Nacrene City Trade Encounter (Black): Petilil (Black)
Driftveil City Trade Encounter (Black): Basculin (Red-Striped) (Black)
Route 7 Trade Encounter (Black): Emolga (Black)
Route 15 Trade Encounter (Black): Rotom (Black)
Undella Town Trade Encounter (Black): Munchlax (Black)"""

if __name__ == "__main__":
    b = a.splitlines()
    b.sort()
    for line in b:
        print(line)
